# The two main questions we answer (the business requirement / problem)
- Environmental impact on accidents (location, weather/season, time of day)
- Manufacturer Confidence Analysis (Can they be trusted)

In [ ]:
# sources:
# https://aviation-safety.net/database/

In [ ]:
import pandas as pd
import numpy as np

## Dataframe 1

In [ ]:
url = "https://raw.githubusercontent.com/oshani-jayawardane/aircraft-accident-project/main/aviation_accidents_2000_2025_merged.csv"
df = pd.read_csv(url)

df.head()

,Event No.,Year,List Date,Detail URL,Time,Type,Owner/operator,Registration,MSN,Total airframe hrs,...,Location,Phase,Nature,Departure airport,Destination airport,Investigating agency,Confidence Rating,Narrative,Year of manufacture,Cycles
0,1,2000,1 Jan 2000,https://aviation-safety.net/wikibase/299408,13:00 LT,Cessna 550 Citation II,US Customs Service,N752CC,550-0018,12159 hours,...,"HOMESTEAD, Florida - United States of America",Unknown,Ferry/positioning,"MIAMI , FL (KTMB)",(KHST),NTSB,Accident investigation report completed and in...,The pilot-in-command (PIC) stated he was in cr...,NaN,NaN
1,2,2000,3 Jan 2000,https://aviation-safety.net/wikibase/323589,NaN,Beechcraft 200 Super King Air,Kalahari Air Services & Charter,A2-AEZ,BB-421,NaN,...,unknown location - Unknown country,Unknown,Unknown,NaN,NaN,NaN,Little or no information is available,Damaged beyond repair.,1978.0,NaN
2,3,2000,4 Jan 2000,https://aviation-safety.net/wikibase/299403,17:25 LT,Beechcraft B200 Super King Air,Private,N895TT,BB-1239,3238 hours,...,"JACKSON, Wyoming - United States of America",Unknown,Private,"GRAND ISLAND , NE (KGRI)",(KJAC),NTSB,Accident investigation report completed and in...,While performing the ILS runway 18 approach to...,1986.0,NaN
3,4,2000,5 Jan 2000,https://aviation-safety.net/wikibase/323588,13:25,Embraer EMB-110P1A Bandeirante,Skypower Express Airways,5N-AXL,110455,NaN,...,Abuja International Airport (ABV) - Nigeria,Approach,Passenger - Scheduled,Lagos-Murtala Muhammed International Airport (...,Abuja International Airport (ABV/DNAA),NaN,Information verified through data from acciden...,The Bandeirante aircraft was coming in to land...,1984.0,NaN
4,5,2000,7 Jan 2000,https://aviation-safety.net/wikibase/323587,NaN,Antonov An-26,Unknown,D2-FBR,7206,NaN,...,- Angola,Unknown,Cargo,Luanda-4 de Fevereiro Airport (LAD/FNLU),Cafunfo Airport (CFF/FNCF),NaN,NaN,Disappeared near the border of the Angolan pro...,1978.0,NaN

In [ ]:
df.shape

(6848, 25)

In [ ]:
# convert to datetime -- here safe to convert casue we already have a seperate year column

df['List Date'] = pd.to_datetime(df['List Date'], format='%d %b %Y', errors='coerce')
df.head(2)

,Event No.,Year,List Date,Detail URL,Time,Type,Owner/operator,Registration,MSN,Total airframe hrs,...,Location,Phase,Nature,Departure airport,Destination airport,Investigating agency,Confidence Rating,Narrative,Year of manufacture,Cycles
0,1,2000,2000-01-01,https://aviation-safety.net/wikibase/299408,13:00 LT,Cessna 550 Citation II,US Customs Service,N752CC,550-0018,12159 hours,...,"HOMESTEAD, Florida - United States of America",Unknown,Ferry/positioning,"MIAMI , FL (KTMB)",(KHST),NTSB,Accident investigation report completed and in...,The pilot-in-command (PIC) stated he was in cr...,NaN,NaN
1,2,2000,2000-01-03,https://aviation-safety.net/wikibase/323589,NaN,Beechcraft 200 Super King Air,Kalahari Air Services & Charter,A2-AEZ,BB-421,NaN,...,unknown location - Unknown country,Unknown,Unknown,NaN,NaN,NaN,Little or no information is available,Damaged beyond repair.,1978.0,NaN

In [ ]:
# there are this many date unknown entries, but the year column has the year

df['List Date'].isna().sum()

np.int64(61)

In [ ]:
df.columns

In [ ]:
# drop unwanted columns
df = df.drop(columns=['Detail URL', 'MSN', 'Investigating agency', 'Cycles', 'Other fatalities'], errors='ignore')

# rename columns
df = df.rename(columns={
    'Event No.'           : 'Event_No',
    'List Date'           : 'Incident_Date',
    'Type'                : 'Aircaft_Model',
    'Registration'        : 'Aircaft_Registration',
    'Owner/operator'      : 'Aircaft_Operator',
    'Total airframe hrs'  : 'Total_Flight_Hours',
    'Engine model'        : 'Engine_Model',
    'Aircraft damage'     : 'Aircaft_Damage_Type',
    'Category'            : 'Incident_Category',
    'Location'            : 'Incident_Location',
    'Phase'               : 'Aircraft_Phase',
    'Nature'              : 'Aircaft_Nature',
    'Departure airport'   : 'Departure_Airport',
    'Destination airport' : 'Destination_Airport',
    'Confidence Rating'   : 'Confidence_Rating',
    'Year of manufacture' : 'Aircraft_Manufacture_Year'
})

desired_order = [
    'Event_No', 'Incident_Date', 'Year', 'Time',
    'Incident_Category', 'Aircaft_Damage_Type', 'Aircraft_Phase', 'Incident_Location', 'Fatalities',
    'Aircaft_Nature', 'Aircaft_Registration', 'Aircaft_Model', 'Aircaft_Operator', 'Engine_Model',
    'Departure_Airport', 'Destination_Airport', 'Aircraft_Manufacture_Year', 'Total_Flight_Hours',
    'Confidence_Rating', 'Narrative'
]

# keep the columns in your desired order and then append the rest (so nothing gets lost)
df = df[desired_order + [col for col in df.columns if col not in desired_order]]

# drop duplicates
df = df.drop_duplicates()

df.head(3)

## Dataframe 2

In [ ]:
url2 = "https://raw.githubusercontent.com/oshani-jayawardane/aircraft-accident-project/main/Aircraft_Incident_Dataset.csv"
df2 = pd.read_csv(url2)

df2.head()

,Incident_Date,Aircaft_Model,Aircaft_Registration,Aircaft_Operator,Aircaft_Nature,Incident_Category,Incident_Cause(es),Incident_Location,Aircaft_Damage_Type,Date,...,Onboard_Crew,Onboard_Passengers,Onboard_Total,Fatalities,Aircaft_First_Flight,Aircraft_Phase,Departure_Airport,Destination_Airport,Ground_Casualties,Collision_Casualties
0,03-JAN-2022,British Aerospace 4121 Jetstream 41,ZS-NRJ,SA Airlink,Domestic Non Scheduled Passenger,Accident | repairable-damage,"Airplane - Engines, Airplane - Engines - Prop/...",near Venetia Mine...,Substantial,Monday 3 January 2022,...,Fatalities: 0 / Occupants: 3,Fatalities: 0 / Occupants: 4,Fatalities: 0 / Occupants: 7,0,1995-05-19 (26 years 8 months),Landing (LDG),Johannesburg-O.R. Tambo International Airport ...,"Venetia Mine Airport (FAVM) , South Africa",NaN,NaN
1,04-JAN-2022,British Aerospace 3101 Jetstream 31,HR-AYY,LANHSA,Domestic Scheduled Passenger,Accident | repairable-damage,"Airplane - Undercarriage, Airplane - Undercarr...",Roatán-Juan ...,Substantial,Tuesday 4 January 2022,...,Fatalities: 0 / Occupants:,Fatalities: 0 / Occupants:,Fatalities: 0 / Occupants: 19,0,1985,Landing (LDG),La Ceiba-Goloson International Airport (LCE/MH...,Roatán-Juan Manuel Gálvez International Airpor...,NaN,NaN
2,05-JAN-2022,Boeing 737-4H6,EP-CAP,Caspian Airlines,Domestic Scheduled Passenger,Accident | repairable-damage,"Airplane - Undercarriage, Airplane - Undercarr...",Isfahan-Shah...,Substantial,Wednesday 5 January 2022,...,Fatalities: 0 / Occupants:,Fatalities: 0 / Occupants:,Fatalities: 0 / Occupants: 116,0,1992-09-18 (29 years 4 months),Landing (LDG),"Mashhad Airport (MHD/OIMM) , Iran","Isfahan-Shahid Beheshti Airport (IFN/OIFM) , Iran",NaN,NaN
3,08-JAN-2022,Tupolev Tu-204-100C,RA-64032,"Cainiao, opb Aviastar-TU",Cargo,Accident | hull-loss,"Cargo - Fire/smoke, Result - Damaged on the gr...",Hangzhou-Xia...,Destroyed,Saturday 8 January 2022,...,Fatalities: 0 / Occupants: 8,Fatalities: 0 / Occupants: 0,Fatalities: 0 / Occupants: 8,0,2002-07-18 (19 years 6 months),Standing (STD),Hangzhou-Xiaoshan International Airport (HGH/Z...,"Novosibirsk-Tolmachevo Airport (OVB/UNNT) , Ru...",NaN,NaN
4,12-JAN-2022,Beechcraft 200 Super King Air,NaN,private,Illegal Flight,"Criminal occurrence (sabotage, shoot down) | h...",Result - Damaged on the ground,"Machakilha, ...",Damaged beyond repair,Wednesday 12 January 2022,...,Fatalities: 0 / Occupants: 0,Fatalities: 0 / Occupants: 0,Fatalities: 0 / Occupants: 0,0,NaN,Standing (STD),?,?,NaN,NaN

In [ ]:
df.shape

(6848, 25)

In [ ]:
df2.columns

In [ ]:
# drop unnecessary columns from df2

df2 = df2.drop(columns=['Onboard_Crew', 'Onboard_Passengers', 'Fatalities', 'Date', 'Arit'], errors='ignore')
df2.head(2)

In [ ]:
# extract year - since Incident_Date has some missing dates

df2['Year'] = df2['Incident_Date'].astype(str).str.extract(r'(\d{4})').astype('Int64')
df2['Year'].isna().sum()

In [ ]:
# now convert incident date to date time format
df2['Incident_Date'] = pd.to_datetime(df2['Incident_Date'], format='%d-%b-%Y', errors='coerce')

In [ ]:
# 1) Rename columns in df2
df2 = df2.rename(columns={
    'Onboard_Total'        : 'Fatalities',
    'Aircaft_Engines'      : 'Engine_Model',
    'Aircaft_First_Flight' : 'Aircraft_Manufacture_Year'
})

# 2) Reorder columns in the desired order
desired_order_df2 = [
    'Incident_Date', 'Year', 'Time',
    'Incident_Category', 'Aircaft_Damage_Type', 'Aircraft_Phase', 'Incident_Location',
    'Fatalities', 'Ground_Casualties', 'Collision_Casualties', 'Incident_Cause(es)',
    'Aircaft_Nature', 'Aircaft_Registration', 'Aircaft_Model', 'Aircaft_Operator', 'Engine_Model',
    'Departure_Airport', 'Destination_Airport', 'Aircraft_Manufacture_Year'
]

df2 = df2[desired_order_df2 + [col for col in df2.columns if col not in desired_order_df2]]

# drop duplicates
df2 = df2.drop_duplicates()

df2.head(2)

In [ ]:
df2.columns

In [ ]:
cols = ['Departure_Airport', 'Destination_Airport']

for c in cols:
    df2[c] = df2[c].replace(r'^\?+$', np.nan, regex=True)

# Data Cleaning

In [ ]:
# filter out only the necessary years - from 2000 to 2018

df = df[(df['Year'] >= 2000) & (df['Year'] <= 2018)]
df2 = df2[(df2['Year'] >= 2000) & (df2['Year'] <= 2018)]

print(len(df))
print(len(df2))

In [ ]:
# sort dates from 2000 to 2018 ascending

df = df.sort_values(by='Incident_Date', ascending=True)
df2 = df2.sort_values(by='Incident_Date', ascending=True)

In [ ]:
df.head(2)

In [ ]:
df2.head(2)

#### Merge Datasets
To merge, we have to find common unique combinations since the date is not unique. There are multiple entries per single date

In [ ]:
print(len(df))          # 5283
print(len(df2))         # 3954

In [ ]:
# to check for duplicaions that are not null

keys = ['Incident_Date', 'Aircaft_Registration', 'Aircaft_Model']

dup_df  = df[df[keys].notna().all(axis=1) & df[keys].duplicated(keep=False)]
dup_df2 = df2[df2[keys].notna().all(axis=1) & df2[keys].duplicated(keep=False)]

print(len(dup_df))
print(len(dup_df2))

In [ ]:
dupes = df2[df2.duplicated(['Incident_Date', 'Aircaft_Registration', 'Aircaft_Model'], keep=False)]
print(len(dupes))
dupes

In [ ]:
# drop the duplicating observation from df2
df2 = df2.drop(index=3393).reset_index(drop=True)
dupes = df2[df2.duplicated(['Incident_Date', 'Aircaft_Registration', 'Aircaft_Model'], keep=False)]
print(len(dupes))
dupes

In [ ]:
dupes = df[df.duplicated(['Incident_Date', 'Aircaft_Registration', 'Aircaft_Model'], keep=False)]
print(len(dupes))
dupes

In [ ]:
# drop the duplicating observation from df2
df = df.drop(index=74	).reset_index(drop=True)
df = df.drop(index=606	).reset_index(drop=True)
df = df.drop(index=1181	).reset_index(drop=True)
df = df.drop(index=3081	).reset_index(drop=True)
df = df.drop(index=4196	).reset_index(drop=True)
dupes = df2[df2.duplicated(['Incident_Date', 'Aircaft_Registration', 'Aircaft_Model'], keep=False)]
print(len(dupes))
dupes

i decided to clean the df2 and merge in any columns from df that makes sense

In [ ]:
df2.columns

In [ ]:
# Incident_Category
# Aircraft_Phase
# Fatalities
# Ground_Casualties
# Collision_Casualties
# Incident_Cause(es)

In [ ]:
df.columns

In [ ]:
print(len(df))
print(len(df2))

In [ ]:
print(df['Incident_Date'].isna().sum())
print(df2['Incident_Date'].isna().sum())
print(df['Aircaft_Registration'].isna().sum())
print(df2['Aircaft_Registration'].isna().sum())

In [ ]:
########################## This code is just a sanity check #######################################

# here we check for entries with incident date and aircraft registration and we get all datasets that have matching entries.
key_cols = ['Incident_Date', 'Aircaft_Registration']

# 2. Find common (non-key) columns
common_cols = df.columns.intersection(df2.columns).tolist()
value_cols  = [c for c in common_cols if c not in key_cols]

# 3. Build a merged dataframe on the keys
merged = pd.merge(
    df[key_cols + value_cols],
    df2[key_cols + value_cols],
    on=key_cols,
    how='inner',
    suffixes=('_df', '_df2')
)

print("Common key matches:", len(merged))

# 4. Loop over each common feature and show comparisons
n = 10  # how many random entries per feature

for col in value_cols:
    col_df  = f'{col}_df'
    col_df2 = f'{col}_df2'

    sub = merged[key_cols + [col_df, col_df2]].copy()

    if sub.empty:
        continue

    # random sample up to n rows
    sub = sub.sample(n=min(n, len(sub)), random_state=0)

    # rename for display
    sub = sub.rename(columns={col_df: 'df', col_df2: 'df2'})

    print(f'\nFeature: {col}')
    print(sub.to_string(index=False))

In [ ]:
# we take different entries from different datasets

# first we only consider entries where 'Incident_Date' and 'Aircaft_Registration' is non-nan in df2 and we do this:

# create a copy of the df as new_df

# overwrite entires of columns new_df 'Aircraft_Phase', 'Incident_Category' in df that match the unique 'Incident_Date' and 'Aircaft_Registration' combination
# add new columns 'Incident_Cause(es)', 'Ground_Casualties', 'Collision_Casualties', to the new dataframe from df2 based on unique combinations of 'Incident_Date' and 'Aircaft_Registration'

# leave the following columns of new_df without overwriting, unless the entries are nan
# 'Year', 'Time', 'Event_No', 'Aircaft_Damage_Type', 'Incident_Location', 'Aircaft_Nature', 'Fatalities', 'Aircaft_Model', 'Aircaft_Operator', 'Engine_Model', 'Departure_Airport', 'Destination_Airport',
# 'Aircraft_Manufacture_Year', 'Total_Flight_Hours', 'Confidence_Rating', 'Narrative' stays as it is in df

new_df = df.copy()

key_cols = ['Incident_Date', 'Aircaft_Registration']

df2_unique_combos = (df2.dropna(subset=key_cols).sort_values(key_cols).drop_duplicates(subset=key_cols, keep='first')) # ensure unique combos

print(len(df2_unique_combos))
print(len(df2))
print(len(df2) - len(df2_unique_combos))
print(len(df2[df2['Incident_Date'].isna() | df2['Aircaft_Registration'].isna()]))

In [ ]:
new_df.head(3)

In [ ]:
# add new columns from df2
cols_to_add = ['Incident_Cause(es)', 'Ground_Casualties', 'Collision_Casualties']

# keep only key + those columns from df2_unique_combos
df2_subset = df2_unique_combos[key_cols + cols_to_add]

print("len new_df before merge: ", len(new_df))

# left-join: keep all rows from new_df, add matching info from df2_unique_combos
new_df = new_df.merge(df2_subset, on=key_cols, how='left')

print("len new_df after merge: ", len(new_df))

new_df.head(3)

In [ ]:
# cols to overwrite from df2 : 'Aircraft_Phase', 'Incident_Category'
for col_to_overwrite in ['Aircraft_Phase', 'Incident_Category']:
    if col_to_overwrite not in df2_unique_combos.columns:
        continue
    df2_subset_overwrite = (
        df2_unique_combos[key_cols + [col_to_overwrite]]
        .dropna(subset=[col_to_overwrite])
    )
    new_df = new_df.merge(
        df2_subset_overwrite,
        on=key_cols,
        how='left',
        suffixes=('', '_df2')
    )
    new_df[col_to_overwrite] = new_df[f'{col_to_overwrite}_df2'].combine_first(new_df[col_to_overwrite])
    new_df = new_df.drop(columns=[f'{col_to_overwrite}_df2'])

print("len new_df after merge: ", len(new_df))

new_df.head(3)

In [ ]:
# if any of these values are missing, fill them

fill_cols = [
    'Time', 'Aircaft_Damage_Type', 'Incident_Location',
    'Aircaft_Nature', 'Fatalities', 'Aircaft_Model', 'Aircaft_Operator',
    'Engine_Model', 'Departure_Airport', 'Destination_Airport',
    'Aircraft_Manufacture_Year'
]

fill_cols_existing = [c for c in fill_cols if c in df2_unique_combos.columns]

df2_fill = df2_unique_combos[key_cols + fill_cols_existing].copy()

new_df = new_df.merge(
    df2_fill,
    on=key_cols,
    how='left',
    suffixes=('', '_df2')
)

for col in fill_cols_existing:
    col_df2 = f'{col}_df2'
    if col_df2 in new_df.columns:
        # keep existing values in new_df[col], fill only NaNs from df2
        new_df[col] = new_df[col].combine_first(new_df[col_df2])

helper_cols = [c for c in new_df.columns if c.endswith('_df2')]
new_df = new_df.drop(columns=helper_cols)

len(new_df)

In [ ]:
new_df.head(10)

In [ ]:
pattern = r'Fatalities:\s*(\d*)\s*/?\s*[\n\r]*\s*Occupants:\s*(\d*)'

df_extract = new_df['Fatalities'].astype(str).str.extract(pattern)
df_extract = df_extract.replace('', np.nan).astype(float)
df_extract.columns = ['Fatalities_num', 'Occupants_num']

new_df['Fatalities_clean'] = df_extract['Fatalities_num']
new_df['Occupants'] = df_extract['Occupants_num']

new_df = new_df.drop(columns=['Fatalities'])

new_df = new_df.rename(columns={'Fatalities_clean': 'Fatalities'})

new_df.head(10)

In [ ]:
new_df.columns

Dealing with Ground casualities and collision casualities

In [ ]:
new_df['Ground_Casualties'] = (
    new_df['Ground_Casualties']
    .str.extract(r'(\d+)')   # extract numbers
    .astype(float)           # convert to float
    .fillna(0)               # replace NaN with 0
)

new_df['Collision_Casualties'] = (
    new_df['Collision_Casualties']
    .str.extract(r'(\d+)')   # extract numbers
    .astype(float)           # convert to float
    .fillna(0)               # replace NaN with 0
)

# All Ground_Casualties and Collision_Casualties are now fatality values

In [ ]:
new_df.head(10)

In [ ]:
new_df.columns

Add lat and lon of airports

In [ ]:
! pip install airportsdata

In [ ]:
import airportsdata

new_df['Departure_Airport_Code'] = new_df['Departure_Airport'].str.extract(r'\((.*?)\)')
new_df['Departure_Airport'] = new_df['Departure_Airport'].str.replace(r'\([^)]*\)', '').str.strip()
new_df.replace('unknown airport', np.nan, inplace = True)
new_df['Destination_Airport_Code'] = new_df['Destination_Airport'].str.extract(r'\((.*?)\)')
new_df['Destination_Airport'] = new_df['Destination_Airport'].str.replace(r'\([^)]*\)', '').str.strip()
new_df['Departure_IATA'] = new_df['Departure_Airport_Code'].str.extract(r'([A-Z]{3})')
new_df['Destination_IATA'] = new_df['Destination_Airport_Code'].str.extract(r'([A-Z]{3})')
new_df[['Departure_Airport', 'Departure_Airport_Code', 'Destination_Airport', 'Destination_Airport_Code', 'Departure_IATA', 'Destination_IATA']].head()

In [ ]:
airports = airportsdata.load('IATA')

def get_airport_info(code, info_type):
    info = airports.get(code)
    return info[info_type] if info else np.nan

new_df['Dep_Lat'] = new_df['Departure_IATA'].map(lambda x: get_airport_info(x, 'lat'))
new_df['Dep_Lon'] = new_df['Departure_IATA'].map(lambda x: get_airport_info(x, 'lon'))

new_df['Dest_Lat'] = new_df['Destination_IATA'].map(lambda x: get_airport_info(x, 'lat'))
new_df['Dest_Lon'] = new_df['Destination_IATA'].map(lambda x: get_airport_info(x, 'lon'))

new_df.head()

# Analysis

In [ ]:
new_df.columns

In [ ]:
new_df['Year'].isna().sum()

In [ ]:
new_df['Aircraft_Phase'].unique()

In [ ]:
canonical_map = {
    'Unknown': 'Unknown',
    'Unknown (UNK)': 'Unknown',

    'Standing': 'Standing',
    'Standing (STD)': 'Standing',

    'Pushback / towing': 'Ground Handling',
    'Pushback / towing (PBT)': 'Ground Handling',

    'Taxi': 'Taxi',
    'Taxi (TXI)': 'Taxi',

    'Takeoff (TOF)': 'Takeoff',
    'Take off': 'Takeoff',

    'Initial climb': 'Initial Climb',
    'Initial climb (ICL)': 'Initial Climb',

    'En route': 'En Route',
    'En route (ENR)': 'En Route',

    'Approach (APR)': 'Approach',
    'Approach': 'Approach',

    'Landing': 'Landing',
    'Landing (LDG)': 'Landing',

    'Manoeuvring (airshow, firefighting, ag.ops.)': 'Maneuvering',
    'Maneuvering (MNV)': 'Maneuvering',
}


new_df['Aircraft_Phase'] = (
    new_df['Aircraft_Phase']
    .replace(canonical_map)
    .fillna('Unknown')     # optional
)

new_df['Aircraft_Phase'].unique()

In [ ]:
new_df['Incident_Category'].unique()

In [ ]:
new_df['Incident'] = new_df['Incident_Category'].str.split(r'\s*\|\s*', n=1).str[0].replace('', np.nan)
new_df['Damage'] = new_df['Incident_Category'].str.split(r'\s*\|\s*', n=1).str[1].replace('', np.nan)
new_df = new_df.drop(columns=['Incident_Category'])

print(new_df['Incident'].unique())

In [ ]:
incident_group_map = {
    'Accident': 'Accident',
    'Serious incident': 'Serious Incident',
    'Incident': 'Incident',

    'Hijacking': 'Hijacking',
    'Unlawful Interference': 'Hijacking',

    'Criminal occurrence (sabotage, shoot down)': 'Criminal',

    'other occurrence (ground fire, sabotage)': 'Other Occurrence',
    'Other': 'Other Occurrence',

    'occurrence unknown': 'Unknown',
    'UK': 'Unknown',
    'Unknown': 'Unknown'
}

new_df['Incident'] = new_df['Incident'].fillna('Unknown')
new_df['Incident'] = new_df['Incident'].map(incident_group_map).fillna('Unknown')

print(new_df['Incident'].unique())

In [ ]:
print(new_df['Damage'].unique())

In [ ]:
new_df['Aircaft_Damage_Type'].unique()

In [ ]:
# fill NaNs in Aircaft_Damage_Type using Damage where available
mask = new_df['Aircaft_Damage_Type'].isna() & new_df['Damage'].notna()
new_df.loc[mask, 'Aircaft_Damage_Type'] = new_df.loc[mask, 'Damage']

new_df = new_df.drop(columns=['Damage'])

new_df['Aircaft_Damage_Type'].unique()

In [ ]:
new_df['Aircaft_Damage_Type'] = new_df['Aircaft_Damage_Type'].fillna('Unknown')

damage_map = {
    'Substantial': 'Substantial',
    'Substantial, repaired': 'Repairable',
    'Substantial, written off': 'Destroyed',

    'Minor': 'Minor',
    'Minor, repaired': 'Repairable',
    'Minor, written off': 'Destroyed',

    'repairable-damage': 'Repairable',

    'Destroyed': 'Destroyed',
    'Destroyed, written off': 'Destroyed',

    'Aircraft missing': 'Missing',
    'Aircraft missing, written off': 'Missing',

    'None, repaired': 'Repairable',

    'Unknown': 'Unknown',
    'Unknown, repaired': 'Repairable',
    'Unknown, written off': 'Unknown'
}

new_df['Aircaft_Damage_Type'] = (
    new_df['Aircaft_Damage_Type']
    .map(damage_map)
    .fillna('Unknown')
)

new_df['Aircaft_Damage_Type'].unique()

In [ ]:
new_df['Aircaft_Nature'].unique()

In [ ]:
nature_map = {
    'Passenger': 'Passenger',
    'Passenger - Scheduled': 'Passenger',
    'Passenger - Non-Scheduled/charter/Air Taxi': 'Passenger',
    'Executive': 'Passenger',

    'Cargo': 'Cargo',

    'Private': 'Private',

    'Military': 'Military',

    'Training': 'Training/Test',
    'Test': 'Training/Test',
    'Calibration/Inspection': 'Training/Test',
    'Demo/Airshow/Display': 'Training/Test',

    'Parachuting': 'Special Operations',
    'Agricultural': 'Special Operations',
    'Fire fighting': 'Special Operations',
    'External load operation': 'Special Operations',
    'Aerial patrol': 'Special Operations',
    'Survey': 'Special Operations',
    'SF': 'Special Operations',   # likely "special flight"
    'Ambulance': 'Special Operations',

    'Ferry/positioning': 'Ferry/Positioning',

    'Illegal Flight': 'Illegal/Unauthorized',

    '-': 'Unknown',
    'Unknown': 'Unknown',
    np.nan: 'Unknown'
}

new_df['Aircaft_Nature'] = new_df['Aircaft_Nature'].fillna('Unknown')
new_df['Aircaft_Nature'] = new_df['Aircaft_Nature'].map(nature_map).fillna('Unknown')

new_df['Aircaft_Nature'].unique()

In [ ]:
new_df

In [ ]:
new_df.columns

In [ ]:
new_df['Incident_Location'].isna().sum()

In [ ]:
new_df['Departure_Airport'].isna().sum()

In [ ]:
df['Departure_Airport'].isna().sum()

In [ ]:
df2['Departure_Airport'].isna().sum()

In [ ]:
new_df.to_csv('new_clean_aircraft_data.csv')

In [ ]:
new_df['Year'].unique()

### Try to map locations

In [ ]:
new_df_copy = new_df.copy()

new_df_copy['Incident_Location'].head(20)

In [ ]:
s = new_df_copy["Incident_Location"]
new_df_copy["Incident_Location"] = (
    s.astype(str)
     .str.encode("latin1", errors="ignore")
     .str.decode("utf-8", errors="ignore")
)

new_df_copy[["raw_place", "country"]] = (
    new_df_copy["Incident_Location"]
      .str.rsplit(" -", n=1, expand=True)
)

new_df_copy["raw_place"] = new_df_copy["raw_place"].str.strip()
new_df_copy["country"]   = new_df_copy["country"].str.strip()

In [ ]:
import re

def build_geopy_query(row):
    place_raw = row.get("Incident_Location", np.nan)
    country   = row.get("country", np.nan)

    # ---------- clean_place logic ----------
    if not isinstance(place_raw, str):
        place = ""
    else:
        s = place_raw.strip()

        # keep part after " of "
        if " of " in s:
            s = s.split(" of ")[-1]

        # remove leading near/over/etc.
        s = re.sub(r"^(near|over|off|approx\.?|around)\s+", "", s, flags=re.I)

        # drop leading distance expressions like "5 km off "
        s = re.sub(
            r"^[0-9.,]+\s*(km|nm|mi|miles)?\s*(N|S|E|W|NE|NW|SE|SW)?\s*",
            "",
            s,
            flags=re.I,
        )

        # remove airport codes in parentheses: (YUL)
        s = re.sub(r"\([^)]*\)", "", s)

        # collapse spaces and trim punctuation
        s = re.sub(r"\s+", " ", s)
        place = s.strip(" ,;-")

    # ---------- make_query logic ----------
    query = np.nan
    if place:
        if isinstance(country, str) and country and country.lower() != "unknown country":
            query = f"{place}, {country}"
        else:
            query = place
    elif isinstance(country, str) and country and country.lower() != "unknown country":
        query = country

    # ---------- fix_failed_query logic ----------
    if pd.isna(query):
        return np.nan

    s = str(query).strip()
    if not s:
        return np.nan

    s_lower = s.lower()

    # remove leading "from "
    if s_lower.startswith("from "):
        s = s[5:].strip()
        s_lower = s.lower()

    # remove leading "off "
    if s_lower.startswith("off "):
        s = s[4:].strip()
        s_lower = s.lower()

    # remove things like "W off", "SE off", etc.
    s = re.sub(r"^[NSEW]{1,2}\s+off\s+", "", s, flags=re.I)

    # remove leading "within "
    if s_lower.startswith("within "):
        s = s[7:].strip()
        s_lower = s.lower()

    # handle "ca 3 km from ..." or "ca 3 km SE off ..."
    s = re.sub(r"^ca\s+[^,]*?\s+(from|off)\s+", "", s, flags=re.I)

    # handle "en route DUS-MUC, Germany" → just country
    s_lower = s.lower()
    if s_lower.startswith("en route "):
        parts = s.split(",")
        if len(parts) > 1:
            s = parts[-1].strip()
        else:
            s = s.replace("en route", "").strip()

    # final cleanup
    s = re.sub(r"\s+", " ", s)
    s = s.strip(" ,;-")

    return s if s else np.nan

# apply to your dataframe
new_df_copy["geopy_query"] = new_df_copy.apply(build_geopy_query, axis=1)

In [ ]:
! pip install geopy

Requirement already satisfied: geopy in /usr/local/lib/python3.12/dist-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /usr/local/lib/python3.12/dist-packages (from geopy) (2.1)

In [ ]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

geolocator = Nominatim(user_agent="aircraft_incidents_locations")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)  # be nice to the API

In [ ]:
cache = {}

def geocode_cached(query):
    q = str(query).strip() if isinstance(query, str) else None

    # Skip
    if not q:
        status = "SKIPPED"
        print(f"{status} → {query}")
        return pd.Series([np.nan, np.nan, status])

    # Cache hit
    if q in cache:
        lat, lon, status = cache[q]
        print(f"CACHE HIT → {q} → {lat}, {lon}")
        return pd.Series([lat, lon, status])

    # Try geocoding
    try:
        location = geocode(q)
        if location is not None:
            lat, lon = location.latitude, location.longitude
            status = "SUCCESS"
            cache[q] = (lat, lon, status)
            print(f"{status} → {q} → {lat}, {lon}")
            return pd.Series([lat, lon, status])
        else:
            status = "FAILED"
            print(f"{status} → {q}")
    except Exception as e:
        status = f"ERROR"
        print(f"{status} → {q} ({e})")

    cache[q] = (np.nan, np.nan, status)
    return pd.Series([np.nan, np.nan, status])


new_df_copy[["Latitude", "Longitude", "GeoStatus"]] = new_df_copy["geopy_query"].apply(geocode_cached)

In [ ]:
new_df_copy.head()

# we try to solve the lat long problem

In [ ]:
failed_df = new_df_copy[new_df_copy["GeoStatus"] == "FAILED"]
success_df = new_df_copy[new_df_copy["GeoStatus"] == "SUCCESS"]
skipped_df = new_df_copy[new_df_copy["GeoStatus"] == "SKIPPED"]
error_df = new_df_copy[new_df_copy["GeoStatus"] == "ERROR"]

print(len(failed_df))
print(len(success_df))
print(len(skipped_df))
print(len(error_df))

# we have almost 2000 failed queries - problem for later

1957
3321
0
0

In [ ]:
# new_df_copy.to_csv('new_clean_aircraft_data_with_lat_lon_incident_with_failures.csv')

# trying to handle the coordinate failure problem

failed_queries = (
    failed_df["geopy_query"]
    .dropna()
    .drop_duplicates()
    .sort_values()
)

failed_queries.to_csv("failed_geopy_queries.txt", index=False, header=False)

In [ ]:
new_df_copy.head()

In [ ]:
from google.colab import files
uploaded = files.upload()

import pandas as pd

correction_file = list(uploaded.keys())[0]   # get the only uploaded file name

import json

with open(correction_file, "r", encoding="utf-8") as f:
    correction_map = json.load(f)

mask = (new_df_copy["GeoStatus"] == "FAILED")
new_df_copy.loc[mask, "geopy_query"] = (
    new_df_copy.loc[mask, "geopy_query"].map(correction_map).fillna(new_df_copy.loc[mask, "geopy_query"])
)

Saving geopy_corrections.json to geopy_corrections (2).json

In [ ]:
to_retry = new_df_copy["GeoStatus"] == "FAILED"

result = new_df_copy.loc[to_retry, "geopy_query"].apply(geocode_cached)

# assign by position, not by column labels
new_df_copy.loc[to_retry, ["Latitude", "Longitude", "GeoStatus"]] = result.values

CACHE HIT → Nnamdi Azikiwe International Airport, Nigeria → 9.0207137, 7.2677714
SUCCESS → José Joaquín de Olmedo International Airport, Guayaquil, Ecuador → -2.1579327, -79.8833013
CACHE HIT → Félix-Houphouët-Boigny International Airport, Côte d'Ivoire → 5.2649283, -3.9259573
FAILED → Filitheyo Island Seaplane Base, Maldives
CACHE HIT → Aeroparque Jorge Newbery, Buenos Aires, Argentina → -34.5594554, -58.4143637
SUCCESS → Quatro de Fevereiro Airport, Luanda, Angola → -8.861408, 13.2287561
FAILED → Sacramento Mather Airport, California, United States of America

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=El+Tornillo+area+airstrip%2C+Colombia&format=json&limit=1

FAILED → El Tornillo area airstrip, Colombia
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Salgado+Filho+International+Airport%2C+Porto+Alegre%2C+Rio+Grande+do+Sul%2C+Brazil&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Salgado+Filho+International+Airport%2C+Porto+Alegre%2C+Rio+Grande+do+Sul%2C+Brazil&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Salgado Filho International Airport, Porto Alegre, Rio Grande do Sul, Brazil',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Salgado+Filho+International+Airport%2C+Porto+Alegre%2C+Rio+Grande+do+Sul%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Salgado+Filho+International+Airport%2C+Porto+Alegre%2C+Rio+Grande+do+Sul%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Salgado+Filho+International+Airport%2C+Porto+Alegre%2C+Rio+Grande+do+Sul%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

SUCCESS → Salgado Filho International Airport, Porto Alegre, Rio Grande do Sul, Brazil → -29.9952684, -51.1663978
SUCCESS → Barnstable Municipal Airport, Hyannis, Massachusetts, United States of America → 41.6707658, -70.2843904
FAILED → London Heathrow Airport (Terminal 2, Stand F8), United Kingdom
SUCCESS → Goma International Airport, Goma, Democratic Republic of the Congo → -1.6648635, 29.2381116
FAILED → Montréal–Pierre Elliott Trudeau International Airport, Quebec, Canada
CACHE HIT → Berlin Brandenburg Airport, Germany → 52.3659284, 13.4886435
CACHE HIT → Ingeniero Ambrosio Taravella International Airport, Córdoba, Argentina → nan, nan
CACHE HIT → José Joaquín de Olmedo International Airport, Guayaquil, Ecuador → -2.1579327, -79.8833013
FAILED → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
FAILED → Tomuzlovskoye, Budyonnovsk District, Stavropol Krai, Russia
CACHE HIT → Francisco Bangoy International Airport, Davao City, Philippines → 7.1248797, 125.6434576
SUCCESS → Pepa, Democratic Republic of the Congo → -7.0770001, 29.724444
SUCCESS → Siirt Airport, Turkey → 37.9760297, 41.8311362
FAILED → Houghton County Memorial Airport, Hancock, Michigan, United States of America
CACHE HIT → Tomás de Heres Airport, Ciudad Bolívar, Venezuela → 8.1222138, -63.5361516
CACHE HIT → Kurupung Airport, Guyana → nan, nan
SUCCESS → Islas Malvinas International Airport, Rosario, Argentina → -32.9013031, -60.7783281
SUCCESS → North Pole → 64.750997, -147.349319
FAILED → Chiang Kai-shek International Airport (now Taiwan Taoyuan International Airport), Taiwan
SUCCESS → San Diego, California, United States of America → 32.7174202, -117.162772
FAILED → King County International Airport (Boeing Field), Seattle, Washington, United States of America
FAILED → Charles de Gaulle Airport, Paris, France
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
FAILED → Lima 25 Airstrip, South Sudan
SUCCESS → Harry Reid International Airport, Las Vegas, Nevada, United States of America → 36.0861034, -115.1611002
CACHE HIT → United Kingdom (between Luxembourg and Manston) → nan, nan
SUCCESS → Kamituga Airport, Democratic Republic of the Congo → -3.0456305, 28.1679549
SUCCESS → Lihue Airport, Kauai, Hawaii, United States of America → 21.9722488, -159.3500201
CACHE HIT → Privolzhsky Air Base, Astrakhan Oblast, Russia → nan, nan
SUCCESS → Khartoum International Airport, Sudan → 15.5902124, 32.5550536
CACHE HIT → El Dorado International Airport, Bogotá, Colombia → 4.7020946, -74.1477132
FAILED → Yellowknife Water Aerodrome, Northwest Territories, Canada
CACHE HIT → Coventry Airport, Baginton, United Kingdom → 52.3700591, -1.4812023
CACHE HIT → Queen Alia International Airport, Amman, Jordan → 31.7238024, 36.007237
CACHE HIT → Chulám de Juárez, Mexico → nan, nan
FAILED → La Vanguardia Airport, Villavicencio, Colombia
FAILED → Mount Pelion, Magnesia, Greece
FAILED → King Hussein Air Base, Mafraq, Jordan
SUCCESS → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → Jarayakhali Hill, Nepal → nan, nan
CACHE HIT → Montréal–Pierre Elliott Trudeau International Airport, Quebec, Canada → nan, nan
FAILED → Kullu–Manali Airport (Bhuntar Airport), India
SUCCESS → Hong Kong International Airport (Chek Lap Kok), Hong Kong → 22.3125986, 113.9172999
FAILED → North Yeniseysky District, Krasnoyarsk Krai, Russia
FAILED → Stevens and Nicklin Lakes area, Manitoba, Canada
SUCCESS → Michinmahuida Volcano, Chile → -42.799511, -72.4446906
SUCCESS → Tshikapa, Democratic Republic of the Congo → -6.6399269, 20.5405413
CACHE HIT → Ministro Pistarini International Airport, Buenos Aires, Argentina → -34.8168141, -58.5474234
SUCCESS → Gogebic-Iron County Airport, Ironwood, Michigan, United States of America → 46.5274978, -90.1340891
SUCCESS → Kisangani Airport, Democratic Republic of the Congo → 0.4827092, 25.3368223
CACHE HIT → Heydar Aliyev International Airport, Baku, Azerbaijan → 40.472815, 50.0491469
SUCCESS → Mexico → 23.6585116, -102.0077097
CACHE HIT → Islas Malvinas International Airport, Rosario, Argentina → -32.9013031, -60.7783281
SUCCESS → Eduardo Falla Solano Airport, San Vicente del Caguán, Colombia → 2.1523968, -74.7666063
FAILED → Coaselsa Airstrip, San Pablo, Ecuador
SUCCESS → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
CACHE HIT → Cuba → 23.0131338, -80.8328748
SUCCESS → Tan Son Nhat International Airport, Ho Chi Minh City, Vietnam → 10.8179793, 106.6562645
CACHE HIT → Hartsfield–Jackson Atlanta International Airport, Georgia, United States of America → 33.6374009, -84.4298161

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Diori+Hamani+International+Airport%2C+Niamey%2C+Niger&format=json&limit=1

SUCCESS → Diori Hamani International Airport, Niamey, Niger → 13.4901663, 2.1846007

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Missoula+Montana+Airport+%28Johnson-Bell+Field%29%2C+Montana%2C+United+States+of+America&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Missoula+Montana+Airport+%28Johnson-Bell+Field%29%2C+Montana%2C+United+States+of+America&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Missoula Montana Airport (Johnson-Bell Field), Montana, United States of America',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Missoula+Montana+Airport+%28Johnson-Bell+Field%29%2C+Montana%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Missoula+Montana+Airport+%28Johnson-Bell+Field%29%2C+Montana%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Missoula+Montana+Airport+%28Johnson-Bell+Field%29%2C+Montana%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

FAILED → Missoula Montana Airport (Johnson-Bell Field), Montana, United States of America
CACHE HIT → Diana Lake, Quebec, Canada → nan, nan
CACHE HIT → King Shaka International Airport, Durban, South Africa → nan, nan
SUCCESS → La Grande-4 Airport, Quebec, Canada → 53.7543558, -73.6767181
CACHE HIT → Queen Alia International Airport, Amman, Jordan → 31.7238024, 36.007237
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401
SUCCESS → Indian Ocean → -9.9999999, 69.9999999
FAILED → Burevestnik Airport, Kuril Islands, Russia
SUCCESS → General Lucio Blanco International Airport, Reynosa, Mexico → 26.0057765, -98.2241939
SUCCESS → London Gatwick Airport, United Kingdom → 51.1540772, -0.1823226
CACHE HIT → El Dorado International Airport, Bogotá, Colombia → 4.7020946, -74.1477132
CACHE HIT → Buchanan Field Airport, Concord, California, United States of America → 37.9893485, -122.055954
SUCCESS → Seletar Airport, Singapore → 1.4170202, 103.8680818
SUCCESS → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → Batumi International Airport, Georgia → 41.6093233, 41.6011929
FAILED → Jedo Village, Delta State, Nigeria
SUCCESS → Guam → 13.4499943, 144.7651677
CACHE HIT → Chiang Kai-shek International Airport (now Taiwan Taoyuan International Airport), Taiwan → nan, nan
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
SUCCESS → Luebo Airport, Democratic Republic of the Congo → -5.3496868, 21.4230319
SUCCESS → Fort Wayne International Airport, Indiana, United States of America → 40.9798288, -85.1879116
SUCCESS → Ovda Airbase, Israel → 29.9391304, 34.9384889
CACHE HIT → Quatro de Fevereiro Airport, Luanda, Angola → -8.861408, 13.2287561
CACHE HIT → Asheville, North Carolina, United States of America → 35.595363, -82.5508407
CACHE HIT → Hartsfield–Jackson Atlanta International Airport, Georgia, United States of America → 33.6374009, -84.4298161
CACHE HIT → Tres Esquinas Air Base, Colombia → nan, nan
CACHE HIT → Yeager Airport, Charleston, West Virginia, United States of America → 38.3729476, -81.5942197
SUCCESS → Rangeley Lake Airport, Maine, United States of America → 44.9531109, -70.6625684

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Fa%27a%27%C4%81+International+Airport%2C+Papeete%2C+French+Polynesia&format=json&limit=1

FAILED → Fa'a'ā International Airport, Papeete, French Polynesia
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
SUCCESS → Jomo Kenyatta International Airport, Nairobi, Kenya → -1.3169486, 36.9288569
FAILED → Zhengzhou Air Base, China
CACHE HIT → Ministro Pistarini International Airport, Buenos Aires, Argentina → -34.8168141, -58.5474234
SUCCESS → Meacham International Airport, Fort Worth, Texas, United States of America → 32.8307121, -97.3595581
SUCCESS → Kayseri, Turkey → 38.7219011, 35.4873214
SUCCESS → Sanderson Field Airport, Sault Ste. Marie, Michigan, United States of America → 46.478617, -84.3670113
CACHE HIT → Donlin Creek Airstrip, Alaska, United States of America → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=El+Alcarav%C3%A1n+Airport%2C+Yopal%2C+Colombia&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=El+Alcarav%C3%A1n+Airport%2C+Yopal%2C+Colombia&format=json&limit=1

SUCCESS → El Alcaraván Airport, Yopal, Colombia → 5.3201424, -72.3844781
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Sheffield+City+Airport%2C+Sheffield%2C+United+Kingdom&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Sheffield+City+Airport%2C+Sheffield%2C+United+Kingdom&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Sheffield City Airport, Sheffield, United Kingdom',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Sheffield+City+Airport%2C+Sheffield%2C+United+Kingdom&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Sheffield+City+Airport%2C+Sheffield%2C+United+Kingdom&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Sheffield+City+Airport%2C+Sheffield%2C+United+Kingdom&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Sheffield+City+Airport%2C+Sheffield%2C+United+Kingdom&format=json&limit=1

FAILED → Sheffield City Airport, Sheffield, United Kingdom
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
FAILED → Pondok Cabe Airport, Jakarta, Indonesia
CACHE HIT → Sir Ahmadu Bello International Airport, Birnin Kebbi, Nigeria → 12.4798263, 4.3692074
SUCCESS → Budiarto Airport, Tangerang, Indonesia → -6.2888119, 106.5686964
CACHE HIT → Tempelhof Airport (closed), Berlin, Germany → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Prince+Mohammad+bin+Abdulaziz+International+Airport%2C+Medina%2C+Saudi+Arabia&format=json&limit=1

SUCCESS → Prince Mohammad bin Abdulaziz International Airport, Medina, Saudi Arabia → 24.5554858, 39.7060859

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Roberts+International+Airport%2C+Monrovia%2C+Liberia&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Roberts+International+Airport%2C+Monrovia%2C+Liberia&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Roberts International Airport, Monrovia, Liberia',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Roberts+International+Airport%2C+Monrovia%2C+Liberia&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Roberts+International+Airport%2C+Monrovia%2C+Liberia&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Roberts+International+Airport%2C+Monrovia%2C+Liberia&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

FAILED → Roberts International Airport, Monrovia, Liberia
SUCCESS → Saint Barthélemy → 17.8967693, -62.825598
SUCCESS → Juanda International Airport, Surabaya, Indonesia → -7.3747119, 112.7946133
CACHE HIT → Aspen Airport, Colorado, United States of America → 39.2214209, -106.8673412
SUCCESS → Grand Bahama International Airport, Freeport, Bahamas → 26.5565128, -78.6955864
CACHE HIT → Bishop Airport, Decatur, Texas, United States of America → nan, nan
SUCCESS → Malanje Airport, Angola → -9.5250862, 16.3151737
FAILED → Luis Muñoz Marín International Airport, San Juan, Puerto Rico
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401
SUCCESS → Tembo, Democratic Republic of the Congo → -7.6809087, 17.3326496
FAILED → Flugebyn Airfield, Karlsborg, Sweden
FAILED → Cristiano Ronaldo International Airport, Funchal, Madeira, Portugal
FAILED → Kobyay Airstrip, Sakha Republic (Yakutia), Russia
CACHE HIT → Stanitsa Nekrasovskaya, Russia → nan, nan
CACHE HIT → Amsterdam Airport Schiphol, Netherlands → 52.3269801, 4.7415053
SUCCESS → O. R. Tambo International Airport, Johannesburg, South Africa → -26.1350013, 28.2270057
SUCCESS → Malatya, Turkey → 38.3487153, 38.3190674
FAILED → El Plumerillo International Airport (Governor Francisco Gabrielli), Mendoza, Argentina
CACHE HIT → Etimesgut Air Base, Ankara, Turkey → 39.9517942, 32.6894144
FAILED → Fly Inn Estate Airfield, South Africa
FAILED → Myakotino, Zubtsovsky District, Tver Oblast, Russia
SUCCESS → Metallurg, Volgograd Oblast, Russia → 48.7948916, 44.5206385

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Jersey+Airport%2C+Channel+Islands&format=json&limit=1

FAILED → Jersey Airport, Channel Islands
FAILED → Ben Gurion International Airport, Tel Aviv, Israel
SUCCESS → Fort Lauderdale, Florida, United States of America → 26.1223084, -80.1433786
SUCCESS → Space Coast Regional Airport, Titusville, Florida, United States of America → 28.5142066, -80.7990149
SUCCESS → Zenino, Veydelevsky District, Belgorod Oblast, Russia → 50.173595, 38.293476
SUCCESS → Bartolomé Salom Airport, Puerto Cabello, Venezuela → 10.478892, -68.0724625
FAILED → Havre-Saint-Pierre Water Aerodrome, Quebec, Canada
SUCCESS → Sitidgi Lake, Northwest Territories, Canada → 68.5402109, -132.6804956
SUCCESS → Ronald Reagan Washington National Airport, Virginia, United States of America → 38.8512895, -77.0396889
CACHE HIT → Scott Air Force Base, Illinois, United States of America → 38.543839, -89.8527741
SUCCESS → Kaolin Field Airport, Sandersville, Georgia, United States of America → 32.9661543, -82.83675
SUCCESS → Fazenda Conforto Airport, Itaituba, Pará, Brazil → -7.3898556, -56.5205093
SUCCESS → Kuujjuaq Airport (Fort Chimo), Quebec, Canada → 58.0906856, -68.4273935
SUCCESS → Mugogo, Democratic Republic of the Congo → -2.5816667, 28.7552778
SUCCESS → Ithaca Tompkins International Airport, New York, United States of America → 42.4909458, -76.4620696
FAILED → Lajes Air Base, Terceira Island, Azores, Portugal
SUCCESS → Málaga-Costa del Sol Airport, Spain → 36.6785446, -4.4999552
FAILED → Naples International Airport (Capodichino), Italy
SUCCESS → Piarco International Airport, Trinidad and Tobago → 10.5961258, -61.3361649
SUCCESS → Lubumbashi International Airport, Democratic Republic of the Congo → -11.5926492, 27.5259188

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Goose+Water+Aerodrome%2C+Newfoundland+and+Labrador%2C+Canada&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Goose+Water+Aerodrome%2C+Newfoundland+and+Labrador%2C+Canada&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Goose Water Aerodrome, Newfoundland and Labrador, Canada',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Goose+Water+Aerodrome%2C+Newfoundland+and+Labrador%2C+Canada&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Goose+Water+Aerodrome%2C+Newfoundland+and+Labrador%2C+Canada&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Goose+Water+Aerodrome%2C+Newfoundland+and+Labrador%2C+Canada&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

FAILED → Goose Water Aerodrome, Newfoundland and Labrador, Canada
SUCCESS → La Aurora International Airport, Guatemala City, Guatemala → 14.5831769, -90.5271896
CACHE HIT → Kuujjuaq Airport (Fort Chimo), Quebec, Canada → 58.0906856, -68.4273935
FAILED → Plácido de Castro International Airport, Rio Branco, Acre, Brazil
SUCCESS → Manchester Airport, United Kingdom → 53.3503421, -2.2803693
CACHE HIT → Alpine Airstrip, Deadhorse, Alaska, United States of America → nan, nan
CACHE HIT → Borkum Airfield, Lower Saxony, Germany → nan, nan
CACHE HIT → Adler, Sochi, Krasnodar Krai, Russia → 43.4253834, 39.9237036
SUCCESS → Polyarny, Yakutia, Russia → 66.4005807, 112.0328741
CACHE HIT → EuroAirport Basel–Mulhouse–Freiburg, France–Switzerland → nan, nan
CACHE HIT → Columbretes Islands, Castellón, Spain → nan, nan
CACHE HIT → Dillingham Airport, Alaska, United States of America → 59.0433568, -158.5112028
CACHE HIT → Comandante Espora Airport, Bahía Blanca, Argentina → -38.7272941, -62.1714145
FAILED → Munich Airport (Franz Josef Strauß), Germany
SUCCESS → Grand Glaize-Osage Beach Airport, Missouri, United States of America → 38.109994, -92.6800701
CACHE HIT → General Pedro J. Méndez International Airport, Ciudad Victoria, Mexico → 23.6999115, -98.9542838
CACHE HIT → Jomo Kenyatta International Airport, Nairobi, Kenya → -1.3169486, 36.9288569
FAILED → Mike Zubko Airport, Inuvik, Northwest Territories, Canada
SUCCESS → Taiwan Taoyuan International Airport, Taiwan → 25.0793175, 121.2345977
CACHE HIT → Chiang Kai-shek International Airport (now Taiwan Taoyuan International Airport), Taiwan → nan, nan
CACHE HIT → Buriti Alegre, Goiás, Brazil → -18.1377879, -49.0404411
CACHE HIT → Pratica di Mare Air Base, Italy → nan, nan
CACHE HIT → Comandante Espora Airport, Bahía Blanca, Argentina → -38.7272941, -62.1714145
SUCCESS → Geti, Democratic Republic of the Congo → 1.2092449, 30.1743285
CACHE HIT → Tancredo Neves International Airport, Belo Horizonte, Brazil → -19.6367633, -43.9621429
FAILED → Long Bawan Airport, North Kalimantan, Indonesia
FAILED → Malikussaleh Airport, Lhokseumawe, Indonesia
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401
CACHE HIT → Bremerhaven Airport, Germany → nan, nan
CACHE HIT → Ted Stevens Anchorage International Airport, Alaska, United States of America → 61.1810353, -149.9978919
FAILED → Piloto Civil Norberto Fernández International Airport, Río Gallegos, Argentina
SUCCESS → Pulkovo Airport, Saint Petersburg, Russia → 59.8016986, 30.2676011
SUCCESS → Sultan Syarif Kasim II International Airport, Pekanbaru, Indonesia → 0.457566, 101.4401532
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
FAILED → Ellsworth Air Force Base, Rapid City, South Dakota, United States of America
CACHE HIT → Harrell Field Airport, Camden, Arkansas, United States of America → nan, nan
FAILED → Marin County Airport (Gnoss Field), Novato, California, United States of America
SUCCESS → Biggs Army Airfield, El Paso, Texas, United States of America → 31.8481662, -106.3829653
CACHE HIT → Cuyahoga County Airport, Richmond Heights, Ohio, United States of America → nan, nan
CACHE HIT → Sarab-e Do Rah, Iran → nan, nan
SUCCESS → Hindu Kush, Afghanistan → 36.8936766, 73.2678437
SUCCESS → Ralph Wien Memorial Airport, Kotzebue, Alaska, United States of America → 66.8836843, -162.6107466
CACHE HIT → Sarsura Glacier, near Zernez, Switzerland → nan, nan
SUCCESS → Palm Beach International Airport, Florida, United States of America → 26.6859478, -80.0924865
CACHE HIT → Sam Neua Airport, Laos → nan, nan
CACHE HIT → Roberts International Airport, Monrovia, Liberia → nan, nan
SUCCESS → Mbuji-Mayi, Democratic Republic of the Congo → -6.1258942, 23.5998111
FAILED → Lakhta Air Base, Arkhangelsk, Russia
FAILED → Changi International Airport, Singapore
SUCCESS → Parkes, New South Wales, Australia → -32.8225409, 147.9761363
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → Tancredo Neves International Airport, Belo Horizonte, Brazil → -19.6367633, -43.9621429

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=International+waters&format=json&limit=1

SUCCESS → International waters → -6.1817263, 106.8159505
CACHE HIT → Nnamdi Azikiwe International Airport, Nigeria → 9.0207137, 7.2677714
CACHE HIT → Nnamdi Azikiwe International Airport, Nigeria → 9.0207137, 7.2677714
FAILED → Isle of Man Airport (Ronaldsway), Isle of Man
SUCCESS → Maimun Saleh Airport, Sabang, Indonesia → 5.875035, 95.3391283
SUCCESS → RAF Weston-on-the-Green, Oxfordshire, United Kingdom → 51.8785683, -1.2191338
FAILED → Pilanesberg International Airport (Sun City), South Africa
CACHE HIT → Mara Ngerende Airstrip, Kenya → nan, nan
SUCCESS → Kostandenets, Bulgaria → 43.57034, 26.19448
SUCCESS → Guillermo León Valencia Airport, Popayán, Colombia → 2.4547051, -76.6087509

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=San+Juan%2C+Puerto+Rico&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=San+Juan%2C+Puerto+Rico&format=json&limit=1

SUCCESS → San Juan, Puerto Rico → 18.465299, -66.116666
SUCCESS → Lake in the Hills, Illinois, United States of America → 42.1816908, -88.3303618
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
FAILED → El Salvador International Airport (Comalapa), San Salvador, El Salvador
SUCCESS → Pacific Ocean → -0.703107, -120.9375
SUCCESS → Aminu Kano International Airport, Kano, Nigeria → 12.0468517, 8.5213229
CACHE HIT → Burke Lakefront Airport, Cleveland, Ohio, United States of America → 41.5188169, -81.6811324
CACHE HIT → Mexico → 23.6585116, -102.0077097
CACHE HIT → Mexico → 23.6585116, -102.0077097
SUCCESS → Central Nebraska Regional Airport, Grand Island, Nebraska, United States of America → 40.9705149, -98.3075367
CACHE HIT → Central Nebraska Regional Airport, Grand Island, Nebraska, United States of America → 40.9705149, -98.3075367
SUCCESS → Wiley Post Airport, Oklahoma City, Oklahoma, United States of America → 35.5332202, -97.6455261
SUCCESS → Penghu Islands, Taiwan → 23.5585685, 119.6098859
SUCCESS → Mendoza, Argentina → -34.5970325, -68.7304797
CACHE HIT → Hartsfield–Jackson Atlanta International Airport, Georgia, United States of America → 33.6374009, -84.4298161
CACHE HIT → Hartsfield–Jackson Atlanta International Airport, Georgia, United States of America → 33.6374009, -84.4298161
FAILED → Lovozero Airfield, Murmansk Oblast, Russia
CACHE HIT → Montréal–Pierre Elliott Trudeau International Airport, Quebec, Canada → nan, nan
CACHE HIT → Khartoum International Airport, Sudan → 15.5902124, 32.5550536
SUCCESS → Benito Salas Airport, Neiva, Colombia → 2.9527007, -75.293331
CACHE HIT → General Enrique Mosconi International Airport, Comodoro Rivadavia, Argentina → nan, nan
SUCCESS → Antonio Rivera Rodríguez Airport, Vieques, Puerto Rico → 18.1346239, -65.4926079
FAILED → Lac Cojibo, Quebec, Canada
SUCCESS → William P. Hobby Airport, Houston, Texas, United States of America → 29.6471491, -95.2769303
CACHE HIT → Long Bawan Airport, North Kalimantan, Indonesia → nan, nan
CACHE HIT → Yeager Airport, Charleston, West Virginia, United States of America → 38.3729476, -81.5942197
CACHE HIT → Mugumo Coffee Farm, Kenya → nan, nan
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
SUCCESS → Tallahassee International Airport, Florida, United States of America → 30.397826, -84.3590839
SUCCESS → Lviv Danylo Halytskyi International Airport, Lviv, Ukraine → 49.8105751, 23.9574437
FAILED → Pimu Airstrip, Democratic Republic of the Congo
CACHE HIT → Ministro Pistarini International Airport, Buenos Aires, Argentina → -34.8168141, -58.5474234
CACHE HIT → Ministro Pistarini International Airport, Buenos Aires, Argentina → -34.8168141, -58.5474234
FAILED → Sladkiy Liman, Kanev District, Krasnodar Krai, Russia
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
SUCCESS → Vagay, Tyumen Oblast, Russia → 57.9352224, 69.0125864
FAILED → Murungu Airstrip, Muyowasi, Tanzania
SUCCESS → Eduardo Gomes International Airport, Manaus, Amazonas, Brazil → -3.0356561, -60.0459675
SUCCESS → Jinnah International Airport, Karachi, Pakistan → 24.9058248, 67.1614489
FAILED → In flight over Germany
SUCCESS → Blue Grass Airport, Lexington, Kentucky, United States of America → 38.0348043, -84.6049217
SUCCESS → Viracopos Airport, São Paulo, Brazil → -23.0060223, -47.142004
CACHE HIT → Plácido de Castro International Airport, Rio Branco, Acre, Brazil → nan, nan
SUCCESS → Xichang, Liangshan Prefecture, Sichuan, China → 27.8458993, 102.124224
SUCCESS → Ninoy Aquino International Airport, Manila, Philippines → 14.5123016, 121.0218861
FAILED → Seychelles International Airport, Mahé Island, Seychelles
SUCCESS → Inongo Airport, Democratic Republic of the Congo → -1.9471396, 18.2827695
CACHE HIT → Munich Airport (Franz Josef Strauß), Germany → nan, nan
FAILED → Bykovo Airport, Moscow, Russia
CACHE HIT → EuroAirport Basel–Mulhouse–Freiburg, France–Switzerland → nan, nan
FAILED → Hawthorne Municipal Airport (Jack Northrop Field), California, United States of America
CACHE HIT → Ministro Pistarini International Airport, Buenos Aires, Argentina → -34.8168141, -58.5474234
CACHE HIT → Manas International Airport, Bishkek, Kyrgyzstan → nan, nan
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=General+Mariano+Escobedo+International+Airport%2C+Monterrey%2C+Mexico&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=General+Mariano+Escobedo+International+Airport%2C+Monterrey%2C+Mexico&format=json&limit=1

FAILED → General Mariano Escobedo International Airport, Monterrey, Mexico
FAILED → Sligo Airport (Collooney), Ireland
CACHE HIT → John Glenn Columbus International Airport, Columbus, Ohio, United States of America → 39.9970561, -82.8930477

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Enrique+Olaya+Herrera+Airport%2C+Medell%C3%ADn%2C+Colombia&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Enrique+Olaya+Herrera+Airport%2C+Medell%C3%ADn%2C+Colombia&format=json&limit=1

FAILED → Enrique Olaya Herrera Airport, Medellín, Colombia
CACHE HIT → Antalya Airport, Turkey → 36.8999425, 30.7981914
CACHE HIT → Ninoy Aquino International Airport, Manila, Philippines → 14.5123016, 121.0218861

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Istanbul+Atat%C3%BCrk+Airport%2C+Turkey&format=json&limit=1

SUCCESS → Istanbul Atatürk Airport, Turkey → 40.9782389, 28.8263208
CACHE HIT → Ol Kiombo Airstrip, Kenya → nan, nan
SUCCESS → José Martí International Airport, Havana, Cuba → 22.9873849, -82.4142531

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=A.+B.+Won+Pat+International+Airport%2C+Guam&format=json&limit=1

FAILED → A. B. Won Pat International Airport, Guam
CACHE HIT → A. B. Won Pat International Airport, Guam → nan, nan
CACHE HIT → A. B. Won Pat International Airport, Guam → nan, nan
CACHE HIT → King County International Airport (Boeing Field), Seattle, Washington, United States of America → nan, nan
SUCCESS → Chicago Rockford International Airport, Illinois, United States of America → 42.1966203, -89.1018595
FAILED → Magong City, Penghu County, Taiwan
CACHE HIT → Baghrabad, Iran → nan, nan
SUCCESS → Dare County Regional Airport, Manteo, North Carolina, United States of America → 35.9199194, -75.6972044
CACHE HIT → Blue Grass Airport, Lexington, Kentucky, United States of America → 38.0348043, -84.6049217
CACHE HIT → Afonso Pena International Airport, Curitiba, Paraná, Brazil → -25.5328128, -49.1673619
FAILED → Flight route between Bocas del Toro and Panama City, Panama

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Herrera+International+Airport%2C+Santo+Domingo%2C+Dominican+Republic&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Herrera+International+Airport%2C+Santo+Domingo%2C+Dominican+Republic&format=json&limit=1

FAILED → Herrera International Airport, Santo Domingo, Dominican Republic
CACHE HIT → Diyarbakır Airport, Turkey → 37.892325, 40.1992144
SUCCESS → Jalaluddin Airport, Gorontalo, Indonesia → 0.6378751, 122.8443144
FAILED → HERZO intersection (oceanic waypoint)
SUCCESS → Mariscal Sucre International Airport, Quito, Ecuador → -0.127422, -78.3566377
CACHE HIT → John Glenn Columbus International Airport, Columbus, Ohio, United States of America → 39.9970561, -82.8930477
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
CACHE HIT → Aeroparque Jorge Newbery, Buenos Aires, Argentina → -34.5594554, -58.4143637
SUCCESS → Soekarno–Hatta International Airport, Jakarta, Indonesia → -6.1238696, 106.6429036
FAILED → Ducote Airpark, San Angelo, Texas, United States of America
CACHE HIT → Plácido de Castro International Airport, Rio Branco, Acre, Brazil → nan, nan
CACHE HIT → Baucau Airport, East Timor → -8.4854959, 126.3993415
CACHE HIT → Istanbul Atatürk Airport, Turkey → 40.9782389, 28.8263208
CACHE HIT → Brasschaat Air Base, Antwerp Province, Belgium → nan, nan
CACHE HIT → Jinnah International Airport, Karachi, Pakistan → 24.9058248, 67.1614489
SUCCESS → Kerman, Iran → 29.571858, 57.301047
CACHE HIT → RNZAF Base Woodbourne, Blenheim, New Zealand → nan, nan
CACHE HIT → Ralph Wien Memorial Airport, Kotzebue, Alaska, United States of America → 66.8836843, -162.6107466
CACHE HIT → Marine Corps Air Station Cherry Point, North Carolina, United States of America → 34.9151898, -76.8840453
FAILED → Samedan Airport (St. Moritz), Switzerland
FAILED → Obuasi Airport, Ghana
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
FAILED → Oujda Angads Airport, Morocco
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
SUCCESS → Istanbul, Turkey → 41.006381, 28.9758715
CACHE HIT → Taqaddum Air Base, Al Anbar Governorate, Iraq → 33.3322068, 43.6005196
SUCCESS → St. Louis Lambert International Airport, Missouri, United States of America → 38.7496273, -90.3704702
CACHE HIT → DuBois Regional Airport, Pennsylvania, United States of America → 41.1795228, -78.8986431
CACHE HIT → Ted Stevens Anchorage International Airport, Alaska, United States of America → 61.1810353, -149.9978919
CACHE HIT → Maya–Maya Airport, Brazzaville, Republic of the Congo → -4.2510091, 15.2538455
CACHE HIT → Beni Airport, North Kivu, Democratic Republic of the Congo → 0.5094382, 29.4756911
SUCCESS → Gobernador Horacio Guzmán International Airport, Jujuy, Argentina → -24.3934524, -65.0936948
CACHE HIT → Dnipro International Airport, Dnipro, Ukraine → 48.3612473, 35.0966217
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
SUCCESS → Aguas Claras Airport, Ocaña, Colombia → 8.3152699, -73.3574111
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401
CACHE HIT → Bunia Airport, Democratic Republic of the Congo → 1.5666587, 30.2172709
SUCCESS → Kinshasa, Democratic Republic of the Congo → -4.32171, 15.3122511
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
SUCCESS → Democratic Republic of the Congo → -2.9814344, 23.8222636
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
SUCCESS → Maçka, Turkey → 40.8120424, 39.6127153
CACHE HIT → Goma International Airport, Goma, Democratic Republic of the Congo → -1.6648635, 29.2381116
CACHE HIT → In flight over Germany → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Porto+Belo+Farm%2C+Rio+de+Janeiro%2C+Brazil&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Porto+Belo+Farm%2C+Rio+de+Janeiro%2C+Brazil&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Porto Belo Farm, Rio de Janeiro, Brazil',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Porto+Belo+Farm%2C+Rio+de+Janeiro%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Porto+Belo+Farm%2C+Rio+de+Janeiro%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Porto+Belo+Farm%2C+Rio+de+Janeiro%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Porto+Belo+Farm%2C+Rio+de+Janeiro%2C+Brazil&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Porto+Belo+Farm%2C+Rio+de+Janeiro%2C+Brazil&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (1/2 tries). Called with (*('Porto Belo Farm, Rio de Janeiro, Brazil',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Porto+Belo+Farm%2C+Rio+de+Janeiro%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Porto+Belo+Farm%2C+Rio+de+Janeiro%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Porto+Belo+Farm%2C+Rio+de+Janeiro%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Porto+Belo+Farm%2C+Rio+de+Janeiro%2C+Brazil&format=json&limit=1

FAILED → Porto Belo Farm, Rio de Janeiro, Brazil
SUCCESS → Rafael Cabrera Mustelier Airport, Nueva Gerona, Cuba → 21.8332118, -82.7832898
FAILED → Jaffna International Airport (Palaly Airport), Sri Lanka
SUCCESS → Manila, Philippines → 14.5904492, 120.9803621
CACHE HIT → Brest Bretagne Airport, Guipavas, France → 48.4476903, -4.4173698
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401
SUCCESS → Rudshur, Iran → 35.2957445, 50.7553386
CACHE HIT → Ingeniero Ambrosio Taravella International Airport, Córdoba, Argentina → nan, nan
SUCCESS → City of Derry Airport, Northern Ireland, United Kingdom → 55.041887, -7.1613066
CACHE HIT → Montréal–Pierre Elliott Trudeau International Airport, Quebec, Canada → nan, nan
FAILED → Ulu Mine Airstrip, Nunavut, Canada
CACHE HIT → Borg El Arab Airport, Alexandria, Egypt → 30.9332681, 29.697542
CACHE HIT → Soekarno–Hatta International Airport, Jakarta, Indonesia → -6.1238696, 106.6429036
CACHE HIT → Aeroparque Jorge Newbery, Buenos Aires, Argentina → -34.5594554, -58.4143637
FAILED → Camp Humphreys (Desiderio Army Airfield), Pyeongtaek, South Korea
CACHE HIT → Montréal–Pierre Elliott Trudeau International Airport, Quebec, Canada → nan, nan
CACHE HIT → Keesler Air Force Base, Biloxi, Mississippi, United States of America → 30.4094294, -88.918865

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=St.+Augustine+Airport%2C+Florida%2C+United+States+of+America&format=json&limit=1

FAILED → St. Augustine Airport, Florida, United States of America
SUCCESS → London Stansted Airport, United Kingdom → 51.8869652, 0.2441929
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
FAILED → Approx. 1.5 km north of Caniçal, Madeira Island, Portugal
SUCCESS → Lankien, South Sudan → 8.5248787, 32.0618875
SUCCESS → Treasure Coast International Airport, Fort Pierce, Florida, United States of America → 27.4945813, -80.3665069
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
CACHE HIT → Amakinskaya (village), Russia → nan, nan
CACHE HIT → Ministro Pistarini International Airport, Buenos Aires, Argentina → -34.8168141, -58.5474234
CACHE HIT → Las Potrancas Ranch Airstrip, Mexico → nan, nan
CACHE HIT → Yellowstone Regional Airport, Cody, Wyoming, United States of America → 44.520752, -109.0218534
SUCCESS → Kamina Airport, Democratic Republic of the Congo → -8.7288751, 24.9922114
CACHE HIT → Rothera Research Station, Antarctica → nan, nan
CACHE HIT → Quatro de Fevereiro Airport, Luanda, Angola → -8.861408, 13.2287561
CACHE HIT → Ministro Pistarini International Airport, Buenos Aires, Argentina → -34.8168141, -58.5474234
FAILED → Murtala Muhammed International Airport, Lagos, Nigeria
SUCCESS → Felts Field Airport, Spokane, Washington, United States of America → 47.6847157, -117.3173678
CACHE HIT → Boende Airport, Democratic Republic of the Congo → -0.2866489, 20.8802666
CACHE HIT → Aminu Kano International Airport, Kano, Nigeria → 12.0468517, 8.5213229
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Pos+Ubrel%2C+Argentina&format=json&limit=1

FAILED → Pos Ubrel, Argentina
CACHE HIT → Newnan–Coweta County Airport, Georgia, United States of America → 33.3118628, -84.7712355
CACHE HIT → Barangay Dinapigue (Dinapnat), Divilacan, Isabela, Philippines → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Jorge+Ch%C3%A1vez+International+Airport%2C+Lima%2C+Peru&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Jorge+Ch%C3%A1vez+International+Airport%2C+Lima%2C+Peru&format=json&limit=1

SUCCESS → Jorge Chávez International Airport, Lima, Peru → -12.019515, -77.1183731

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Central+Wisconsin+Airport%2C+Wisconsin%2C+United+States+of+America&format=json&limit=1

SUCCESS → Central Wisconsin Airport, Wisconsin, United States of America → 44.7727172, -89.6671649
CACHE HIT → In flight over Germany → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Cyril+E.+King+Airport%2C+Saint+Thomas%2C+U.S.+Virgin+Islands&format=json&limit=1

SUCCESS → Cyril E. King Airport, Saint Thomas, U.S. Virgin Islands → 18.3347691, -64.9724536

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Terrace+Bay+Airport%2C+Ontario%2C+Canada&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Terrace+Bay+Airport%2C+Ontario%2C+Canada&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Terrace Bay Airport, Ontario, Canada',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Terrace+Bay+Airport%2C+Ontario%2C+Canada&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Terrace+Bay+Airport%2C+Ontario%2C+Canada&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Terrace+Bay+Airport%2C+Ontario%2C+Canada&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

FAILED → Terrace Bay Airport, Ontario, Canada
FAILED → Tokunoshima Airport, Kagoshima Prefecture, Japan
CACHE HIT → Munich Airport (Franz Josef Strauß), Germany → nan, nan
CACHE HIT → Léopold Sédar Senghor International Airport, Dakar, Senegal → nan, nan
CACHE HIT → Léopold Sédar Senghor International Airport, Dakar, Senegal → nan, nan
CACHE HIT → Akron–Canton Airport, Ohio, United States of America → 40.9152061, -81.4399242
CACHE HIT → Ministro Pistarini International Airport, Buenos Aires, Argentina → -34.8168141, -58.5474234
SUCCESS → King Abdulaziz International Airport, Jeddah, Saudi Arabia → 21.6585157, 39.1746303
CACHE HIT → José Joaquín de Olmedo International Airport, Guayaquil, Ecuador → -2.1579327, -79.8833013
SUCCESS → Frank País International Airport, Holguín, Cuba → 20.7878278, -76.3207656
SUCCESS → Marine Corps Air Station Miramar, San Diego, California, United States of America → 32.8763782, -117.0824905
FAILED → Oneida County Airport (former), Whitestown, New York, United States of America
SUCCESS → Pavlovsky District, Voronezh Oblast, Russia → 50.5115386, 40.2944645
SUCCESS → Bradley International Airport, Windsor Locks, Connecticut, United States of America → 41.9406881, -72.6849968
SUCCESS → Shabunda, Democratic Republic of the Congo → -2.993575, 27.4702053
FAILED → Puerto Esperanza Airport, Ucayali, Peru
CACHE HIT → Fa'a'ā International Airport, Papeete, French Polynesia → nan, nan
CACHE HIT → El Dorado International Airport, Bogotá, Colombia → 4.7020946, -74.1477132
CACHE HIT → Chimantá Massif, Bolívar State, Venezuela → 5.2796827, -62.1266985
CACHE HIT → Antonio Roldán Betancourt Airport, Carepa, Colombia → 7.8117992, -76.7163594
SUCCESS → Martinique Aimé Césaire International Airport, Fort-de-France, Martinique → 14.590977, -61.0042393
CACHE HIT → Luis Muñoz Marín International Airport, San Juan, Puerto Rico → nan, nan
CACHE HIT → Tatal, Sudan → nan, nan
FAILED → Phinda Airfield, KwaZulu-Natal, South Africa
CACHE HIT → Bozoy, Kazakhstan → nan, nan
SUCCESS → North Las Vegas Airport, Nevada, United States of America → 36.2101116, -115.1960241
CACHE HIT → Loiborsoit Village, Simanjiro District, Tanzania → nan, nan
SUCCESS → Tosca, North West Province, South Africa → -25.8778028, 23.960406
FAILED → Henichesk, Kherson Region, Ukraine
CACHE HIT → Khartoum International Airport, Sudan → 15.5902124, 32.5550536
SUCCESS → Myachkovo Airport, Moscow, Russia → 55.5623317, 37.9855667
FAILED → Waypoint ARESI over the Pacific Ocean
SUCCESS → Green Bay–Austin Straubel International Airport, Wisconsin, United States of America → 44.4784881, -88.1436201
SUCCESS → Argyle International Airport, Saint Vincent and the Grenadines → 13.1604271, -61.1497582
FAILED → Tocumen International Airport, Panama City, Panama
CACHE HIT → Canol Road Mile 222, Northwest Territories, Canada → nan, nan
CACHE HIT → Chamadouro, Santa Comba Dão, Portugal → 40.3523004, -8.1609643
CACHE HIT → Beef Island, British Virgin Islands → 18.4394817, -64.5233511
SUCCESS → Sarasota, Florida, United States of America → 27.3365805, -82.5308545
FAILED → Vance W. Amory International Airport, Nevis, St. Kitts and Nevis
FAILED → Stord Airport, Sørstokken, Norway

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Benito+Ju%C3%A1rez+International+Airport%2C+Mexico+City%2C+Mexico&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Benito+Ju%C3%A1rez+International+Airport%2C+Mexico+City%2C+Mexico&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Benito Juárez International Airport, Mexico City, Mexico',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Benito+Ju%C3%A1rez+International+Airport%2C+Mexico+City%2C+Mexico&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Benito+Ju%C3%A1rez+International+Airport%2C+Mexico+City%2C+Mexico&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Benito+Ju%C3%A1rez+International+Airport%2C+Mexico+City%2C+Mexico&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

SUCCESS → Benito Juárez International Airport, Mexico City, Mexico → 19.4342349, -99.0733121
CACHE HIT → Istanbul Atatürk Airport, Turkey → 40.9782389, 28.8263208
SUCCESS → General Rodolfo Sánchez Taboada International Airport, Mexicali, Mexico → 32.6300016, -115.2448954
CACHE HIT → Beni-Mavivi, Democratic Republic of the Congo → 0.5753739, 29.4780053
SUCCESS → Viru Viru International Airport, Santa Cruz, Bolivia → -17.6470801, -63.134509
SUCCESS → Playa La Ventanilla, Oaxaca, Mexico → 15.6640412, -96.5663347
SUCCESS → Orlando Executive Airport, Florida, United States of America → 28.5461744, -81.3316359
FAILED → Marcos A. Gelabert International Airport, Panama City, Panama
SUCCESS → Goma, Democratic Republic of the Congo → -1.6665685, 29.225652
CACHE HIT → Schwarze Heide Airport, Dinslaken, Germany → nan, nan
CACHE HIT → Buchalki, Russia → nan, nan
CACHE HIT → Khartoum International Airport, Sudan → 15.5902124, 32.5550536
SUCCESS → Hanamaki, Iwate Prefecture, Japan → 39.3884038, 141.1169618
CACHE HIT → Colorado Springs Airport, Colorado, United States of America → 38.8004299, -104.7032771
SUCCESS → Boryspil International Airport, Kyiv, Ukraine → 50.3401779, 30.8915573
FAILED → Gwinner–Roger Melroe Field Airport, North Dakota, United States of America
FAILED → Wilmington Airport (ILG), Delaware, United States of America
CACHE HIT → Aruba, Kingdom of the Netherlands → 12.5013629, -69.9618475
SUCCESS → Osmani International Airport, Sylhet, Bangladesh → 24.963849, 91.8612302
SUCCESS → Kindu, Democratic Republic of the Congo → -2.9493766, 25.9184499
CACHE HIT → Enrique Olaya Herrera Airport, Medellín, Colombia → nan, nan
CACHE HIT → Eduardo Gomes International Airport, Manaus, Amazonas, Brazil → -3.0356561, -60.0459675
SUCCESS → Brown Field Municipal Airport, San Diego, California, United States of America → 32.5727262, -116.9795582
CACHE HIT → La Carlota Airport, Caracas, Venezuela → 10.4845244, -66.8422507
CACHE HIT → Oro Negro Airport, Cabimas, Venezuela → 10.331012, -71.3183443
CACHE HIT → South-Eastern Eswatini, Eswatini → nan, nan
CACHE HIT → William P. Hobby Airport, Houston, Texas, United States of America → 29.6471491, -95.2769303
FAILED → Adi Sumarmo International Airport, Surakarta (Solo City), Indonesia
SUCCESS → Greece → 38.9953683, 21.9877132
CACHE HIT → Aurel Vlaicu International Airport (Băneasa), Bucharest, Romania → 44.5002921, 26.0902283
CACHE HIT → Hartsfield–Jackson Atlanta International Airport, Georgia, United States of America → 33.6374009, -84.4298161
CACHE HIT → Rancho Buena Vista Airport, Texas, United States of America → 26.2534439, -97.301532
SUCCESS → Oshawa Executive Airport, Ontario, Canada → 43.9236324, -78.8958801
FAILED → T. F. Green International Airport, Providence, Rhode Island, United States of America
CACHE HIT → The Eastern Iowa Airport, Cedar Rapids, Iowa, United States of America → nan, nan
CACHE HIT → Qayyarah Airfield West, Iraq → nan, nan
CACHE HIT → Sultan Iskandar Muda International Airport, Banda Aceh, Indonesia → nan, nan
CACHE HIT → Alfonso Bonilla Aragón International Airport, Cali, Colombia → nan, nan
CACHE HIT → Bukalaza, Uganda → nan, nan
CACHE HIT → Marcos A. Gelabert International Airport, Panama City, Panama → nan, nan
FAILED → Dillant–Hopkins Airport, Keene, New Hampshire, United States of America
SUCCESS → Kongolo, Democratic Republic of the Congo → -5.3856439, 26.9992427
FAILED → Asturias Airport, Oviedo/Avilés, Spain
CACHE HIT → Rothera Research Station, Antarctica → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Charles+B.+Wheeler+Downtown+Airport%2C+Kansas+City%2C+Missouri%2C+United+States+of+America&format=json&limit=1

SUCCESS → Charles B. Wheeler Downtown Airport, Kansas City, Missouri, United States of America → 39.1241626, -94.5928374
CACHE HIT → Khartoum International Airport, Sudan → 15.5902124, 32.5550536
CACHE HIT → Queen Beatrix International Airport, Aruba → 12.502135, -70.0141264
CACHE HIT → Bromont Airport, Quebec, Canada → nan, nan
FAILED → Teniente Jorge Henrich Arauz Airport, Trinidad, Bolivia
CACHE HIT → Aguachica, Cesar, Colombia → 8.309416, -73.603699
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401
CACHE HIT → Óscar Machado Zuloaga International Airport, Charallave, Venezuela → nan, nan
CACHE HIT → Jorge Chávez International Airport, Lima, Peru → -12.019515, -77.1183731
SUCCESS → Campbeltown Airport (Machrihanish), United Kingdom → 55.4371893, -5.6844698
CACHE HIT → Sakhanka, Russia → nan, nan
FAILED → El Embrujo Airport, Providencia Island, Colombia
CACHE HIT → El Dorado International Airport, Bogotá, Colombia → 4.7020946, -74.1477132
CACHE HIT → El Dorado International Airport, Bogotá, Colombia → 4.7020946, -74.1477132
CACHE HIT → Simón Bolívar International Airport, Caracas, Venezuela → nan, nan
SUCCESS → Japan → 36.5748441, 139.2394179

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Fazenda+Vera+Paz+Airport%2C+Itaituba%2C+Par%C3%A1%2C+Brazil&format=json&limit=1

SUCCESS → Fazenda Vera Paz Airport, Itaituba, Pará, Brazil → -7.3952647, -56.7646835
SUCCESS → Dade-Collier Training and Transition Airport, Florida, United States of America → 25.8631662, -80.898457
SUCCESS → Kampene, Democratic Republic of the Congo → -3.5942806, 26.6683333
FAILED → Al Riyan International Airport, Mukalla, Yemen
CACHE HIT → Rovie, Albania → nan, nan
CACHE HIT → Francisco de Orellana Airport, Coca, Ecuador → -0.4568168, -76.9899886
CACHE HIT → Jorge Chávez International Airport, Lima, Peru → -12.019515, -77.1183731
SUCCESS → Kisangani, Democratic Republic of the Congo → 0.5184021, 25.2057292
CACHE HIT → Kolyadinets, Ukraine → nan, nan
CACHE HIT → Bader Field, Atlantic City, New Jersey, United States of America → 39.3584865, -74.4557093
FAILED → Exuma International Airport, Great Exuma, Bahamas
CACHE HIT → Biega, Democratic Republic of the Congo → -2.4192, 28.6725
FAILED → Toende Aerodrome, Democratic Republic of the Congo
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → Soekarno–Hatta International Airport, Jakarta, Indonesia → -6.1238696, 106.6429036
CACHE HIT → Khartoum International Airport, Sudan → 15.5902124, 32.5550536
CACHE HIT → Ronald Reagan Washington National Airport, Virginia, United States of America → 38.8512895, -77.0396889
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → Manchester Airport, United Kingdom → 53.3503421, -2.2803693
CACHE HIT → Murtala Muhammed International Airport, Lagos, Nigeria → nan, nan
CACHE HIT → Simón Bolívar International Airport, Caracas, Venezuela → nan, nan
FAILED → Kalima Airport, Democratic Republic of the Congo
CACHE HIT → Yellowknife Water Aerodrome, Northwest Territories, Canada → nan, nan
CACHE HIT → Goma International Airport, Goma, Democratic Republic of the Congo → -1.6648635, 29.2381116
CACHE HIT → Murtala Muhammed International Airport, Lagos, Nigeria → nan, nan
CACHE HIT → Shah Amanat International Airport, Chattogram, Bangladesh → 22.2536779, 91.8196817
SUCCESS → Eagle County Regional Airport, Colorado, United States of America → 39.6422569, -106.9172206
CACHE HIT → Malikussaleh Airport, Lhokseumawe, Indonesia → nan, nan
SUCCESS → San Carlos Apache Airport, Globe, Arizona, United States of America → 33.3536143, -110.6693068
CACHE HIT → Hierba Buena, Guatemala → nan, nan
FAILED → Louie Lagoon, Nootka Island, British Columbia, Canada
SUCCESS → Cacique Aramare Airport, Puerto Ayacucho, Venezuela → 5.6205837, -67.6070365

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Naval+Air+Station+Chambers+Field%2C+Norfolk%2C+Virginia%2C+United+States+of+America&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Naval+Air+Station+Chambers+Field%2C+Norfolk%2C+Virginia%2C+United+States+of+America&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Naval Air Station Chambers Field, Norfolk, Virginia, United States of America',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Naval+Air+Station+Chambers+Field%2C+Norfolk%2C+Virginia%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Naval+Air+Station+Chambers+Field%2C+Norfolk%2C+Virginia%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Naval+Air+Station+Chambers+Field%2C+Norfolk%2C+Virginia%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

FAILED → Naval Air Station Chambers Field, Norfolk, Virginia, United States of America
CACHE HIT → A. B. Won Pat International Airport, Guam → nan, nan
CACHE HIT → Soekarno–Hatta International Airport, Jakarta, Indonesia → -6.1238696, 106.6429036
CACHE HIT → Virginia Airport, Durban, South Africa → -29.7707202, 31.057948
FAILED → FAP Captain David Abensur Rengifo International Airport, Pucallpa, Peru
SUCCESS → Isiro, Democratic Republic of the Congo → 2.7742702, 27.6208169
FAILED → Polonia International Airport, Medan, Indonesia
SUCCESS → Murambi, Democratic Republic of the Congo → -1.5349444, 29.023861
CACHE HIT → El Dorado International Airport, Bogotá, Colombia → 4.7020946, -74.1477132
FAILED → Guernsey Airport, Channel Islands
FAILED → May Creek, Yukon, Canada
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → Aru Airport, Democratic Republic of the Congo → 2.8773822, 30.8303474
FAILED → Ogdensburg International Airport, New York, United States of America
FAILED → Labozhskoye, Nenets Autonomous Okrug, Russia
CACHE HIT → Boca Raton Airport, Florida, United States of America → 26.3785634, -80.1084334
CACHE HIT → Boca Raton Airport, Florida, United States of America → 26.3785634, -80.1084334
CACHE HIT → Boca Raton Airport, Florida, United States of America → 26.3785634, -80.1084334
CACHE HIT → Boca Raton Airport, Florida, United States of America → 26.3785634, -80.1084334
SUCCESS → Kindu Airport, Democratic Republic of the Congo → -2.9200784, 25.9154371
SUCCESS → Manchester–Boston Regional Airport, New Hampshire, United States of America → 42.9306656, -71.4388087
CACHE HIT → Khak-e Shahidan, Afghanistan → nan, nan
SUCCESS → John C. Munro Hamilton International Airport, Ontario, Canada → 43.1708488, -79.9275372
FAILED → Privación Airstrip, Belize
FAILED → Ban Lung Airport, Ratanakiri, Cambodia
CACHE HIT → Grobnik Airport, Croatia → nan, nan
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
FAILED → Lasikin Airport, Sinabang, Indonesia
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
SUCCESS → Sabiha Gökçen International Airport, Istanbul, Turkey → 40.8943341, 29.3118058
SUCCESS → Italy → 42.6384261, 12.674297
SUCCESS → Kharkiv International Airport, Kharkiv, Ukraine → 49.9226221, 36.28843
SUCCESS → Fataki, Democratic Republic of the Congo → 1.9880627, 30.5828702
FAILED → Lakeland Airport (Noble F. Lee Memorial Field), Minocqua, Wisconsin, United States of America
CACHE HIT → Sanderson Field Airport, Sault Ste. Marie, Michigan, United States of America → 46.478617, -84.3670113

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Valencia+Airport+%28VLC%29%2C+Spain&format=json&limit=1

SUCCESS → Valencia Airport (VLC), Spain → 39.4878647, -0.4812092
FAILED → Freiburg im Breisgau Airport (EDTF), Germany
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
CACHE HIT → Ted Stevens Anchorage International Airport, Alaska, United States of America → 61.1810353, -149.9978919
SUCCESS → Lanseria International Airport, South Africa → -25.9396667, 27.9261711
SUCCESS → Mbuji-Mayi Airport, Democratic Republic of the Congo → -6.1188177, 23.5682265
CACHE HIT → McClellan–Palomar Airport, Carlsbad, California, United States of America → 33.1275461, -117.2814001
CACHE HIT → Mountain Air Airport, Burnsville, North Carolina, United States of America → nan, nan
SUCCESS → Grand Strand Airport, Myrtle Beach, South Carolina, United States of America → 33.8112835, -78.7233511

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Dodge+County+Airport%2C+Juneau%2C+Wisconsin%2C+United+States+of+America&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Dodge+County+Airport%2C+Juneau%2C+Wisconsin%2C+United+States+of+America&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Dodge County Airport, Juneau, Wisconsin, United States of America',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Dodge+County+Airport%2C+Juneau%2C+Wisconsin%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Dodge+County+Airport%2C+Juneau%2C+Wisconsin%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Dodge+County+Airport%2C+Juneau%2C+Wisconsin%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

FAILED → Dodge County Airport, Juneau, Wisconsin, United States of America
CACHE HIT → Bushin, Iraq → nan, nan
SUCCESS → Venezuela → 8.0018709, -66.1109318
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401
CACHE HIT → Mbuji-Mayi Airport, Democratic Republic of the Congo → -6.1188177, 23.5682265
FAILED → Lubanimanga, Democratic Republic of the Congo
CACHE HIT → Juanda International Airport, Surabaya, Indonesia → -7.3747119, 112.7946133
FAILED → Amílcar Cabral International Airport, Sal Island, Cape Verde
SUCCESS → El Alto International Airport, La Paz, Bolivia → -16.5122206, -68.190261
CACHE HIT → HAL Airport (Hindustan Aeronautics Airport), Bengaluru, India → nan, nan
FAILED → TMA Ezeiza (Buenos Aires FIR), Argentina
SUCCESS → Tallil Air Base, Nasiriyah, Iraq → 30.9302258, 46.0866913
CACHE HIT → Mariscal Lamar International Airport, Cuenca, Ecuador → nan, nan
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
SUCCESS → Domodedovo International Airport, Moscow, Russia → 55.4087122, 37.9094721
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
CACHE HIT → Borg El Arab Airport, Alexandria, Egypt → 30.9332681, 29.697542
CACHE HIT → Bost Airport, Lashkar Gah, Afghanistan → 31.5595609, 64.3679684
CACHE HIT → Amisi Airport, Democratic Republic of the Congo → 1.0305556, 27.1333333
FAILED → Margherita Peak, Rwenzori Mountains, Uganda
CACHE HIT → Harry Reid International Airport, Las Vegas, Nevada, United States of America → 36.0861034, -115.1611002
CACHE HIT → Zwedru Airport, Liberia → nan, nan
CACHE HIT → Soekarno–Hatta International Airport, Jakarta, Indonesia → -6.1238696, 106.6429036
CACHE HIT → HAL Airport (Hindustan Aeronautics Airport), Bengaluru, India → nan, nan
SUCCESS → Mersin, Turkey → 36.7978381, 34.6298391
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401
SUCCESS → São Tomé International Airport, São Tomé and Príncipe → 0.3773992, 6.7148853
FAILED → Exuma International Airport, George Town, Bahamas
CACHE HIT → Bost Airport, Lashkar Gah, Afghanistan → 31.5595609, 64.3679684
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
SUCCESS → Groton–New London Airport, Connecticut, United States of America → 41.3305292, -72.0465062
FAILED → Manassas Regional Airport (Harry P. Davis Field), Virginia, United States of America
FAILED → José María Córdova International Airport, Rionegro/Medellín, Colombia
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
CACHE HIT → Anyang, Gyeonggi Province, South Korea → 37.3938528, 126.9570605
CACHE HIT → Aurel Vlaicu International Airport (Băneasa), Bucharest, Romania → 44.5002921, 26.0902283
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → Peterson Space Force Base, Colorado Springs, Colorado, United States of America → 38.8222878, -104.7004494
SUCCESS → Cable Airport, Upland, California, United States of America → 34.112425, -117.6853958
CACHE HIT → General José Antonio Anzoátegui International Airport, Barcelona, Venezuela → 10.1073096, -64.6899227
SUCCESS → Vilankulo Airport, Mozambique → -22.01664, 35.3126155
CACHE HIT → El Dorado International Airport, Bogotá, Colombia → 4.7020946, -74.1477132
SUCCESS → Hamada, Shimane Prefecture, Japan → 34.8991982, 132.0799984
CACHE HIT → Benito Juárez International Airport, Mexico City, Mexico → 19.4342349, -99.0733121
SUCCESS → Sake, Democratic Republic of the Congo → -1.571281, 29.053624
SUCCESS → Ravalli County Airport, Hamilton, Montana, United States of America → 46.2549402, -114.1257254
SUCCESS → Kristiansund Airport Kvernberget, Norway → 63.1125744, 7.8293798
CACHE HIT → Al Asad Airbase, Al Anbar Governorate, Iraq → 33.7984496, 42.4372455
FAILED → Achmad Yani International Airport, Semarang, Indonesia
CACHE HIT → Ellen Church Field Airport, Cresco, Iowa, United States of America → 43.365442, -92.1331644
CACHE HIT → Cyril E. King Airport, Saint Thomas, U.S. Virgin Islands → 18.3347691, -64.9724536
CACHE HIT → William H. Morse State Airport, Vermont, United States of America → 42.8912104, -73.247606
CACHE HIT → José María Córdova International Airport, Rionegro/Medellín, Colombia → nan, nan
FAILED → Novobratskoye, Bulandy District, Kazakhstan
SUCCESS → Pyongyang Sunan International Airport, North Korea → 39.2295753, 125.6770427
CACHE HIT → El Dorado International Airport, Bogotá, Colombia → 4.7020946, -74.1477132
SUCCESS → East Kansas City Airport, Grain Valley, Missouri, United States of America → 39.0160635, -94.2119905
CACHE HIT → Blue Grass Airport, Lexington, Kentucky, United States of America → 38.0348043, -84.6049217
SUCCESS → Martín Miguel de Güemes International Airport, Salta, Argentina → -24.8595387, -65.4881531
CACHE HIT → Gimhae International Airport, Busan, South Korea → 35.1800774, 128.9364014
CACHE HIT → Luis Muñoz Marín International Airport, San Juan, Puerto Rico → nan, nan
CACHE HIT → Murtala Muhammed International Airport, Lagos, Nigeria → nan, nan
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
CACHE HIT → Nangungu, Tanzania → nan, nan
SUCCESS → Kahuzi-Biega National Park, Democratic Republic of the Congo → -2.1399266, 27.8963289

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Vandeikya%2C+Benue+State%2C+Nigeria&format=json&limit=1

SUCCESS → Vandeikya, Benue State, Nigeria → 6.8334444, 9.0458344
CACHE HIT → Manas International Airport, Bishkek, Kyrgyzstan → nan, nan
CACHE HIT → Manas International Airport, Bishkek, Kyrgyzstan → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Finca+El+Pataxte+Airstrip%2C+Guatemala&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Finca+El+Pataxte+Airstrip%2C+Guatemala&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Finca El Pataxte Airstrip, Guatemala',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Finca+El+Pataxte+Airstrip%2C+Guatemala&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Finca+El+Pataxte+Airstrip%2C+Guatemala&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Finca+El+Pataxte+Airstrip%2C+Guatemala&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Finca+El+Pataxte+Airstrip%2C+Guatemala&format=json&limit=1

FAILED → Finca El Pataxte Airstrip, Guatemala
FAILED → Cachimbo Air Base (Campo de Provas Brigadeiro Velloso), Pará, Brazil
SUCCESS → Kikwit Airport, Democratic Republic of the Congo → -5.0360572, 18.7862858
FAILED → Juwata International Airport, Tarakan, Indonesia

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=St.+Mary%27s+County+Regional+Airport%2C+Leonardtown%2C+Maryland%2C+United+States+of+America&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=St.+Mary%27s+County+Regional+Airport%2C+Leonardtown%2C+Maryland%2C+United+States+of+America&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*("St. Mary's County Regional Airport, Leonardtown, Maryland, United States of America",), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=St.+Mary%27s+County+Regional+Airport%2C+Leonardtown%2C+Maryland%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=St.+Mary%27s+County+Regional+Airport%2C+Leonardtown%2C+Maryland%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=St.+Mary%27s+County+Regional+Airport%2C+Leonardtown%2C+Maryland%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

FAILED → St. Mary's County Regional Airport, Leonardtown, Maryland, United States of America
CACHE HIT → Comandante Espora Airport, Bahía Blanca, Argentina → -38.7272941, -62.1714145
CACHE HIT → Munich Airport (Franz Josef Strauß), Germany → nan, nan
CACHE HIT → Nnamdi Azikiwe International Airport, Nigeria → 9.0207137, 7.2677714
CACHE HIT → Punta Pájaros Airstrip, Mexico → nan, nan
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
SUCCESS → Takhli Air Base, Nakhon Sawan, Thailand → 15.2755634, 100.2938311
SUCCESS → Walikale, Democratic Republic of the Congo → -1.0728008, 27.9753698
SUCCESS → Memphis International Airport, Tennessee, United States of America → 35.0462565, -89.9768947
CACHE HIT → Kamenbe Airport, Bukavu, Democratic Republic of the Congo → nan, nan
CACHE HIT → Ninoy Aquino International Airport, Manila, Philippines → 14.5123016, 121.0218861
CACHE HIT → Ernesto Cortissoz International Airport, Barranquilla, Colombia → nan, nan
FAILED → Alfredo Vásquez Cobo International Airport, Leticia, Colombia
CACHE HIT → Óscar Machado Zuloaga International Airport, Charallave, Venezuela → nan, nan
CACHE HIT → Montréal–Pierre Elliott Trudeau International Airport, Quebec, Canada → nan, nan
CACHE HIT → General Rodolfo Sánchez Taboada International Airport, Mexicali, Mexico → 32.6300016, -115.2448954
FAILED → Novolazarevskaya Station, Antarctica
CACHE HIT → Pratica di Mare Air Base, Italy → nan, nan
CACHE HIT → Ministro Pistarini International Airport, Buenos Aires, Argentina → -34.8168141, -58.5474234
FAILED → Pie de la Cuesta Air Base, Guerrero, Mexico
CACHE HIT → General Mariano Escobedo International Airport, Monterrey, Mexico → nan, nan
SUCCESS → Sultan Hasanuddin International Airport, Makassar, Indonesia → -5.0767232, 119.5510095
SUCCESS → Gari, Sverdlovsk Oblast, Russia → 59.427441, 62.35247
SUCCESS → Václav Havel Airport Prague, Czech Republic → 50.1020451, 14.2705663
CACHE HIT → Carat Lake, Nunavut, Canada → nan, nan
FAILED → Long Layu Airstrip, North Kalimantan, Indonesia
CACHE HIT → Federal de Bachigualato International Airport, Culiacán, Mexico → nan, nan
CACHE HIT → Jomo Kenyatta International Airport, Nairobi, Kenya → -1.3169486, 36.9288569
CACHE HIT → Pambauang, Indonesia → nan, nan
FAILED → North Peace Regional Airport, Fort St. John, British Columbia, Canada
SUCCESS → Miguel Hidalgo y Costilla International Airport, Guadalajara, Mexico → 20.5259, -103.29111
FAILED → Tanjung Bara Airport, Sangatta, Indonesia
SUCCESS → Van Nuys Airport, Los Angeles, California, United States of America → 34.2072085, -118.490148
CACHE HIT → Coventry Airport, Baginton, United Kingdom → 52.3700591, -1.4812023
CACHE HIT → O. R. Tambo International Airport, Johannesburg, South Africa → -26.1350013, 28.2270057
CACHE HIT → Butler County Airport (K. W. Scholter Field), Pennsylvania, United States of America → nan, nan
CACHE HIT → Samedan Airport (St. Moritz), Switzerland → nan, nan
SUCCESS → Pau Pyrénées Airport, France → 43.3791396, -0.4164272
CACHE HIT → Yahurabila, Nicaragua → nan, nan
CACHE HIT → Berbegamau Airport, Quebec, Canada → nan, nan
SUCCESS → Vnukovo International Airport, Moscow, Russia → 55.5995278, 37.2735752
FAILED → Gran Canaria Airport (Gando Air Base), Las Palmas, Spain
CACHE HIT → Walikale, Democratic Republic of the Congo → -1.0728008, 27.9753698
CACHE HIT → Manchester Airport, United Kingdom → 53.3503421, -2.2803693
CACHE HIT → Manchester Airport, United Kingdom → 53.3503421, -2.2803693
CACHE HIT → Juanda International Airport, Surabaya, Indonesia → -7.3747119, 112.7946133
SUCCESS → Arturo Michelena International Airport, Valencia, Venezuela → 10.1516769, -67.9288155
FAILED → Adisutjipto International Airport, Yogyakarta, Indonesia
FAILED → Ostromechevo, Brest Region, Belarus
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
FAILED → Kish International Airport, Kish Island, Iran
CACHE HIT → Beverly Regional Airport, Massachusetts, United States of America → nan, nan
SUCCESS → Glasgow Prestwick Airport, Scotland, United Kingdom → 55.5023054, -4.5775966
CACHE HIT → Istanbul Atatürk Airport, Turkey → 40.9782389, 28.8263208
FAILED → Newport News/Williamsburg International Airport, Virginia, United States of America
CACHE HIT → Tocumen International Airport, Panama City, Panama → nan, nan
CACHE HIT → Khartoum International Airport, Sudan → 15.5902124, 32.5550536
CACHE HIT → Esenboğa Airport, Ankara, Turkey → 40.1230634, 32.9987209
CACHE HIT → Soekarno–Hatta International Airport, Jakarta, Indonesia → -6.1238696, 106.6429036
SUCCESS → Cherry Capital Airport, Traverse City, Michigan, United States of America → 44.7417371, -85.5802553
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
CACHE HIT → Ministro Pistarini International Airport, Buenos Aires, Argentina → -34.8168141, -58.5474234
CACHE HIT → Ravalli County Airport, Hamilton, Montana, United States of America → 46.2549402, -114.1257254
SUCCESS → CFB Trenton, Ontario, Canada → 44.1187558, -77.536849
CACHE HIT → Walikale, Democratic Republic of the Congo → -1.0728008, 27.9753698
CACHE HIT → Billings Logan International Airport, Montana, United States of America → 45.8092348, -108.5476752
CACHE HIT → Acarigua Airport, Portuguesa, Venezuela → nan, nan
CACHE HIT → Polonia International Airport, Medan, Indonesia → nan, nan
CACHE HIT → Woodbourne Airport, Blenheim, New Zealand → nan, nan
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401
SUCCESS → Kamina, Democratic Republic of the Congo → -8.7351826, 25.0032201
CACHE HIT → Karakuzhur, Kyrgyzstan → nan, nan
CACHE HIT → An Naeem Airstrip, Yemen → nan, nan
CACHE HIT → Antalya Airport, Turkey → 36.8999425, 30.7981914
CACHE HIT → Phnom Damrey, Cambodia → nan, nan
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
SUCCESS → Mbanza Congo Airport, Angola → -6.2693545, 14.2472351
CACHE HIT → Dennis F. Cantrell Field Airport, Conway, Arkansas, United States of America → nan, nan
FAILED → Rio de Janeiro–Galeão International Airport, Brazil
CACHE HIT → Federal de Bachigualato International Airport, Culiacán, Mexico → nan, nan
CACHE HIT → Jomo Kenyatta International Airport, Nairobi, Kenya → -1.3169486, 36.9288569
FAILED → Muncho Lake Water Aerodrome (Mile 462), British Columbia, Canada
SUCCESS → Tunica Municipal Airport, Mississippi, United States of America → 34.6853311, -90.3480805
CACHE HIT → Hartsfield–Jackson Atlanta International Airport, Georgia, United States of America → 33.6374009, -84.4298161
SUCCESS → Istanbul Airport, Turkey → 41.2748684, 28.7322749
SUCCESS → Simón Bolívar International Airport, Santa Marta, Colombia → 11.1188921, -74.2311888
CACHE HIT → Bandundu, Democratic Republic of the Congo → -4.4137734, 18.2941215
CACHE HIT → Bandundu Airport, Democratic Republic of the Congo → -3.3113069, 17.3812425
CACHE HIT → St. Augustine Airport, Florida, United States of America → nan, nan
CACHE HIT → Antabare Airstrip, Venezuela → nan, nan
CACHE HIT → Dilesi, Greece → 38.3424485, 23.6718185
SUCCESS → Paloich Airport, South Sudan → 10.5288791, 32.5010003
CACHE HIT → Domodedovo International Airport, Moscow, Russia → 55.4087122, 37.9094721
CACHE HIT → Vnukovo International Airport, Moscow, Russia → 55.5995278, 37.2735752
CACHE HIT → Douglas–Charles Airport, Dominica → 15.5464855, -61.3020804
SUCCESS → Republic Airport, Farmingdale, New York, United States of America → 40.7308166, -73.4173401
CACHE HIT → Gimhae International Airport, Busan, South Korea → 35.1800774, 128.9364014
CACHE HIT → Antalya Airport, Turkey → 36.8999425, 30.7981914
FAILED → Antonio Nariño Airport, Pasto, Colombia
FAILED → Francis S. Gabreski Airport, Westhampton Beach, New York, United States of America
FAILED → Golosón International Airport, La Ceiba, Honduras
SUCCESS → Kongolo Airport, Democratic Republic of the Congo → -5.3932567, 26.9866965
SUCCESS → Fabio Alberto León Bentley Airport, Mitú, Colombia → 1.253429, -70.2340241
SUCCESS → Punia Airport, Democratic Republic of the Congo → -1.3902988, 26.3483146
FAILED → Mystic Lake Lodge Airstrip, Alaska, United States of America
CACHE HIT → Dobo Airport (Rar Gwamar Airport), Aru Islands, Indonesia → nan, nan
FAILED → Juan Santamaría International Airport, San José, Costa Rica
CACHE HIT → Goma International Airport, Goma, Democratic Republic of the Congo → -1.6648635, 29.2381116
CACHE HIT → Miguel Hidalgo y Costilla International Airport, Guadalajara, Mexico → 20.5259, -103.29111
CACHE HIT → DeKalb–Peachtree Airport, Georgia, United States of America → 33.8759268, -84.3028447
CACHE HIT → Mystic Lake Lodge Airstrip, Alaska, United States of America → nan, nan
CACHE HIT → Munich Airport (Franz Josef Strauß), Germany → nan, nan
CACHE HIT → Kamburu Airstrip, Kenya → nan, nan
SUCCESS → Malemba-Nkulu, Democratic Republic of the Congo → -8.0413219, 26.7909208
CACHE HIT → St. Louis Lambert International Airport, Missouri, United States of America → 38.7496273, -90.3704702
CACHE HIT → Kisangani, Democratic Republic of the Congo → 0.5184021, 25.2057292
SUCCESS → Durusu Lake, Turkey → 41.3441346, 28.5755909
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
CACHE HIT → El Dorado International Airport, Bogotá, Colombia → 4.7020946, -74.1477132
CACHE HIT → Istanbul Atatürk Airport, Turkey → 40.9782389, 28.8263208
FAILED → Sydney Kingsford Smith International Airport, New South Wales, Australia
FAILED → New Century AirCenter, Olathe, Kansas, United States of America
FAILED → Los Tomillares Airstrip, Guadalcanal, Spain
SUCCESS → Phnom Penh International Airport, Cambodia → 11.5534919, 104.8442885
SUCCESS → Copenhagen Airport (Kastrup), Denmark → 55.6309113, 12.6492236
SUCCESS → John Wayne Airport, Santa Ana, California, United States of America → 33.6742048, -117.8680243
CACHE HIT → Marcos A. Gelabert International Airport, Panama City, Panama → nan, nan
SUCCESS → Abdul Rachman Saleh Airport, Malang, Indonesia → -7.9303251, 112.7132741
SUCCESS → Campo de Marte Airport, São Paulo, Brazil → -23.5093734, -46.6393378
CACHE HIT → Federal de Bachigualato International Airport, Culiacán, Mexico → nan, nan
CACHE HIT → Khartoum International Airport, Sudan → 15.5902124, 32.5550536
CACHE HIT → Mariscal Sucre International Airport, Quito, Ecuador → -0.127422, -78.3566377
CACHE HIT → Santa Inés, Isletas, Colón, Honduras → nan, nan
SUCCESS → Isparta Süleyman Demirel Airport, Turkey → 37.856023, 30.367304
CACHE HIT → Coeur d'Alene Airport – Pappy Boyington Field, Idaho, United States of America → nan, nan
CACHE HIT → Rickenbacker International Airport, Columbus, Ohio, United States of America → 39.8132172, -82.9341997
FAILED → Lemhi County Airport, Salmon, Idaho, United States of America
CACHE HIT → Vance W. Amory International Airport, Nevis, St. Kitts and Nevis → nan, nan
CACHE HIT → Chania International Airport (Ioannis Daskalogiannis), Crete, Greece → 35.5296433, 24.1480057
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → Golosón International Airport, La Ceiba, Honduras → nan, nan
CACHE HIT → T. F. Green International Airport, Providence, Rhode Island, United States of America → nan, nan
FAILED → Mount Patterson, Antarctica
CACHE HIT → Chub Cay, Bahamas → 25.4165151, -77.8782658
FAILED → Honolulu, Oahu, Hawaii, United States of America
CACHE HIT → Henri Coandă International Airport, Bucharest, Romania → nan, nan
FAILED → Mirosławiec Air Base, Poland
CACHE HIT → Joshua Mqabuko Nkomo International Airport, Bulawayo, Zimbabwe → -20.0133425, 28.6086137
CACHE HIT → El Dorado International Airport, Bogotá, Colombia → 4.7020946, -74.1477132
CACHE HIT → Teniente Jorge Henrich Arauz Airport, Trinidad, Bolivia → nan, nan
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
SUCCESS → Reyes Murillo Airport, Nuquí, Colombia → 5.7113951, -77.2609716
FAILED → El Prado, El Seibo Province, Dominican Republic
CACHE HIT → Ronald Reagan Washington National Airport, Virginia, United States of America → 38.8512895, -77.0396889
CACHE HIT → Ronald Reagan Washington National Airport, Virginia, United States of America → 38.8512895, -77.0396889
FAILED → Alberto Carnevalli Airport, Mérida, Venezuela
FAILED → Peabody Bedard Field Airport, Kayenta, Arizona, United States of America
CACHE HIT → Ninoy Aquino International Airport, Manila, Philippines → 14.5123016, 121.0218861
CACHE HIT → Benito Juárez International Airport, Mexico City, Mexico → 19.4342349, -99.0733121
CACHE HIT → Consuegra, Spain → 39.460918, -3.6070786
SUCCESS → Venice, Italy → 45.4371908, 12.3345898
CACHE HIT → Wiley Post Airport, Oklahoma City, Oklahoma, United States of America → 35.5332202, -97.6455261
SUCCESS → Ain Arnat Airport, Sétif, Algeria → 36.1805412, 5.3253191
CACHE HIT → Bushi Village, Obanliku, Nigeria → nan, nan
FAILED → Maharana Pratap Airport (Dabok), Udaipur, India
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → General Enrique Mosconi International Airport, Comodoro Rivadavia, Argentina → nan, nan
CACHE HIT → Colorado Springs, Colorado, United States of America → 38.8339578, -104.825348
CACHE HIT → Sydney Kingsford Smith International Airport, New South Wales, Australia → nan, nan
CACHE HIT → Goma International Airport, Goma, Democratic Republic of the Congo → -1.6648635, 29.2381116
CACHE HIT → McClellan–Palomar Airport, Carlsbad, California, United States of America → 33.1275461, -117.2814001
SUCCESS → Las Américas International Airport, Santo Domingo, Dominican Republic → 18.4292961, -69.6715124
CACHE HIT → Henri Coandă International Airport, Bucharest, Romania → nan, nan
CACHE HIT → Doro Airstrip, South Sudan → nan, nan
SUCCESS → Marechal Cunha Machado International Airport, São Luís, Brazil → -2.5889911, -44.2394076

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Piedmont+Triad+International+Airport%2C+Greensboro%2C+North+Carolina%2C+United+States+of+America&format=json&limit=1

SUCCESS → Piedmont Triad International Airport, Greensboro, North Carolina, United States of America → 36.1020574, -79.944597
CACHE HIT → Piedmont Triad International Airport, Greensboro, North Carolina, United States of America → 36.1020574, -79.944597
CACHE HIT → Goma International Airport, Goma, Democratic Republic of the Congo → -1.6648635, 29.2381116

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Toncont%C3%ADn+International+Airport%2C+Tegucigalpa%2C+Honduras&format=json&limit=1

SUCCESS → Toncontín International Airport, Tegucigalpa, Honduras → 14.0576, -87.2163832

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Greensburg+Municipal+Airport+%28Decatur+County%29%2C+Indiana%2C+United+States+of+America&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Greensburg+Municipal+Airport+%28Decatur+County%29%2C+Indiana%2C+United+States+of+America&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Greensburg Municipal Airport (Decatur County), Indiana, United States of America',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Greensburg+Municipal+Airport+%28Decatur+County%29%2C+Indiana%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Greensburg+Municipal+Airport+%28Decatur+County%29%2C+Indiana%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Greensburg+Municipal+Airport+%28Decatur+County%29%2C+Indiana%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

SUCCESS → Greensburg Municipal Airport (Decatur County), Indiana, United States of America → 39.3169295, -85.5256477
SUCCESS → Norfolk, Virginia, United States of America → 36.8493695, -76.2899539
CACHE HIT → Novoternovskiy, Russia → nan, nan
CACHE HIT → Sidra Airstrip, Libya → nan, nan
CACHE HIT → Khartoum International Airport, Sudan → 15.5902124, 32.5550536
FAILED → Bangoka International Airport, Kisangani, Democratic Republic of the Congo
CACHE HIT → Mathiang Airfield, South Sudan → nan, nan
FAILED → Tenerife South–Reina Sofía Airport, Spain
CACHE HIT → Munich Airport (Franz Josef Strauß), Germany → nan, nan
CACHE HIT → Barnstable Municipal Airport, Hyannis, Massachusetts, United States of America → 41.6707658, -70.2843904
CACHE HIT → Tegal Lilin, Indonesia → nan, nan
CACHE HIT → Gryzlov, Russia → nan, nan
CACHE HIT → Pulkovo Airport, Saint Petersburg, Russia → 59.8016986, 30.2676011
CACHE HIT → Khartoum International Airport, Sudan → 15.5902124, 32.5550536
CACHE HIT → Óscar Machado Zuloaga International Airport, Charallave, Venezuela → nan, nan
FAILED → Plan de Guadalupe International Airport, Saltillo, Mexico
CACHE HIT → El Dorado International Airport, Bogotá, Colombia → 4.7020946, -74.1477132
SUCCESS → Marcel Marchant Airport (La Paloma), Puerto Montt, Chile → -41.454479, -72.9192955
FAILED → Hook Lake, Northwest Territories, Canada
CACHE HIT → Syamsudin Noor International Airport, Banjarmasin, Indonesia → nan, nan
CACHE HIT → Manila, Philippines → 14.5904492, 120.9803621
SUCCESS → Brandywine Regional Airport, Pennsylvania, United States of America → 39.990041, -75.5810185
CACHE HIT → Lisbon FIR, Portugal → nan, nan
CACHE HIT → Miguel Hidalgo y Costilla International Airport, Guadalajara, Mexico → 20.5259, -103.29111
FAILED → Reading Regional Airport (Spaatz Field), Pennsylvania, United States of America
CACHE HIT → Don Mueang International Airport, Bangkok, Thailand → 13.9122207, 100.6035314
CACHE HIT → Montréal–Pierre Elliott Trudeau International Airport, Quebec, Canada → nan, nan
CACHE HIT → St. Louis Lambert International Airport, Missouri, United States of America → 38.7496273, -90.3704702
FAILED → Punta Delgada Airport, Isla La Tortuga, Venezuela
CACHE HIT → Saint Barthélemy → 17.8967693, -62.825598
FAILED → Canyonlands Regional Airport, Moab, Utah, United States of America
CACHE HIT → Ernesto Cortissoz International Airport, Barranquilla, Colombia → nan, nan
CACHE HIT → Manas International Airport, Bishkek, Kyrgyzstan → nan, nan
CACHE HIT → La Puente, Cabañas, Zacapa, Guatemala → nan, nan
CACHE HIT → Munich Airport (Franz Josef Strauß), Germany → nan, nan
CACHE HIT → Barangay Bucana, Davao City, Philippines → 7.0539426, 125.5989103
SUCCESS → Kufra Airport, Libya → 24.1781055, 23.3139961
FAILED → Sultan Thaha Syaifuddin International Airport, Jambi, Indonesia
CACHE HIT → Rickenbacker International Airport, Columbus, Ohio, United States of America → 39.8132172, -82.9341997
CACHE HIT → Kavumu Airport, Bukavu, Democratic Republic of the Congo → nan, nan
CACHE HIT → Mariscal Sucre International Airport, Quito, Ecuador → -0.127422, -78.3566377
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
SUCCESS → Khrabrovo Airport, Kaliningrad, Russia → 54.8822001, 20.58512
FAILED → Sylt Airport (Westerland), Germany
SUCCESS → Learmonth Airport, Western Australia, Australia → -22.2280017, 114.085391
SUCCESS → Tenzing-Hillary Airport, Lukla, Nepal → 27.6866013, 86.7291582
CACHE HIT → Bloemspruit Air Force Base, Bloemfontein, South Africa → nan, nan
CACHE HIT → Simón Bolívar International Airport, Caracas, Venezuela → nan, nan
FAILED → Moss Airport Rygge, Norway
CACHE HIT → Juanda International Airport, Surabaya, Indonesia → -7.3747119, 112.7946133
CACHE HIT → Ngurah Rai International Airport, Denpasar, Bali, Indonesia → -8.7458582, 115.167339
CACHE HIT → Nyala Lodge Airstrip, South Africa → nan, nan
FAILED → Punta Chivato Airstrip, Baja California Sur, Mexico
CACHE HIT → Benito Juárez International Airport, Mexico City, Mexico → 19.4342349, -99.0733121
SUCCESS → Fakfak Torea Airport, Fakfak, Indonesia → -2.920213, 132.2666077
FAILED → Verkhnyaya Pesha, Arkhangelsk Oblast, Russia
CACHE HIT → Munich Airport (Franz Josef Strauß), Germany → nan, nan
CACHE HIT → Atlangatepec Air Force Base, Tlaxcala, Mexico → nan, nan
CACHE HIT → Caribbean Sea (off Turks and Caicos Islands) → nan, nan
CACHE HIT → Captain Rogelio Castillo National Airport, Celaya, Mexico → 20.5456333, -100.8852786
FAILED → Sharpe Farms Airport, Lewistown, Missouri, United States of America
FAILED → Jeongseok Airport, Jeju Island, South Korea
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → Tony Camp, Antarctica → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Wilmington+International+Airport+%28ILM%29%2C+North+Carolina%2C+United+States+of+America&format=json&limit=1

FAILED → Wilmington International Airport (ILM), North Carolina, United States of America
CACHE HIT → Bender Qassim International Airport, Bosaso, Somalia → 11.277856, 49.1429744
SUCCESS → Weehawken, New Jersey (Hudson River), United States of America → 40.7624833, -74.0192712
CACHE HIT → Mohammed V International Airport, Casablanca, Morocco → nan, nan
CACHE HIT → Anyang, Gyeonggi Province, South Korea → 37.3938528, 126.9570605
FAILED → Mojave Air and Space Port, Kern County, California, United States of America
CACHE HIT → General Pedro J. Méndez International Airport, Ciudad Victoria, Mexico → 23.6999115, -98.9542838
CACHE HIT → Samedan Airport (St. Moritz), Switzerland → nan, nan
SUCCESS → Santo António, Rio Manacapuru, Amazonas, Brazil → -2.6230544, -60.9508711
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Anadolu+Airport%2C+Eski%C5%9Fehir%2C+Turkey&format=json&limit=1

FAILED → Anadolu Airport, Eskişehir, Turkey
SUCCESS → Heraklion International Airport (Nikos Kazantzakis), Crete, Greece → 35.337058, 25.180972
CACHE HIT → Samedan Airport (St. Moritz), Switzerland → nan, nan
CACHE HIT → Ralph Wien Memorial Airport, Kotzebue, Alaska, United States of America → 66.8836843, -162.6107466
FAILED → Vare María Airport, Guasdualito, Venezuela
FAILED → Germán Olano Air Base, Palanquero, Colombia
CACHE HIT → Enrique Olaya Herrera Airport, Medellín, Colombia → nan, nan
CACHE HIT → Manas International Airport, Bishkek, Kyrgyzstan → nan, nan
CACHE HIT → Amsterdam Airport Schiphol, Netherlands → 52.3269801, 4.7415053
FAILED → Khok Katiam Air Force Base, Lopburi Province, Thailand
CACHE HIT → Soekarno–Hatta International Airport, Jakarta, Indonesia → -6.1238696, 106.6429036
CACHE HIT → Mariscal Sucre International Airport, Quito, Ecuador → -0.127422, -78.3566377
CACHE HIT → Hartsfield–Jackson Atlanta International Airport, Georgia, United States of America → 33.6374009, -84.4298161
CACHE HIT → Barangay San Miguel, Baggao, Cagayan Province, Philippines → nan, nan
CACHE HIT → Husein Sastranegara International Airport, Bandung, Indonesia → -6.8995168, 107.5760475
SUCCESS → Thoulakhom District, Laos → 18.3534934, 102.7337995
SUCCESS → Batuco, Chile → -33.2300466, -70.8085254
SUCCESS → Sangster International Airport, Montego Bay, Jamaica → 18.5037807, -77.9114681
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → Luis Muñoz Marín International Airport, San Juan, Puerto Rico → nan, nan
CACHE HIT → Miguel Hidalgo y Costilla International Airport, Guadalajara, Mexico → 20.5259, -103.29111
SUCCESS → Massamba, Democratic Republic of the Congo → -5.2696903, 14.8518656
CACHE HIT → Seongmu Air Base, South Korea → nan, nan
SUCCESS → King Khalid International Airport, Riyadh, Saudi Arabia → 24.9586204, 46.7110396
CACHE HIT → Aba Tenna Dejazmach Yilma International Airport, Dire Dawa, Ethiopia → 9.6251062, 41.8523848
FAILED → Cologne Bonn Airport (Konrad Adenauer), Germany
FAILED → Iswahyudi Airport, Madiun, Indonesia

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Terravista+Airport%2C+Porto+Seguro%2C+Bahia%2C+Brazil&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Terravista+Airport%2C+Porto+Seguro%2C+Bahia%2C+Brazil&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Terravista Airport, Porto Seguro, Bahia, Brazil',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Terravista+Airport%2C+Porto+Seguro%2C+Bahia%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Terravista+Airport%2C+Porto+Seguro%2C+Bahia%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Terravista+Airport%2C+Porto+Seguro%2C+Bahia%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

SUCCESS → Terravista Airport, Porto Seguro, Bahia, Brazil → -16.5352992, -39.1133771
SUCCESS → São Paulo, Brazil → -23.5506507, -46.6333824
SUCCESS → Matari Airport, Isiro, Democratic Republic of the Congo → 2.8285449, 27.5872867
FAILED → Approx. 160 km NNW of São Pedro and São Paulo Archipelago, Atlantic Ocean
FAILED → Constance Halaveli Resort Lagoon, Maldives
FAILED → Gryttjom Airfield, Uppsala County, Sweden
SUCCESS → Sittwe Airport, Myanmar → 20.1330489, 92.8731834
FAILED → Rinchi, West Siang District, Arunachal Pradesh, India
CACHE HIT → Khartoum International Airport, Sudan → 15.5902124, 32.5550536
FAILED → Kadamdzhay, Batken District, Kyrgyzstan
SUCCESS → Tanah Merah Airport, Papua, Indonesia → -6.096033, 140.3042634
CACHE HIT → Ministro Pistarini International Airport, Buenos Aires, Argentina → -34.8168141, -58.5474234
CACHE HIT → Meacham International Airport, Fort Worth, Texas, United States of America → 32.8307121, -97.3595581
FAILED → Pology, Zaporizhzhia Oblast, Ukraine
SUCCESS → Wangerooge Airport, Germany → 53.7857438, 7.911052
FAILED → Great Barrier Aerodrome, Great Barrier Island, New Zealand
FAILED → Sarif Umra Airstrip, Sudan
CACHE HIT → South Bimini Airport, Bimini, Bahamas → 25.69984, -79.2680124
FAILED → Vicenza VOR (VIC), Italy
FAILED → Mashhad International Airport (Shahid Hashemi Nejad), Iran
CACHE HIT → Constable Point (Nerlerit Inaat), Greenland → nan, nan
SUCCESS → Akanu Ibiam International Airport, Enugu, Nigeria → 6.4751503, 7.5613389
SUCCESS → João Paulo II Airport, Ponta Delgada, Azores, Portugal → 37.7431464, -25.7012684
SUCCESS → Louisville, Kentucky, United States of America → 38.2542376, -85.759407
CACHE HIT → Almeirim, Viseu District, Portugal → nan, nan
CACHE HIT → Simón Bolívar International Airport, Caracas, Venezuela → nan, nan
CACHE HIT → Ninoy Aquino International Airport, Manila, Philippines → 14.5123016, 121.0218861
CACHE HIT → Maya–Maya Airport, Brazzaville, Republic of the Congo → -4.2510091, 15.2538455
CACHE HIT → Quatro de Fevereiro Airport, Luanda, Angola → -8.861408, 13.2287561
SUCCESS → JAGS McCartney International Airport, Grand Turk, Turks and Caicos Islands → 21.4444155, -71.1417299
CACHE HIT → JAGS McCartney International Airport, Grand Turk, Turks and Caicos Islands → 21.4444155, -71.1417299
SUCCESS → Sierra Blanca Regional Airport, Ruidoso, New Mexico, United States of America → 33.4638054, -105.5335402
SUCCESS → Long Apung, North Kalimantan, Indonesia → 1.7066893, 114.9710758
SUCCESS → Varginha, Minas Gerais, Brazil → -21.5565914, -45.4340674
CACHE HIT → Aktobe Airport, Aktobe, Kazakhstan → 50.2470166, 57.2079299
CACHE HIT → Benito Juárez International Airport, Mexico City, Mexico → 19.4342349, -99.0733121
CACHE HIT → Benito Juárez International Airport, Mexico City, Mexico → 19.4342349, -99.0733121
SUCCESS → Sudjarwo Tjondronegoro Airport, Serui, Indonesia → -1.8755707, 136.239404
FAILED → Off the coast of Uruguay (Atlantic Ocean)
CACHE HIT → Joint Base Elmendorf–Richardson, Anchorage, Alaska, United States of America → 61.2349181, -149.7451095
FAILED → Um Galala Airstrip, Sudan
SUCCESS → Augusto C. Sandino International Airport, Managua, Nicaragua → 12.1407312, -86.1682362
CACHE HIT → Kwamalasamutu Airfield, Suriname → nan, nan
FAILED → Molokai Airport, Molokaʻi, Hawaii, United States of America
CACHE HIT → Ninoy Aquino International Airport, Manila, Philippines → 14.5123016, 121.0218861
FAILED → Carrasco International Airport, Montevideo, Uruguay
CACHE HIT → Manchester Airport, United Kingdom → 53.3503421, -2.2803693
CACHE HIT → Pamalican Island Airport, Philippines → nan, nan
CACHE HIT → Flamingo International Airport, Bonaire, Caribbean Netherlands → nan, nan
SUCCESS → Minsk National Airport, Belarus → 53.8876628, 28.0341227
CACHE HIT → O. R. Tambo International Airport, Johannesburg, South Africa → -26.1350013, 28.2270057
CACHE HIT → Aldeias Aurélio, Amazonas, Brazil → nan, nan
CACHE HIT → Bender Qassim International Airport, Bosaso, Somalia → 11.277856, 49.1429744
CACHE HIT → Sinkrebaka, Mali → nan, nan
CACHE HIT → Treasure Coast International Airport, Fort Pierce, Florida, United States of America → 27.4945813, -80.3665069
CACHE HIT → Ministro Pistarini International Airport, Buenos Aires, Argentina → -34.8168141, -58.5474234
FAILED → Ivanovo Severny Air Base, Ivanovo Oblast, Russia
CACHE HIT → Goma International Airport, Goma, Democratic Republic of the Congo → -1.6648635, 29.2381116
FAILED → Tarakigné area near Kolokani, Mali
SUCCESS → Le René, Coltano, Italy → 43.6391855, 10.3923427
FAILED → Isabel Pasar Airstrip, Philippines
CACHE HIT → Rio de Janeiro–Galeão International Airport, Brazil → nan, nan
CACHE HIT → Matthew Town, Great Inagua Island, Bahamas → nan, nan
FAILED → Tonj Airstrip, South Sudan
CACHE HIT → Sultan Hasanuddin International Airport, Makassar, Indonesia → -5.0767232, 119.5510095
SUCCESS → Norman Manley International Airport, Kingston, Jamaica → 17.9355606, -76.7809809
CACHE HIT → Vomo Island, Fiji → nan, nan
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
FAILED → Lake Cumberland Regional Airport, Somerset, Kentucky, United States of America
FAILED → Piajó Airstrip, Chief's Island, Okavango Delta, Botswana
CACHE HIT → Eagle County Regional Airport, Colorado, United States of America → 39.6422569, -106.9172206
SUCCESS → Moba Airport, Democratic Republic of the Congo → -7.0847933, 29.737128
CACHE HIT → Amsterdam Airport Schiphol, Netherlands → 52.3269801, 4.7415053
SUCCESS → Sand Point Airport, Alaska, United States of America → 55.3129232, -160.5207244
FAILED → Wilma Rebelo Airfield, Senador José Porfírio, Pará, Brazil
CACHE HIT → Coventry Airport, Baginton, United Kingdom → 52.3700591, -1.4812023
CACHE HIT → Quatro de Fevereiro Airport, Luanda, Angola → -8.861408, 13.2287561
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → General Mariano Escobedo International Airport, Monterrey, Mexico → nan, nan
CACHE HIT → Sultan Aji Muhammad Sulaiman Sepinggan International Airport, Balikpapan, Indonesia → -1.2669684, 116.8970703
CACHE HIT → Campo de Marte Airport, São Paulo, Brazil → -23.5093734, -46.6393378
CACHE HIT → Ted Stevens Anchorage International Airport, Alaska, United States of America → 61.1810353, -149.9978919
CACHE HIT → Bender Qassim International Airport, Bosaso, Somalia → 11.277856, 49.1429744
SUCCESS → Perth Airport, Western Australia, Australia → -31.9415213, 115.9655769
CACHE HIT → Eduardo Gomes International Airport, Manaus, Amazonas, Brazil → -3.0356561, -60.0459675
SUCCESS → Tallinn Lennart Meri Airport, Estonia → 59.414383, 24.8368511
CACHE HIT → Domodedovo International Airport, Moscow, Russia → 55.4087122, 37.9094721
FAILED → Clark Regional Airport, Jeffersonville, Indiana, United States of America
CACHE HIT → Ivanovo Severny Air Base, Ivanovo Oblast, Russia → nan, nan
SUCCESS → Bahías de Huatulco International Airport, Mexico → 15.7759827, -96.2586987
FAILED → Melville Island, Nunavut, Canada
CACHE HIT → Hong Kong International Airport (Chek Lap Kok), Hong Kong → 22.3125986, 113.9172999
CACHE HIT → General Mariano Escobedo International Airport, Monterrey, Mexico → nan, nan
SUCCESS → Rendani Airport, Manokwari, Indonesia → -0.8909731, 134.0491786
SUCCESS → Kangel Danda Airport, Nepal → 27.410708, 86.6463633
FAILED → Marina di Campo Airport, Elba Island, Italy
FAILED → Marianivka, Odesa Region, Ukraine
CACHE HIT → Fabio Alberto León Bentley Airport, Mitú, Colombia → 1.253429, -70.2340241
CACHE HIT → RAF Brize Norton, Oxfordshire, United Kingdom → 51.7511351, -1.579378
CACHE HIT → Alert, Nunavut, Canada → 82.4989872, -62.3506712
SUCCESS → Osypnoy Bugor, Astrakhan Oblast, Russia → 46.2871581, 48.061173
CACHE HIT → Biscarrosse – Parentis Seaplane Base, France → nan, nan
CACHE HIT → San Pedro, Catacamas, Honduras → nan, nan
CACHE HIT → Sharana Air Base, Afghanistan → nan, nan
CACHE HIT → Amsterdam Airport Schiphol, Netherlands → 52.3269801, 4.7415053
SUCCESS → Peru → -6.8699697, -75.0458515
SUCCESS → Puerta del Este, Guarenas, Venezuela → 10.4765677, -66.6283441
CACHE HIT → Felipe Carrillo Puerto Airfield, Mexico → nan, nan
SUCCESS → Shabunda Airport, Democratic Republic of the Congo → -2.6897975, 27.3442817
CACHE HIT → Václav Havel Airport Prague, Czech Republic → 50.1020451, 14.2705663
CACHE HIT → Václav Havel Airport Prague, Czech Republic → 50.1020451, 14.2705663
CACHE HIT → Capitán FAP José A. Quiñones González International Airport, Chiclayo, Peru → nan, nan
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → Berlin Brandenburg Airport, Germany → 52.3659284, 13.4886435
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
CACHE HIT → Rocky Mountain Metropolitan Airport, Colorado, United States of America → 39.914579, -105.1295243
SUCCESS → Voznesenskoye, Nizhny Novgorod Oblast, Russia → 54.8906328, 42.7598373
FAILED → Wiesbaden Army Airfield (Clay Kaserne), Germany
FAILED → Tuzla Airfield, Constanța County, Romania
CACHE HIT → Ninoy Aquino International Airport, Manila, Philippines → 14.5123016, 121.0218861
CACHE HIT → Lubumbashi International Airport, Democratic Republic of the Congo → -11.5926492, 27.5259188
SUCCESS → Rio Santa, Amapá, Brazil → 0.0203649, -51.0563844
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
SUCCESS → Wittman Regional Airport, Oshkosh, Wisconsin, United States of America → 43.9739457, -88.5558078
CACHE HIT → King Khalid International Airport, Riyadh, Saudi Arabia → 24.9586204, 46.7110396
FAILED → Benazir Bhutto International Airport, Islamabad, Pakistan
CACHE HIT → Joint Base Elmendorf–Richardson, Anchorage, Alaska, United States of America → 61.2349181, -149.7451095
FAILED → Forward Operating Base Dwyer, Helmand Province, Afghanistan
FAILED → Mount Healy, Denali National Park, Alaska, United States of America
FAILED → Kumushkyne, Ukraine
CACHE HIT → Salt Lake City Intn\'l Airport, UT, United States of America → nan, nan
CACHE HIT → Istanbul Atatürk Airport, Turkey → 40.9782389, 28.8263208
SUCCESS → Santos Dumont Airport, Rio de Janeiro, Brazil → -22.9104541, -43.1641922
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
FAILED → Gustavo Rojas Pinilla International Airport, San Andrés Island, Colombia
CACHE HIT → Bastipur, Makwanpur District, Nepal → nan, nan
CACHE HIT → Bandundu Airport, Democratic Republic of the Congo → -3.3113069, 17.3812425
CACHE HIT → Tallinn Lennart Meri Airport, Estonia → 59.414383, 24.8368511
FAILED → Izhma Airport, Komi Republic, Russia
SUCCESS → Manuel Carlos Piar International Airport, Puerto Ordaz, Venezuela → 8.2877988, -62.7611544
FAILED → Montmagny Airport, Quebec, Canada
CACHE HIT → Dare County Regional Airport, Manteo, North Carolina, United States of America → 35.9199194, -75.6972044
SUCCESS → Kirensk, Irkutsk Oblast, Russia → 57.776356, 108.116295
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
CACHE HIT → Mukinge Airport, Zambia → nan, nan
SUCCESS → Sitka Rocky Gutierrez Airport, Sitka, Alaska, United States of America → 57.0479557, -135.3635849
CACHE HIT → Bugulumisa, Democratic Republic of the Congo → nan, nan
FAILED → Seville Airport (San Pablo Airport), Spain
CACHE HIT → Mohammed V International Airport, Casablanca, Morocco → nan, nan
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
FAILED → Supadio International Airport, Pontianak, Indonesia
FAILED → Guasimal, Sancti Spíritus Province, Cuba
CACHE HIT → Mike Zubko Airport, Inuvik, Northwest Territories, Canada → nan, nan
CACHE HIT → Mike Zubko Airport, Inuvik, Northwest Territories, Canada → nan, nan
CACHE HIT → Mike Zubko Airport, Inuvik, Northwest Territories, Canada → nan, nan
SUCCESS → Alférez FAP David Figueroa Fernandini Airport, Huánuco, Peru → -9.8787644, -76.2050891
CACHE HIT → Jinnah International Airport, Karachi, Pakistan → 24.9058248, 67.1614489
CACHE HIT → Los Angeles Intn\'l Airport, CA, United States of America → nan, nan
FAILED → Cheddi Jagan International Airport, Georgetown, Guyana
CACHE HIT → Bunger Hills, Antarctica → nan, nan
FAILED → Marrakesh Menara Airport, Morocco
SUCCESS → Dane County Regional Airport, Madison, Wisconsin, United States of America → 43.1420815, -89.3377453
CACHE HIT → General Mariano Escobedo International Airport, Monterrey, Mexico → nan, nan
CACHE HIT → Hong Kong International Airport (Chek Lap Kok), Hong Kong → 22.3125986, 113.9172999
CACHE HIT → Jinnah International Airport, Karachi, Pakistan → 24.9058248, 67.1614489
CACHE HIT → Amsterdam Airport Schiphol, Netherlands → 52.3269801, 4.7415053
FAILED → Flight route between St. Louis and Milwaukee, United States of America
CACHE HIT → Berlin Brandenburg Airport, Germany → 52.3659284, 13.4886435
CACHE HIT → Pago Pago, Tutuila, American Samoa → nan, nan
CACHE HIT → Domodedovo International Airport, Moscow, Russia → 55.4087122, 37.9094721
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → Doncaster Sheffield Airport, United Kingdom → 53.4809342, -1.0107445
CACHE HIT → Soekarno–Hatta International Airport, Jakarta, Indonesia → -6.1238696, 106.6429036
FAILED → Sri Chaur Village, Okhaldhunga District, Nepal
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
CACHE HIT → Samedan Airport (St. Moritz), Switzerland → nan, nan
FAILED → Krasny Oktyabr, Tula Oblast, Russia
CACHE HIT → Istanbul Atatürk Airport, Turkey → 40.9782389, 28.8263208
SUCCESS → Abraham Lincoln Capital Airport, Springfield, Illinois, United States of America → 39.8436861, -89.6795659
CACHE HIT → Cyril E. King Airport, Saint Thomas, U.S. Virgin Islands → 18.3347691, -64.9724536
CACHE HIT → Tharjath Airstrip, South Sudan → nan, nan
SUCCESS → El Capricho, Ecuador → 0.7342615, -79.313618
CACHE HIT → Fa'a'ā International Airport, Papeete, French Polynesia → nan, nan
CACHE HIT → Sulaymaniyah International Airport, Iraq → nan, nan
SUCCESS → Niʻihau, Hawaii, United States of America → 21.8922167, -160.1516422
FAILED → Raja Haji Fisabilillah International Airport (formerly Kijang Airport), Bintan Island, Indonesia
SUCCESS → Toussaint Louverture International Airport, Port-au-Prince, Haiti → 18.5790123, -72.296065
CACHE HIT → Appleton International Airport, Wisconsin, United States of America → nan, nan
FAILED → Mount Biega, Democratic Republic of the Congo
CACHE HIT → Prince Mohammad bin Abdulaziz International Airport, Medina, Saudi Arabia → 24.5554858, 39.7060859
FAILED → Ingeniero Juan Guillermo Villasana Airport, Pachuca, Mexico
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
CACHE HIT → El Alto International Airport, La Paz, Bolivia → -16.5122206, -68.190261
SUCCESS → Garbuzovo, Belgorod Oblast, Russia → 50.4666981, 38.7522016
CACHE HIT → Clayton County Airport – Tara Field, Georgia, United States of America → nan, nan
CACHE HIT → Meadows Field Airport, Bakersfield, California, United States of America → nan, nan
CACHE HIT → King County International Airport (Boeing Field), Seattle, Washington, United States of America → nan, nan
SUCCESS → Tripoli International Airport, Libya → 32.6684925, 13.149414
CACHE HIT → Benina International Airport, Benghazi, Libya → 32.1009176, 20.2734102
CACHE HIT → Benina International Airport, Benghazi, Libya → 32.1009176, 20.2734102
CACHE HIT → Benina International Airport, Benghazi, Libya → 32.1009176, 20.2734102
CACHE HIT → King County International Airport (Boeing Field), Seattle, Washington, United States of America → nan, nan
CACHE HIT → Clark Regional Airport, Jeffersonville, Indiana, United States of America → nan, nan
FAILED → Tianshan Mountains, China
CACHE HIT → Dibrova, Zhytomyr Region, Ukraine → nan, nan
CACHE HIT → Amsterdam Airport Schiphol, Netherlands → 52.3269801, 4.7415053
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
SUCCESS → Narita International Airport, Japan → 35.7758715, 140.3933101
CACHE HIT → Simón Bolívar International Airport, Caracas, Venezuela → nan, nan
CACHE HIT → Río Gallegos, Santa Cruz, Argentina → -51.6268852, -69.105804
FAILED → Ust-Kamchatsk Airport, Kamchatka Krai, Russia
SUCCESS → John A. Osborne Airport, Montserrat → 16.7914596, -62.1934917
CACHE HIT → Copenhagen Airport (Kastrup), Denmark → 55.6309113, 12.6492236
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
SUCCESS → Little Rock Air Force Base, Jacksonville, Arkansas, United States of America → 34.9059274, -92.13877
CACHE HIT → Little Rock Air Force Base, Jacksonville, Arkansas, United States of America → 34.9059274, -92.13877
FAILED → Greenville Mid-Delta Airport, Mississippi, United States of America
CACHE HIT → Hartsfield–Jackson Atlanta International Airport, Georgia, United States of America → 33.6374009, -84.4298161
FAILED → Sofiyivka, Ipatovsky District, Stavropol Krai, Russia
FAILED → Naval Air Station Point Mugu, Port Hueneme, California, United States of America
SUCCESS → Helgoland Airport (Düne), Germany → 54.185536, 7.914329
SUCCESS → Postville Airport, Newfoundland and Labrador, Canada → 54.9095001, -59.7858494
SUCCESS → John C. Tune Airport, Nashville, Tennessee, United States of America → 36.1840598, -86.8858988
SUCCESS → Buttonville Municipal Airport, Markham, Ontario, Canada → 43.8612256, -79.3697267
CACHE HIT → Berezovy, Amur Oblast, Russia → nan, nan
CACHE HIT → Bangoka International Airport, Kisangani, Democratic Republic of the Congo → nan, nan
CACHE HIT → Biyaadhoo Lagoon, Kaafu Atoll, Maldives → nan, nan
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401
SUCCESS → Warsaw Frederic Chopin Airport, Poland → 52.1630651, 20.9708149
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
SUCCESS → Guelmim Airport, Morocco → 29.0254195, -10.0595614
CACHE HIT → Bichevaya, Russia → nan, nan
SUCCESS → Jeju Island, South Korea → 33.3803475, 126.5482545
FAILED → Gransee Airfield, Brandenburg, Germany
CACHE HIT → Cheddi Jagan International Airport, Georgetown, Guyana → nan, nan
CACHE HIT → Ignatyevo Airport, Blagoveshchensk, Russia → 50.4238456, 127.4127125
SUCCESS → Todzhinsky District, Tuva Republic, Russia → 52.6644167, 96.9558607
FAILED → Neschadinovskaya, Krasnodar Krai, Russia

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tri-State+Airport+%28HTS%29%2C+Huntington%2C+West+Virginia%2C+United+States+of+America&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tri-State+Airport+%28HTS%29%2C+Huntington%2C+West+Virginia%2C+United+States+of+America&format=json&limit=1

FAILED → Tri-State Airport (HTS), Huntington, West Virginia, United States of America
CACHE HIT → Kitakojima Island, Japan → nan, nan
CACHE HIT → T. F. Green International Airport, Providence, Rhode Island, United States of America → nan, nan
SUCCESS → Namoya, Democratic Republic of the Congo → -4.0458404, 27.5368974
CACHE HIT → Merrill Field Airport, Anchorage, Alaska, United States of America → 61.2128462, -149.8390133
SUCCESS → Phifer Airfield, Wheatland, Wyoming, United States of America → 42.0534533, -104.9382999
CACHE HIT → Kavumu Airport, Bukavu, Democratic Republic of the Congo → nan, nan
CACHE HIT → Salgado Filho International Airport, Porto Alegre, Rio Grande do Sul, Brazil → -29.9952684, -51.1663978
CACHE HIT → Tanay Airfield, Kemerovo Oblast, Russia → nan, nan
SUCCESS → Naval Air Station Key West, Florida, United States of America → 24.5782047, -81.683659
FAILED → Aeroclube de Flores Airport, Manaus, Amazonas, Brazil
FAILED → Paulding Northwest Atlanta Airport (KPUJ), Georgia, United States of America
CACHE HIT → Isle of Man Airport (Ronaldsway), Isle of Man → nan, nan
CACHE HIT → Deadman's Cay Airport, Long Island, Bahamas → nan, nan
CACHE HIT → Hartsfield–Jackson Atlanta International Airport, Georgia, United States of America → 33.6374009, -84.4298161

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Macon+County+Airport%2C+Franklin%2C+North+Carolina%2C+United+States+of+America&format=json&limit=1

FAILED → Macon County Airport, Franklin, North Carolina, United States of America
SUCCESS → Kebnekaise, Sweden → 67.9000837, 18.447799
CACHE HIT → Luis Muñoz Marín International Airport, San Juan, Puerto Rico → nan, nan
CACHE HIT → Mariscal Sucre International Airport, Quito, Ecuador → -0.127422, -78.3566377
CACHE HIT → Belaya Kalitva, Rostov Oblast, Russia → 48.1777167, 40.8023923
CACHE HIT → Luis Muñoz Marín International Airport, San Juan, Puerto Rico → nan, nan
CACHE HIT → Abalone Caye, Belize → 16.2092274, -88.6252385
CACHE HIT → Doro Airstrip, South Sudan → nan, nan
SUCCESS → Roshchino International Airport, Tyumen, Russia → 57.1799511, 65.3494166
SUCCESS → George Bush Intercontinental Airport, Houston, Texas, United States of America → 29.9841416, -95.332986
SUCCESS → East Midlands Airport, United Kingdom → 52.8280866, -1.3326695
CACHE HIT → Yida Airstrip, South Sudan → nan, nan
CACHE HIT → Benazir Bhutto International Airport, Islamabad, Pakistan → nan, nan
CACHE HIT → Viru Viru International Airport, Santa Cruz, Bolivia → -17.6470801, -63.134509
CACHE HIT → Jinnah International Airport, Karachi, Pakistan → 24.9058248, 67.1614489
CACHE HIT → Knyazhichi, Sumy Oblast, Ukraine → nan, nan
SUCCESS → Abdullahi Yusuf International Airport, Galkayo, Somalia → 6.7812703, 47.4529078
CACHE HIT → King Abdulaziz International Airport, Jeddah, Saudi Arabia → 21.6585157, 39.1746303
CACHE HIT → La Aurora International Airport, Guatemala City, Guatemala → 14.5831769, -90.5271896
CACHE HIT → Sasereme Airstrip, Papua New Guinea → nan, nan
CACHE HIT → George Bush Intercontinental Airport, Houston, Texas, United States of America → 29.9841416, -95.332986
CACHE HIT → Munich Airport (Franz Josef Strauß), Germany → nan, nan
FAILED → Diplomat Beach Resort, Hollywood, Florida, United States of America
SUCCESS → MacDill Air Force Base, Tampa, Florida, United States of America → 27.8436409, -82.5028722
CACHE HIT → Lézignan-Corbières Airfield, France → nan, nan
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → Supadio International Airport, Pontianak, Indonesia → nan, nan
CACHE HIT → Murtala Muhammed International Airport, Lagos, Nigeria → nan, nan
CACHE HIT → Simón Bolívar International Airport, Caracas, Venezuela → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Isla+de+Flores%2C+R%C3%ADo+de+la+Plata%2C+Uruguay&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Isla+de+Flores%2C+R%C3%ADo+de+la+Plata%2C+Uruguay&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Isla de Flores, Río de la Plata, Uruguay',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Isla+de+Flores%2C+R%C3%ADo+de+la+Plata%2C+Uruguay&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Isla+de+Flores%2C+R%C3%ADo+de+la+Plata%2C+Uruguay&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Isla+de+Flores%2C+R%C3%ADo+de+la+Plata%2C+Uruguay&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Isla+de+Flores%2C+R%C3%ADo+de+la+Plata%2C+Uruguay&format=json&limit=1

FAILED → Isla de Flores, Río de la Plata, Uruguay
CACHE HIT → Aspen/Pitkin County Airport, Colorado, United States of America → 39.2214209, -106.8673412
CACHE HIT → Václav Havel Airport Prague, Czech Republic → 50.1020451, 14.2705663
CACHE HIT → V. C. Bird International Airport, Antigua and Barbuda → 17.1355258, -61.7938871
CACHE HIT → Borodianka Airfield, Kyiv Oblast, Ukraine → 50.6660517, 29.9243013
SUCCESS → Serov, Sverdlovsk Oblast, Russia → 59.6051267, 60.5733483
CACHE HIT → Jersey Airport, Channel Islands → nan, nan
CACHE HIT → DeKalb–Peachtree Airport, Georgia, United States of America → 33.8759268, -84.3028447
SUCCESS → Pweto Airport, Democratic Republic of the Congo → -8.4668805, 28.8898649
FAILED → Halim Perdanakusuma International Airport, Jakarta, Indonesia
SUCCESS → La Leona, Tocaima, Cundinamarca, Colombia → 4.4180109, -74.5783967
SUCCESS → Migalovo Air Base, Tver, Russia → 56.8290938, 35.7564309
CACHE HIT → George Bush Intercontinental Airport, Houston, Texas, United States of America → 29.9841416, -95.332986
SUCCESS → Hof, Germany → 50.3187507, 11.9162992
CACHE HIT → Rangali Island (Conrad Maldives Rangali Island Resort), Alifu Dhaalu Atoll, Maldives → nan, nan
CACHE HIT → Le Castellet Airport, France → nan, nan
SUCCESS → St. George Regional Airport, Utah, United States of America → 37.0350479, -113.5091583
SUCCESS → La Florida Airport, La Serena, Chile → -29.915712, -71.2015613
SUCCESS → Elban, Khabarovsk Krai, Russia → 50.101788, 136.509415
CACHE HIT → Bolshoe Gryzlovo Airfield, Moscow Oblast, Russia → nan, nan
SUCCESS → Francisco de Assis Airport, Juiz de Fora, Minas Gerais, Brazil → -21.7904526, -43.3859624
CACHE HIT → Santiago de Compostela Airport, Spain → nan, nan
FAILED → Umkal airstrip, Chile
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
FAILED → PAF Base Minhas, Kamra, Pakistan
FAILED → Ngerende Airstrip, Masai Mara, Kenya
FAILED → Mayor Buenaventura Vivas Airport, Santo Domingo, Venezuela
CACHE HIT → Jhuosi, Hualien County, Taiwan → nan, nan
SUCCESS → São Paulo–Guarulhos International Airport, São Paulo, Brazil → -23.437859, -46.4805562
SUCCESS → Tweed New Haven Airport, Connecticut, United States of America → 41.2626111, -72.8856344
SUCCESS → Statesboro–Bulloch County Airport, Georgia, United States of America → 32.483065, -81.73961
SUCCESS → Ivdel, Sverdlovsk Oblast, Russia → 60.6973287, 60.4172583
CACHE HIT → V. C. Bird International Airport, Antigua and Barbuda → 17.1355258, -61.7938871
SUCCESS → Viracopos International Airport, Campinas, São Paulo, Brazil → -23.0060223, -47.142004
CACHE HIT → Antalya Airport, Turkey → 36.8999425, 30.7981914
FAILED → Lorient South Brittany Airport (Lann-Bihoué), France
SUCCESS → Glasgow Airport, Scotland, United Kingdom → 55.870556, -4.4357037
CACHE HIT → Bir Kalait, Chad → nan, nan
CACHE HIT → Butembo Airport, Democratic Republic of the Congo → 0.1165498, 29.3133842
CACHE HIT → O. R. Tambo International Airport, Johannesburg, South Africa → -26.1350013, 28.2270057
CACHE HIT → M. R. Štefánik Airport, Bratislava, Slovakia → 48.170844, 17.2100407
CACHE HIT → Atlantic Ocean → 13.581921, -38.320312
CACHE HIT → Yida Airstrip, South Sudan → nan, nan
FAILED → Yugorsk-2 Airfield, Khanty-Mansi Autonomous Okrug, Russia
SUCCESS → Fujinomiya, Shizuoka Prefecture, Japan → 35.2221369, 138.6214683
FAILED → Prince Said Ibrahim International Airport, Moroni, Comoros
CACHE HIT → Maya–Maya Airport, Brazzaville, Republic of the Congo → -4.2510091, 15.2538455
FAILED → Ellis Field Airport, Mekoryuk, Alaska, United States of America
FAILED → Giant's Castle, Drakensberg, South Africa
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
CACHE HIT → La Yesca Airstrip, Mexico → nan, nan
FAILED → Tomas District, Yauyos Province, Peru
CACHE HIT → Holtanna Glacier, Antarctica → nan, nan
SUCCESS → Will Rogers World Airport, Oklahoma City, Oklahoma, United States of America → 35.3848053, -97.6053443
CACHE HIT → Comandante Espora Airport, Bahía Blanca, Argentina → -38.7272941, -62.1714145
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → O. R. Tambo International Airport, Johannesburg, South Africa → -26.1350013, 28.2270057
CACHE HIT → Vnukovo International Airport, Moscow, Russia → 55.5995278, 37.2735752
SUCCESS → Ramón Villeda Morales International Airport, San Pedro Sula, Honduras → 15.455729, -87.9274528
CACHE HIT → El Plumerillo International Airport (Governor Francisco Gabrielli), Mendoza, Argentina → nan, nan
FAILED → Flight route between Los Roques and Caracas, Venezuela
SUCCESS → El Trompillo Airport, Santa Cruz, Bolivia → -17.8112273, -63.1716738
CACHE HIT → Bloemspruit Air Force Base, Bloemfontein, South Africa → nan, nan
CACHE HIT → Cologne Bonn Airport (Konrad Adenauer), Germany → nan, nan
CACHE HIT → Mount Elizabeth, Antarctica → nan, nan
CACHE HIT → Centro Nacional de Paraquedismo Airfield, Boituva, São Paulo, Brazil → nan, nan
CACHE HIT → Halim Perdanakusuma International Airport, Jakarta, Indonesia → nan, nan
FAILED → Knyazhin, Zhytomyr Region, Ukraine
CACHE HIT → Martín Miguel de Güemes International Airport, Salta, Argentina → -24.8595387, -65.4881531
CACHE HIT → Roberts International Airport, Monrovia, Liberia → nan, nan
CACHE HIT → Berlin Brandenburg Airport, Germany → 52.3659284, 13.4886435
FAILED → Staroselye Airport, Rybinsk, Russia
CACHE HIT → João Paulo II Airport, Ponta Delgada, Azores, Portugal → 37.7431464, -25.7012684
CACHE HIT → Goma International Airport, Goma, Democratic Republic of the Congo → -1.6648635, 29.2381116
CACHE HIT → Hartsfield–Jackson Atlanta International Airport, Georgia, United States of America → 33.6374009, -84.4298161
CACHE HIT → Dillingham Airport, Alaska, United States of America → 59.0433568, -158.5112028
CACHE HIT → Soekarno–Hatta International Airport, Jakarta, Indonesia → -6.1238696, 106.6429036
CACHE HIT → Soekarno–Hatta International Airport, Jakarta, Indonesia → -6.1238696, 106.6429036
CACHE HIT → Djolu Airport, Democratic Republic of the Congo → 0.6335769, 22.462892
SUCCESS → Vostochnaya, Ust-Labinsky District, Krasnodar Krai, Russia → 45.3674271, 39.7768125
SUCCESS → Minangkabau International Airport, Padang, Indonesia → -0.7882247, 100.2830945
CACHE HIT → Harry Reid International Airport, Las Vegas, Nevada, United States of America → 36.0861034, -115.1611002
CACHE HIT → São Tomé International Airport, São Tomé and Príncipe → 0.3773992, 6.7148853
CACHE HIT → Doro Airstrip, South Sudan → nan, nan
CACHE HIT → Ngurah Rai International Airport, Denpasar, Bali, Indonesia → -8.7458582, 115.167339
SUCCESS → Incheon International Airport, Seoul, South Korea → 37.5879876, 126.8264828
CACHE HIT → Sam Neua Airport, Laos → nan, nan
SUCCESS → Billy Bishop Toronto City Airport, Ontario, Canada → 43.6280558, -79.3979969
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
SUCCESS → General Leobardo C. Ruiz International Airport, Zacatecas, Mexico → 22.8954945, -102.6863918
CACHE HIT → Chaldovar, Kyrgyzstan → nan, nan
CACHE HIT → Arturo Michelena International Airport, Valencia, Venezuela → 10.1516769, -67.9288155
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
CACHE HIT → Chernolesskoye, Stavropol Krai, Russia → nan, nan
CACHE HIT → Campo de Marte Airport, São Paulo, Brazil → -23.5093734, -46.6393378
FAILED → FOB Shank, Logar Province, Afghanistan
SUCCESS → Varna Airport, Bulgaria → 43.233936, 27.8233416
FAILED → Jyl-Kol, Jalal-Abad Region, Kyrgyzstan
CACHE HIT → Toussaint Louverture International Airport, Port-au-Prince, Haiti → 18.5790123, -72.296065
CACHE HIT → Francisco Bangoy International Airport, Davao City, Philippines → 7.1248797, 125.6434576
FAILED → El Tari International Airport, Kupang, Indonesia
SUCCESS → Ngaoundéré Airport, Cameroon → 7.3561702, 13.5588858
CACHE HIT → Ninoy Aquino International Airport, Manila, Philippines → 14.5123016, 121.0218861
CACHE HIT → Seletar Airport, Singapore → 1.4170202, 103.8680818
CACHE HIT → Francistown Airport, Botswana → nan, nan
CACHE HIT → Harry Reid International Airport, Las Vegas, Nevada, United States of America → 36.0861034, -115.1611002
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → Isla Perico, Panama City, Panama → nan, nan
FAILED → Pyatykhatky, Crimea
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
CACHE HIT → Lubumbashi International Airport, Democratic Republic of the Congo → -11.5926492, 27.5259188
FAILED → Flying Cloud Airport, Minneapolis, Minnesota, United States of America
CACHE HIT → Khartoum International Airport, Sudan → 15.5902124, 32.5550536
CACHE HIT → Bienenfarm Airfield, Nauen, Germany → nan, nan
FAILED → Juana Azurduy de Padilla International Airport, Sucre, Bolivia
CACHE HIT → Guri'el Airstrip, Somalia → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Pinto+Martins+International+Airport%2C+Fortaleza%2C+Cear%C3%A1%2C+Brazil&format=json&limit=1

SUCCESS → Pinto Martins International Airport, Fortaleza, Ceará, Brazil → -3.7761154, -38.5355413
CACHE HIT → Vnukovo International Airport, Moscow, Russia → 55.5995278, 37.2735752
SUCCESS → General Ignacio Pesqueira García International Airport, Hermosillo, Mexico → 29.09211, -111.0546368
FAILED → Viña del Mar Airport (Aeródromo Concón), Chile
CACHE HIT → Murtala Muhammed International Airport, Lagos, Nigeria → nan, nan
CACHE HIT → Acandí, Chocó, Colombia → 8.5115155, -77.2790562
FAILED → Sevryukova, Belgorod Oblast, Russia
CACHE HIT → Ninoy Aquino International Airport, Manila, Philippines → 14.5123016, 121.0218861
SUCCESS → Skulyn, Volyn Oblast, Ukraine → 51.27869, 24.89262
CACHE HIT → Likawage Airstrip, Tanzania → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Colonel+James+Jabara+Airport%2C+Wichita%2C+Kansas%2C+United+States+of+America&format=json&limit=1

SUCCESS → Colonel James Jabara Airport, Wichita, Kansas, United States of America → 37.7461078, -97.2216959
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
FAILED → Tayozhny, Krasnoyarsk Krai, Russia
FAILED → Pogapa Airstrip, Papua Province, Indonesia
CACHE HIT → Devil's Hole, Saint Mary, Jersey, United Kingdom → nan, nan
CACHE HIT → Aeroparque Jorge Newbery, Buenos Aires, Argentina → -34.5594554, -58.4143637
CACHE HIT → Aeroparque Jorge Newbery, Buenos Aires, Argentina → -34.5594554, -58.4143637
CACHE HIT → Simón Bolívar International Airport, Caracas, Venezuela → nan, nan
CACHE HIT → Ministro Pistarini International Airport, Buenos Aires, Argentina → -34.8168141, -58.5474234
FAILED → Kamako, Kasaï Province, Democratic Republic of the Congo
CACHE HIT → Viracopos International Airport, Campinas, São Paulo, Brazil → -23.0060223, -47.142004
CACHE HIT → Buon Ma Thuot Airport, Dak Lak, Vietnam → 12.6668723, 108.1199878

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Pikany+Indian+Airstrip%2C+Par%C3%A1%2C+Brazil&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Pikany+Indian+Airstrip%2C+Par%C3%A1%2C+Brazil&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Pikany Indian Airstrip, Pará, Brazil',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Pikany+Indian+Airstrip%2C+Par%C3%A1%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Pikany+Indian+Airstrip%2C+Par%C3%A1%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Pikany+Indian+Airstrip%2C+Par%C3%A1%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

FAILED → Pikany Indian Airstrip, Pará, Brazil
CACHE HIT → Nnamdi Azikiwe International Airport, Nigeria → 9.0207137, 7.2677714
SUCCESS → Mitiga International Airport, Tripoli, Libya → 32.8951353, 13.2809484
CACHE HIT → Tenerife South–Reina Sofía Airport, Spain → nan, nan
CACHE HIT → Amsterdam Airport Schiphol, Netherlands → 52.3269801, 4.7415053
CACHE HIT → Amsterdam Airport Schiphol, Netherlands → 52.3269801, 4.7415053
CACHE HIT → O. R. Tambo International Airport, Johannesburg, South Africa → -26.1350013, 28.2270057
SUCCESS → Hewanorra International Airport, Saint Lucia → 13.7343239, -60.9538935
CACHE HIT → Harry Reid International Airport, Las Vegas, Nevada, United States of America → 36.0861034, -115.1611002
CACHE HIT → Aspen/Pitkin County Airport, Colorado, United States of America → 39.2214209, -106.8673412
CACHE HIT → Prince Mohammad bin Abdulaziz International Airport, Medina, Saudi Arabia → 24.5554858, 39.7060859
FAILED → Stephenville International Airport, Newfoundland and Labrador, Canada
SUCCESS → Eastern Afghanistan → 34.5166596, 69.1413143
CACHE HIT → Olive Creek, Guyana → nan, nan
CACHE HIT → Plan de Guadalupe International Airport, Saltillo, Mexico → nan, nan
CACHE HIT → Domodedovo International Airport, Moscow, Russia → 55.4087122, 37.9094721
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
CACHE HIT → Istiklal Oil Field Airstrip, Libya → nan, nan
CACHE HIT → Hartsfield–Jackson Atlanta International Airport, Georgia, United States of America → 33.6374009, -84.4298161
CACHE HIT → Juanda International Airport, Surabaya, Indonesia → -7.3747119, 112.7946133
SUCCESS → Fort Lauderdale–Hollywood International Airport, Florida, United States of America → 26.072017, -80.1509967
FAILED → Zhengzhou Xinzheng International Airport, China
CACHE HIT → Sabiha Gökçen International Airport, Istanbul, Turkey → 40.8943341, 29.3118058
SUCCESS → Isle of Man → 54.1936805, -4.5591148
CACHE HIT → Vnukovo International Airport, Moscow, Russia → 55.5995278, 37.2735752
CACHE HIT → Naval Air Facility Atsugi, Kanagawa Prefecture, Japan → 35.4544706, 139.4425475
CACHE HIT → Naval Air Facility Atsugi, Kanagawa Prefecture, Japan → 35.4544706, 139.4425475
CACHE HIT → Naval Air Facility Atsugi, Kanagawa Prefecture, Japan → 35.4544706, 139.4425475
FAILED → Stella Maris Estate Airstrip, Long Island, Bahamas
CACHE HIT → Naval Air Facility Atsugi, Kanagawa Prefecture, Japan → 35.4544706, 139.4425475
CACHE HIT → Naval Air Facility Atsugi, Kanagawa Prefecture, Japan → 35.4544706, 139.4425475
CACHE HIT → Naval Air Facility Atsugi, Kanagawa Prefecture, Japan → 35.4544706, 139.4425475
CACHE HIT → Naval Air Facility Atsugi, Kanagawa Prefecture, Japan → 35.4544706, 139.4425475
SUCCESS → Sandhikharka, Nepal → 27.975697, 83.127113
SUCCESS → Geneva Airport (Cointrin), Switzerland → 46.2378164, 6.1081212
CACHE HIT → Cristiano Ronaldo International Airport, Funchal, Madeira, Portugal → nan, nan
CACHE HIT → Rubkona Airport, South Sudan → nan, nan
FAILED → Lajes Airport, Terceira Island, Azores, Portugal
CACHE HIT → Kish International Airport, Kish Island, Iran → nan, nan
CACHE HIT → Pogapa Airstrip, Papua Province, Indonesia → nan, nan
CACHE HIT → Sydney Kingsford Smith International Airport, New South Wales, Australia → nan, nan
FAILED → Sultan Abdul Aziz Shah Airport, Kuala Lumpur, Malaysia
CACHE HIT → Brasília International Airport (Presidente Juscelino Kubitschek), Federal District, Brazil → nan, nan
SUCCESS → Karauli District, Rajasthan, India → 26.4530971, 77.0160461
CACHE HIT → Munich Airport (Franz Josef Strauß), Germany → nan, nan
CACHE HIT → Plan de Guadalupe International Airport, Saltillo, Mexico → nan, nan
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
CACHE HIT → Guri'el Airstrip, Somalia → nan, nan
CACHE HIT → Murtala Muhammed International Airport, Lagos, Nigeria → nan, nan
CACHE HIT → Rickenbacker International Airport, Columbus, Ohio, United States of America → 39.8132172, -82.9341997
SUCCESS → Terbuny, Lipetsk Oblast, Russia → 52.146828, 38.278389
CACHE HIT → Tocumen International Airport, Panama City, Panama → nan, nan
CACHE HIT → Aeroparque Jorge Newbery, Buenos Aires, Argentina → -34.5594554, -58.4143637
CACHE HIT → Ganla, Niger → nan, nan
CACHE HIT → Logan International Airport, Boston, Massachusetts, United States of America → 42.3631767, -71.0136401
SUCCESS → El Wak Airport, Kenya → 2.8052073, 40.8525185
SUCCESS → Apure State, Venezuela → 7.0735781, -68.8202025
CACHE HIT → Carmelo International Airport (Zagarzazú Airport), Uruguay → nan, nan
CACHE HIT → Coari Airport, Amazonas, Brazil → -4.133102, -63.1297312
CACHE HIT → José Celestino Mutis Airport, Bahía Solano, Colombia → 6.2030693, -77.3952435
CACHE HIT → Mark Anton Airport, Dayton, Tennessee, United States of America → nan, nan
CACHE HIT → Drobysheve, Ukraine → 49.0434703, 37.7340668
SUCCESS → Rybinsk, Yaroslavl Oblast, Russia → 58.0489536, 38.8558908
CACHE HIT → Jinnah International Airport, Karachi, Pakistan → 24.9058248, 67.1614489
CACHE HIT → Jinnah International Airport, Karachi, Pakistan → 24.9058248, 67.1614489
CACHE HIT → Jinnah International Airport, Karachi, Pakistan → 24.9058248, 67.1614489
FAILED → Olsztyn–Dajtki Airport, Poland
CACHE HIT → Juanda International Airport, Surabaya, Indonesia → -7.3747119, 112.7946133
SUCCESS → Imam Khomeini International Airport, Tehran, Iran → 35.4164609, 51.1448324
CACHE HIT → Olsberg-Elpe, Germany → nan, nan
SUCCESS → Bacha Khan International Airport, Peshawar, Pakistan → 33.9910884, 71.5157411
SUCCESS → Samut Prakan Province, Thailand → 13.6531651, 100.8182578
CACHE HIT → Kavumu Airport, Bukavu, Democratic Republic of the Congo → nan, nan
CACHE HIT → Nursultan Nazarbayev International Airport, Kazakhstan → 51.0258535, 71.4641981
CACHE HIT → Jomo Kenyatta International Airport, Nairobi, Kenya → -1.3169486, 36.9288569
CACHE HIT → Vnukovo International Airport, Moscow, Russia → 55.5995278, 37.2735752
CACHE HIT → Hartsfield–Jackson Atlanta International Airport, Georgia, United States of America → 33.6374009, -84.4298161
FAILED → Tarasivka Airfield, Ukraine
SUCCESS → Switzerland → 46.7985624, 8.2319736
CACHE HIT → Carrasco International Airport, Montevideo, Uruguay → nan, nan
FAILED → Foz do Iguaçu/Cataratas International Airport, Paraná, Brazil
CACHE HIT → Doncaster Sheffield Airport, United Kingdom → 53.4809342, -1.0107445
SUCCESS → Reykjavík, Iceland → 64.145981, -21.9422367
FAILED → Shamwana Airstrip, Democratic Republic of the Congo
FAILED → Mulume Munene, Democratic Republic of the Congo
FAILED → Ibans, La Mosquitia, Honduras
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
SUCCESS → Los Cabos International Airport, San José del Cabo, Mexico → 23.1451694, -109.7180129
CACHE HIT → Conroe–North Houston Regional Airport, Texas, United States of America → nan, nan
SUCCESS → Jacksons International Airport, Port Moresby, Papua New Guinea → -9.4402674, 147.2171286
FAILED → Kom Ashwin, Faiyum, Egypt
SUCCESS → Madrid, Spain → 40.416782, -3.703507
CACHE HIT → José Aponte de la Torre Airport, Ceiba, Puerto Rico → 18.2478383, -65.640277
CACHE HIT → Amsterdam Airport Schiphol, Netherlands → 52.3269801, 4.7415053
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → Vnukovo International Airport, Moscow, Russia → 55.5995278, 37.2735752
CACHE HIT → Lorient South Brittany Airport (Lann-Bihoué), France → nan, nan
CACHE HIT → Panamá Pacífico International Airport, Panama → 8.916253, -79.5984002
SUCCESS → Tamanrasset Aguenar – Hadj Bey Akhamok Airport, Algeria → 22.8132233, 5.4511153
CACHE HIT → Shabunda Airport, Democratic Republic of the Congo → -2.6897975, 27.3442817
SUCCESS → Princess Juliana International Airport, Sint Maarten → 18.0408739, -63.1118517
CACHE HIT → Viru Viru International Airport, Santa Cruz, Bolivia → -17.6470801, -63.134509
CACHE HIT → Surat Airport, Gujarat, India → 21.1168313, 72.7422653
CACHE HIT → Grand Bahama International Airport, Freeport, Bahamas → 26.5565128, -78.6955864

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Sugar+Land+Regional+Airport%2C+Houston%2C+Texas%2C+United+States+of+America&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Sugar+Land+Regional+Airport%2C+Houston%2C+Texas%2C+United+States+of+America&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Sugar Land Regional Airport, Houston, Texas, United States of America',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Sugar+Land+Regional+Airport%2C+Houston%2C+Texas%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Sugar+Land+Regional+Airport%2C+Houston%2C+Texas%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Sugar+Land+Regional+Airport%2C+Houston%2C+Texas%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Sugar+Land+Regional+Airport%2C+Houston%2C+Texas%2C+United+States+of+America&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Sugar+Land+Regional+Airport%2C+Houston%2C+Texas%2C+United+States+of+America&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (1/2 tries). Called with (*('Sugar Land Regional Airport, Houston, Texas, United States of America',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Sugar+Land+Regional+Airport%2C+Houston%2C+Texas%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Sugar+Land+Regional+Airport%2C+Houston%2C+Texas%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Sugar+Land+Regional+Airport%2C+Houston%2C+Texas%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Sugar+Land+Regional+Airport%2C+Houston%2C+Texas%2C+United+States+of+America&format=json&limit=1

FAILED → Sugar Land Regional Airport, Houston, Texas, United States of America
FAILED → Teniente Rodolfo Marsh Martin Airport, King George Island, Antarctica
FAILED → Mackall Army Airfield, North Carolina, United States of America
CACHE HIT → Mackall Army Airfield, North Carolina, United States of America → nan, nan
SUCCESS → Montgomery County Airpark, Gaithersburg, Maryland, United States of America → 39.167413, -77.1626858

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Obo+Mission+Airstrip%2C+Central+African+Republic&format=json&limit=1

FAILED → Obo Mission Airstrip, Central African Republic
CACHE HIT → Brittas House Airfield, Ireland → nan, nan
SUCCESS → Uvira, Democratic Republic of the Congo → -3.4055866, 29.1375509
CACHE HIT → Jomo Kenyatta International Airport, Nairobi, Kenya → -1.3169486, 36.9288569
CACHE HIT → Coventry Airport, Baginton, United Kingdom → 52.3700591, -1.4812023
CACHE HIT → Abu al-Duhur Military Airbase, Syria → nan, nan
CACHE HIT → Shatyrkul Mine, Kazakhstan → nan, nan
CACHE HIT → Boca Druif, Aruba → nan, nan
CACHE HIT → Mitiga International Airport, Tripoli, Libya → 32.8951353, 13.2809484
SUCCESS → Rhodes International Airport (Diagoras), Greece → 36.4050007, 28.087407

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Mammoth+Yosemite+Airport%2C+Mammoth+Lakes%2C+California%2C+United+States+of+America&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Mammoth+Yosemite+Airport%2C+Mammoth+Lakes%2C+California%2C+United+States+of+America&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Mammoth Yosemite Airport, Mammoth Lakes, California, United States of America',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Mammoth+Yosemite+Airport%2C+Mammoth+Lakes%2C+California%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Mammoth+Yosemite+Airport%2C+Mammoth+Lakes%2C+California%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Mammoth+Yosemite+Airport%2C+Mammoth+Lakes%2C+California%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

FAILED → Mammoth Yosemite Airport, Mammoth Lakes, California, United States of America
CACHE HIT → George Bush Intercontinental Airport, Houston, Texas, United States of America → 29.9841416, -95.332986
SUCCESS → Daniel K. Inouye International Airport, Honolulu, Hawaii, United States of America → 21.3211445, -157.9184436
CACHE HIT → Malanje Airport, Angola → -9.5250862, 16.3151737
CACHE HIT → Boryspil International Airport, Kyiv, Ukraine → 50.3401779, 30.8915573
CACHE HIT → Boryspil International Airport, Kyiv, Ukraine → 50.3401779, 30.8915573
CACHE HIT → Guernsey Airport, Channel Islands → nan, nan
SUCCESS → St. John's International Airport, Newfoundland and Labrador, Canada → 47.6189907, -52.7452806
SUCCESS → Marco Island Executive Airport, Florida, United States of America → 25.9958845, -81.6728145
SUCCESS → Pyrenees, Spain → 42.5824012, 0.5388272
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
FAILED → Flight route between Tenerife North and Gran Canaria, Spain
SUCCESS → Germany → 51.1638175, 10.4478313
SUCCESS → Goa, India → 15.3004543, 74.0855134
FAILED → Al Dulaimi Air Base, Sana'a, Yemen
CACHE HIT → Al Dulaimi Air Base, Sana'a, Yemen → nan, nan
SUCCESS → Promin, Volyn Oblast, Ukraine → 50.6493896, 25.2966469
CACHE HIT → Barneo Ice Camp, Arctic Ocean → nan, nan
CACHE HIT → Colonel James Jabara Airport, Wichita, Kansas, United States of America → 37.7461078, -97.2216959
CACHE HIT → Colonel James Jabara Airport, Wichita, Kansas, United States of America → 37.7461078, -97.2216959
CACHE HIT → Colonel James Jabara Airport, Wichita, Kansas, United States of America → 37.7461078, -97.2216959
CACHE HIT → Colonel James Jabara Airport, Wichita, Kansas, United States of America → 37.7461078, -97.2216959
CACHE HIT → Colonel James Jabara Airport, Wichita, Kansas, United States of America → 37.7461078, -97.2216959
CACHE HIT → Colonel James Jabara Airport, Wichita, Kansas, United States of America → 37.7461078, -97.2216959
CACHE HIT → Ben Gurion International Airport, Tel Aviv, Israel → nan, nan
CACHE HIT → Caribbean Sea → 15.0000001, -75.0000001
CACHE HIT → Naval Air Station Point Mugu, Port Hueneme, California, United States of America → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Hiroshima+Airport%2C+Japan&format=json&limit=1

SUCCESS → Hiroshima Airport, Japan → 34.4374791, 132.9195109
SUCCESS → Eglin Air Force Base, Valparaiso, Florida, United States of America → 30.461382, -86.5468344
CACHE HIT → Istanbul Atatürk Airport, Turkey → 40.9782389, 28.8263208
SUCCESS → La Chinita International Airport, Maracaibo, Venezuela → 10.5578226, -71.7263232
CACHE HIT → Cape Ashizuri, Kōchi Prefecture, Japan → 32.7250398, 133.0180899
CACHE HIT → Offutt Air Force Base, Nebraska, United States of America → 41.1171964, -95.9081666
CACHE HIT → Dahra Oilfield, Libya → nan, nan
CACHE HIT → Newport News/Williamsburg International Airport, Virginia, United States of America → nan, nan
CACHE HIT → McClellan–Palomar Airport, Carlsbad, California, United States of America → 33.1275461, -117.2814001
SUCCESS → Klaipėda, Lithuania → 55.7127529, 21.1350469
SUCCESS → Sanamer, Stavropol Krai, Russia → 44.0733628, 42.8500427
CACHE HIT → Mandeng Airstrip, South Sudan → nan, nan
SUCCESS → Querétaro Intercontinental Airport, Mexico → 20.6217277, -100.1965062

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=St.+Pete%E2%80%93Clearwater+International+Airport%2C+Florida%2C+United+States+of+America&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=St.+Pete%E2%80%93Clearwater+International+Airport%2C+Florida%2C+United+States+of+America&format=json&limit=1

FAILED → St. Pete–Clearwater International Airport, Florida, United States of America
SUCCESS → Pichavaram, Tamil Nadu, India → 11.4331053, 79.7807079
CACHE HIT → Konan Airport, Japan → nan, nan
FAILED → Kezhma, Kezhemsky District, Krasnoyarsk Krai, Russia
FAILED → Ella Lake, Misty Fjords National Monument, Alaska, United States of America
SUCCESS → Kalaeloa Airport, Kapolei, Hawaii, United States of America → 21.3090432, -158.0717328
SUCCESS → Soewondo Air Force Base, Medan, Indonesia → 3.5587163, 98.6723031
CACHE HIT → Berlin Tegel Airport (closed), Germany → nan, nan
CACHE HIT → Kuredu Island Resort, Lhaviyani Atoll, Maldives → nan, nan
CACHE HIT → Skydive Dubai, Dubai, United Arab Emirates → 25.0907885, 55.1379967
CACHE HIT → Goma International Airport, Goma, Democratic Republic of the Congo → -1.6648635, 29.2381116
CACHE HIT → Chrcynno Airfield, Mazovia, Poland → nan, nan
CACHE HIT → Tocumen International Airport, Panama City, Panama → nan, nan
CACHE HIT → Glasgow Airport, Scotland, United Kingdom → 55.870556, -4.4357037
CACHE HIT → Palm Beach International Airport, Florida, United States of America → 26.6859478, -80.0924865
CACHE HIT → Eduardo Gomes International Airport, Manaus, Amazonas, Brazil → -3.0356561, -60.0459675

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Lagoa+Santa+Air+Base%2C+Minas+Gerais%2C+Brazil&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Lagoa+Santa+Air+Base%2C+Minas+Gerais%2C+Brazil&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Lagoa Santa Air Base, Minas Gerais, Brazil',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Lagoa+Santa+Air+Base%2C+Minas+Gerais%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Lagoa+Santa+Air+Base%2C+Minas+Gerais%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Lagoa+Santa+Air+Base%2C+Minas+Gerais%2C+Brazil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

FAILED → Lagoa Santa Air Base, Minas Gerais, Brazil
CACHE HIT → Domodedovo International Airport, Moscow, Russia → 55.4087122, 37.9094721
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → Saba, Caribbean Netherlands → nan, nan
CACHE HIT → Brown Field Municipal Airport, San Diego, California, United States of America → 32.5727262, -116.9795582
CACHE HIT → Mbuji-Mayi Airport, Democratic Republic of the Congo → -6.1188177, 23.5682265
CACHE HIT → Óscar Machado Zuloaga International Airport, Charallave, Venezuela → nan, nan
CACHE HIT → Harry Reid International Airport, Las Vegas, Nevada, United States of America → 36.0861034, -115.1611002
CACHE HIT → Dakar, Senegal → 14.693425, -17.447938
FAILED → Triangle North Executive Airport, Louisburg, North Carolina, United States of America
CACHE HIT → Harry Reid International Airport, Las Vegas, Nevada, United States of America → 36.0861034, -115.1611002
FAILED → East Wind Lake Seaplane Base, Iliamna, Alaska, United States of America
FAILED → Kanifushi Island, Lhaviyani Atoll, Maldives
SUCCESS → Saarbrücken Airport, Germany → 49.2165735, 7.1119174
CACHE HIT → Skydive Dubai Palm Drop Zone, Dubai, United Arab Emirates → nan, nan
CACHE HIT → Alejandro Velasco Astete International Airport, Cusco, Peru → -13.5363543, -71.9367957
CACHE HIT → Benito Juárez International Airport, Mexico City, Mexico → 19.4342349, -99.0733121
CACHE HIT → O. R. Tambo International Airport, Johannesburg, South Africa → -26.1350013, 28.2270057
SUCCESS → La Crosse Regional Airport, Wisconsin, United States of America → 43.878607, -91.2555715
CACHE HIT → Hasna, North Sinai, Egypt → nan, nan
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
FAILED → Taichung Ching Chuan Kang Airport, Taiwan
SUCCESS → George F. L. Charles Airport, Saint Lucia → 14.0198467, -60.994769
SUCCESS → Ixtapa-Zihuatanejo International Airport, Mexico → 17.6036076, -101.4619957
CACHE HIT → Benito Juárez International Airport, Mexico City, Mexico → 19.4342349, -99.0733121
CACHE HIT → Berlin Brandenburg Airport, Germany → 52.3659284, 13.4886435
CACHE HIT → Oyonnax-Arbent Airfield, France → nan, nan
CACHE HIT → El Tari International Airport, Kupang, Indonesia → nan, nan
CACHE HIT → Sabiha Gökçen International Airport, Istanbul, Turkey → 40.8943341, 29.3118058
CACHE HIT → Istanbul Atatürk Airport, Turkey → 40.9782389, 28.8263208
CACHE HIT → Mbuji-Mayi Airport, Democratic Republic of the Congo → -6.1188177, 23.5682265
CACHE HIT → Anchorage, Alaska, United States of America → 61.2163129, -149.894852

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Gary%2FChicago+International+Airport%2C+Indiana%2C+United+States+of+America&format=json&limit=1

SUCCESS → Gary/Chicago International Airport, Indiana, United States of America → 41.6178246, -87.4141458
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → Tres Esquinas Air Base, Colombia → nan, nan
CACHE HIT → Oajevágge, Sweden → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Maestro+Marinho+Franco+Airport%2C+Rondon%C3%B3polis%2C+Mato+Grosso%2C+Brazil&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Maestro+Marinho+Franco+Airport%2C+Rondon%C3%B3polis%2C+Mato+Grosso%2C+Brazil&format=json&limit=1

SUCCESS → Maestro Marinho Franco Airport, Rondonópolis, Mato Grosso, Brazil → -16.5834324, -54.7248165
CACHE HIT → Luis Muñoz Marín International Airport, San Juan, Puerto Rico → nan, nan
CACHE HIT → Amundsen–Scott South Pole Station, Antarctica → nan, nan
CACHE HIT → Chance Bay, Whitsunday Island, Queensland, Australia → nan, nan
CACHE HIT → Querétaro Intercontinental Airport, Mexico → 20.6217277, -100.1965062
CACHE HIT → Copenhagen Airport (Kastrup), Denmark → 55.6309113, 12.6492236
CACHE HIT → St. Louis Lambert International Airport, Missouri, United States of America → 38.7496273, -90.3704702

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=New+Chitose+Airport%2C+Sapporo%2C+Japan&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=New+Chitose+Airport%2C+Sapporo%2C+Japan&format=json&limit=1

FAILED → New Chitose Airport, Sapporo, Japan
CACHE HIT → Dana, Myagdi District, Nepal → nan, nan
CACHE HIT → Langebaanweg Air Force Base, South Africa → nan, nan
FAILED → Gustaf III Airport, Saint Barthélemy

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Richard+B.+Russell+Regional+Airport%2C+Rome%2C+Georgia%2C+United+States+of+America&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Richard+B.+Russell+Regional+Airport%2C+Rome%2C+Georgia%2C+United+States+of+America&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Richard B. Russell Regional Airport, Rome, Georgia, United States of America',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Richard+B.+Russell+Regional+Airport%2C+Rome%2C+Georgia%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Richard+B.+Russell+Regional+Airport%2C+Rome%2C+Georgia%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Richard+B.+Russell+Regional+Airport%2C+Rome%2C+Georgia%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

FAILED → Richard B. Russell Regional Airport, Rome, Georgia, United States of America
FAILED → Hacienda La Palmira, Pastaza Province, Ecuador
CACHE HIT → Jinnah International Airport, Karachi, Pakistan → 24.9058248, 67.1614489
SUCCESS → Hermes Quijada International Airport, Río Grande, Argentina → -53.778789, -67.7466527
CACHE HIT → Nursultan Nazarbayev International Airport, Kazakhstan → 51.0258535, 71.4641981
CACHE HIT → General Guadalupe Victoria International Airport, Durango, Mexico → 24.126948, -104.5287122
CACHE HIT → Halim Perdanakusuma International Airport, Jakarta, Indonesia → nan, nan
CACHE HIT → Halim Perdanakusuma International Airport, Jakarta, Indonesia → nan, nan
CACHE HIT → Geneva Airport (Cointrin), Switzerland → 46.2378164, 6.1081212
FAILED → Maryevka, Pestravsky District, Samara Oblast, Russia
CACHE HIT → Terravista Airport, Porto Seguro, Bahia, Brazil → -16.5352992, -39.1133771
CACHE HIT → Mariscal Lamar International Airport, Cuenca, Ecuador → nan, nan
FAILED → Devi Ahilya Bai Holkar Airport, Indore, India
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
FAILED → Egyptian Mediterranean Coast, Egypt
FAILED → J. R. Alison Municipal Airport, Gainesville, Florida, United States of America
CACHE HIT → Incheon International Airport, Seoul, South Korea → 37.5879876, 126.8264828
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
SUCCESS → Adolfo Suárez Madrid–Barajas Airport, Madrid, Spain → 40.4952269, -3.5733733
CACHE HIT → Jorge Chávez International Airport, Lima, Peru → -12.019515, -77.1183731
CACHE HIT → Goma International Airport, Goma, Democratic Republic of the Congo → -1.6648635, 29.2381116
CACHE HIT → Dervenochoria, Boeotia, Greece → nan, nan
CACHE HIT → Changi International Airport, Singapore → nan, nan
SUCCESS → Novopokrovskoye, Balashovsky District, Saratov Oblast, Russia → 51.572132, 43.602871
FAILED → Rybny Uyan, Kachugsky District, Irkutsk Oblast, Russia
SUCCESS → Fernando Luis Ribas Dominicci Airport, San Juan, Puerto Rico → 18.4564326, -66.1003366
CACHE HIT → Mountain Air Airport, Burnsville, North Carolina, United States of America → nan, nan
CACHE HIT → Bay of Bengal → 14.2202702, 86.7428454
CACHE HIT → Sugar Land Regional Airport, Houston, Texas, United States of America → nan, nan
CACHE HIT → Colorado Springs Airport, Colorado, United States of America → 38.8004299, -104.7032771
FAILED → Zelenogorsky, Kemerovo Oblast, Russia
CACHE HIT → Ajaccio – Napoléon Bonaparte Airport, Corsica, France → nan, nan
FAILED → Owen Roberts International Airport, Grand Cayman, Cayman Islands
CACHE HIT → Incheon International Airport, Seoul, South Korea → 37.5879876, 126.8264828
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
SUCCESS → Polyarny Airport, Yakutia, Russia → 66.4005807, 112.0328741
FAILED → Río Meta region, Apure, Venezuela
CACHE HIT → Óscar Machado Zuloaga International Airport, Charallave, Venezuela → nan, nan
SUCCESS → Alykel Airport, Norilsk, Russia → 69.3087924, 87.3146752
CACHE HIT → Incheon International Airport, Seoul, South Korea → 37.5879876, 126.8264828
SUCCESS → St. John's, Newfoundland and Labrador, Canada → 47.5646794, -52.7066964
CACHE HIT → Kamina, Democratic Republic of the Congo → -8.7351826, 25.0032201
CACHE HIT → Marcel Marchant Airport (La Paloma), Puerto Montt, Chile → -41.454479, -72.9192955

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tatarskoye+Uraykino%2C+Ulyanovsk+Region%2C+Russia&format=json&limit=1

FAILED → Tatarskoye Uraykino, Ulyanovsk Region, Russia
FAILED → McKellar–Sipes Regional Airport, Jackson, Tennessee, United States of America
CACHE HIT → Fernando Luis Ribas Dominicci Airport, San Juan, Puerto Rico → 18.4564326, -66.1003366
CACHE HIT → Bray, Northern Cape, South Africa → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Spain&format=json&limit=1

SUCCESS → Spain → 39.3260685, -4.8379791
CACHE HIT → Bhairahawa Airport, Rupandehi, Nepal → 27.5039964, 83.4180211
CACHE HIT → Washington Dulles International Airport, Virginia, United States of America → 38.9522663, -77.4534849
CACHE HIT → Halim Perdanakusuma International Airport, Jakarta, Indonesia → nan, nan
CACHE HIT → Beni Airport, North Kivu, Democratic Republic of the Congo → 0.5094382, 29.4756911
CACHE HIT → Deadman's Cay Airport, Long Island, Bahamas → nan, nan
CACHE HIT → Taiwan Taoyuan International Airport, Taiwan → 25.0793175, 121.2345977
CACHE HIT → Berlin Tegel Airport (closed), Germany → nan, nan
CACHE HIT → Campo de Marte Airport, São Paulo, Brazil → -23.5093734, -46.6393378

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=North+Central+State+Airport%2C+Smithfield%2C+Rhode+Island%2C+United+States+of+America&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=North+Central+State+Airport%2C+Smithfield%2C+Rhode+Island%2C+United+States+of+America&format=json&limit=1

SUCCESS → North Central State Airport, Smithfield, Rhode Island, United States of America → 41.9219864, -71.4927732

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Canoas+Air+Base%2C+Porto+Alegre%2C+Rio+Grande+do+Sul%2C+Brazil&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Canoas+Air+Base%2C+Porto+Alegre%2C+Rio+Grande+do+Sul%2C+Brazil&format=json&limit=1

SUCCESS → Canoas Air Base, Porto Alegre, Rio Grande do Sul, Brazil → -29.9416412, -51.1456587
CACHE HIT → Aba Tenna Dejazmach Yilma International Airport, Dire Dawa, Ethiopia → 9.6251062, 41.8523848
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → El Dorado International Airport, Bogotá, Colombia → 4.7020946, -74.1477132
CACHE HIT → Clark Regional Airport, Jeffersonville, Indiana, United States of America → nan, nan
CACHE HIT → Ministro Pistarini International Airport, Buenos Aires, Argentina → -34.8168141, -58.5474234
CACHE HIT → Marcos A. Gelabert International Airport, Panama City, Panama → nan, nan
CACHE HIT → St. Louis Lambert International Airport, Missouri, United States of America → 38.7496273, -90.3704702
FAILED → Leo Wattimena Air Base, Morotai Island, Indonesia
CACHE HIT → José María Córdova International Airport, Rionegro/Medellín, Colombia → nan, nan
CACHE HIT → Cheddi Jagan International Airport, Georgetown, Guyana → nan, nan
CACHE HIT → Cheddi Jagan International Airport, Georgetown, Guyana → nan, nan
CACHE HIT → Lajes Air Base, Terceira Island, Azores, Portugal → nan, nan
CACHE HIT → Don Mueang International Airport, Bangkok, Thailand → 13.9122207, 100.6035314
SUCCESS → Mustang Beach Airport, Port Aransas, Texas, United States of America → 27.8092253, -97.0854233

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Saint-Fr%C3%A9d%C3%A9ric+Aerodrome%2C+Quebec%2C+Canada&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Saint-Fr%C3%A9d%C3%A9ric+Aerodrome%2C+Quebec%2C+Canada&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Saint-Frédéric Aerodrome, Quebec, Canada',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Saint-Fr%C3%A9d%C3%A9ric+Aerodrome%2C+Quebec%2C+Canada&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Saint-Fr%C3%A9d%C3%A9ric+Aerodrome%2C+Quebec%2C+Canada&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Saint-Fr%C3%A9d%C3%A9ric+Aerodrome%2C+Quebec%2C+Canada&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

FAILED → Saint-Frédéric Aerodrome, Quebec, Canada
CACHE HIT → Copenhagen Airport (Kastrup), Denmark → 55.6309113, 12.6492236
SUCCESS → Kadena Air Base, Okinawa, Japan → 26.3555999, 127.7675
SUCCESS → Germán Olano Airport, Puerto Carreño, Colombia → 6.1851127, -67.4926779
CACHE HIT → RMAF Butterworth, Penang, Malaysia → nan, nan
CACHE HIT → Chania International Airport (Ioannis Daskalogiannis), Crete, Greece → 35.5296433, 24.1480057
CACHE HIT → Achmad Yani International Airport, Semarang, Indonesia → nan, nan
CACHE HIT → Copenhagen Airport (Kastrup), Denmark → 55.6309113, 12.6492236
CACHE HIT → Copenhagen Airport (Kastrup), Denmark → 55.6309113, 12.6492236
CACHE HIT → Burke Lakefront Airport, Cleveland, Ohio, United States of America → 41.5188169, -81.6811324
SUCCESS → Babullah Airport, Ternate, Indonesia → 0.8311788, 127.3808746
CACHE HIT → Shabunda Airport, Democratic Republic of the Congo → -2.6897975, 27.3442817
CACHE HIT → Sasakwa Airstrip, Tanzania → nan, nan
SUCCESS → Toronto Pearson International Airport, Ontario, Canada → 43.6782236, -79.6288047
CACHE HIT → Toronto Pearson International Airport, Ontario, Canada → 43.6782236, -79.6288047
SUCCESS → Muscat, Oman → 23.6123628, 58.5938134
FAILED → Agro-West Airport, Five Points, California, United States of America
CACHE HIT → Manchester Airport, United Kingdom → 53.3503421, -2.2803693
CACHE HIT → Manas International Airport, Bishkek, Kyrgyzstan → nan, nan
SUCCESS → Livingston County Spencer J. Hardy Airport, Howell, Michigan, United States of America → 42.628979, -83.9840645
CACHE HIT → Durango–La Plata County Airport, Colorado, United States of America → 37.1528424, -107.7586059
CACHE HIT → Palm Beach International Airport, Florida, United States of America → 26.6859478, -80.0924865
CACHE HIT → Alfredo Vásquez Cobo International Airport, Leticia, Colombia → nan, nan
CACHE HIT → Grand Bahama International Airport, Freeport, Bahamas → 26.5565128, -78.6955864
CACHE HIT → Thebephatshwa Air Base, Botswana → nan, nan
FAILED → Illertissen Airfield, Bavaria, Germany
SUCCESS → Essendon Fields Airport, Melbourne, Victoria, Australia → -37.7266099, 144.901318
CACHE HIT → Amsterdam Airport Schiphol, Netherlands → 52.3269801, 4.7415053
CACHE HIT → Isle of Man Airport (Ronaldsway), Isle of Man → nan, nan
SUCCESS → Salzburg Airport W. A. Mozart, Austria → 47.7934551, 13.0018306
CACHE HIT → General Francisco de Miranda Air Base (La Carlota), Caracas, Venezuela → nan, nan
CACHE HIT → Muwaffaq Salti Air Base, Azraq, Jordan → 31.8205079, 36.7794153
CACHE HIT → Willow Run Airport, Michigan, United States of America → 42.2349279, -83.5260502
FAILED → Yalowega Lake, Saskatchewan, Canada
CACHE HIT → Coari Airport, Amazonas, Brazil → -4.133102, -63.1297312
SUCCESS → Francisco Carlé Airport, Jauja, Peru → -11.7835899, -75.4734237
CACHE HIT → Salzburg Airport W. A. Mozart, Austria → 47.7934551, 13.0018306
FAILED → Kopinang Airstrip, Guyana
SUCCESS → Lanyu Airport, Orchid Island, Taiwan → 22.0287171, 121.5337005
CACHE HIT → Yeager Airport, Charleston, West Virginia, United States of America → 38.3729476, -81.5942197
CACHE HIT → Assabu, Hokkaido, Japan → 41.9204033, 140.2254631
CACHE HIT → Tenzing-Hillary Airport, Lukla, Nepal → 27.6866013, 86.7291582
CACHE HIT → Balashov Air Base, Saratov Oblast, Russia → 51.5362116, 43.2997763
CACHE HIT → Rendani Airport, Manokwari, Indonesia → -0.8909731, 134.0491786
CACHE HIT → Pattimura Airport, Ambon, Indonesia → -3.7111152, 128.0878877
SUCCESS → General Francisco Javier Mina International Airport, Tampico, Mexico → 22.2906699, -97.8641237
SUCCESS → Chinggis Khaan International Airport, Ulaanbaatar, Mongolia → 47.8429763, 106.7667562
SUCCESS → Tarapacá Airport, Colombia → -2.8958053, -69.7497586
CACHE HIT → Nancova Airstrip, Angola → nan, nan
CACHE HIT → Hartsfield–Jackson Atlanta International Airport, Georgia, United States of America → 33.6374009, -84.4298161
CACHE HIT → Ben Gurion International Airport, Tel Aviv, Israel → nan, nan
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Teniente+Luis+Candelaria+International+Airport%2C+San+Carlos+de+Bariloche%2C+Argentina&format=json&limit=1

FAILED → Teniente Luis Candelaria International Airport, San Carlos de Bariloche, Argentina
SUCCESS → East River, New York City, New York, United States of America → 40.7996481, -73.8432294
CACHE HIT → Eteringbang Airport, Guyana → nan, nan
FAILED → Mykonos International Airport, Greece
CACHE HIT → São Tomé International Airport, São Tomé and Príncipe → 0.3773992, 6.7148853

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Mulino+State+Airport%2C+Oregon%2C+United+States+of+America&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Mulino+State+Airport%2C+Oregon%2C+United+States+of+America&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Mulino State Airport, Oregon, United States of America',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Mulino+State+Airport%2C+Oregon%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Mulino+State+Airport%2C+Oregon%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Mulino+State+Airport%2C+Oregon%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

FAILED → Mulino State Airport, Oregon, United States of America
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
FAILED → Coronel FAP Francisco Secada Vignetta International Airport, Iquitos, Peru
CACHE HIT → Palmerola International Airport (Palmerola Air Base), Comayagua, Honduras → nan, nan
FAILED → Unnamed temporary landing zone, Iraq
SUCCESS → Yeniseysk, Krasnoyarsk Krai, Russia → 58.4532212, 92.1748169
CACHE HIT → Maban Airstrip, South Sudan → nan, nan
FAILED → Turinskaya Sloboda, Sverdlovsk Oblast, Russia
CACHE HIT → Wilmington Airport (ILG), Delaware, United States of America → nan, nan
CACHE HIT → Princess Juliana International Airport, Sint Maarten → 18.0408739, -63.1118517
CACHE HIT → Goma International Airport, Goma, Democratic Republic of the Congo → -1.6648635, 29.2381116
SUCCESS → Adelaide Airport, South Australia, Australia → -34.9472404, 138.5330688
CACHE HIT → Grantley Adams International Airport, Bridgetown, Barbados → nan, nan
CACHE HIT → Istanbul Atatürk Airport, Turkey → 40.9782389, 28.8263208
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
CACHE HIT → Ronald Reagan Washington National Airport, Virginia, United States of America → 38.8512895, -77.0396889
CACHE HIT → Ronald Reagan Washington National Airport, Virginia, United States of America → 38.8512895, -77.0396889
SUCCESS → Manuel Prado Ugarteche Airport, Mazamari, Peru → -11.3263308, -74.5353368
CACHE HIT → Xuddur Airport, Somalia → nan, nan
CACHE HIT → Athens International Airport Eleftherios Venizelos, Greece → nan, nan
CACHE HIT → Sydney Kingsford Smith International Airport, New South Wales, Australia → nan, nan
CACHE HIT → Félix-Houphouët-Boigny International Airport, Côte d'Ivoire → 5.2649283, -3.9259573
CACHE HIT → Hawarden Airport, Flintshire, United Kingdom → 53.1796073, -2.972866
FAILED → Anavilhanas National Park, Amazon River (Rio Negro), Amazonas, Brazil
CACHE HIT → Alicante–Elche Miguel Hernández Airport, Spain → 38.2875648, -0.5527807
CACHE HIT → Ted Stevens Anchorage International Airport, Alaska, United States of America → 61.1810353, -149.9978919
FAILED → Lobo Wildlife Lodge Airstrip, Serengeti, Tanzania
CACHE HIT → Akron–Canton Airport, Ohio, United States of America → 40.9152061, -81.4399242
FAILED → Flight route between Toronto and London over the Atlantic Ocean
SUCCESS → Ekimchan, Amur Oblast, Russia → 53.068481, 132.940369
CACHE HIT → Billy Bishop Toronto City Airport, Ontario, Canada → 43.6280558, -79.3979969
SUCCESS → Empakaai Crater, Tanzania → -2.9091907, 35.8279461
SUCCESS → Toulouse–Blagnac Airport, France → 43.629978, 1.3608099
SUCCESS → Rand Airport, Germiston, South Africa → -26.237195, 28.1584722
SUCCESS → Okinawa, Japan → 26.5707754, 128.0255901
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → Changi International Airport, Singapore → nan, nan
CACHE HIT → Jersey Airport, Channel Islands → nan, nan
CACHE HIT → Toronto Pearson International Airport, Ontario, Canada → 43.6782236, -79.6288047
CACHE HIT → Simón Bolívar International Airport, Caracas, Venezuela → nan, nan
CACHE HIT → Hamad International Airport, Doha, Qatar → 25.2748602, 51.6124512
FAILED → Flight route between Anchorage and Bethel, Alaska, United States of America
CACHE HIT → Dinangat Village, Morobe Province, Papua New Guinea → nan, nan
CACHE HIT → Toronto Pearson International Airport, Ontario, Canada → 43.6782236, -79.6288047
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → Warsaw Frederic Chopin Airport, Poland → 52.1630651, 20.9708149

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Bicol+International+Airport%2C+Daraga%2C+Albay%2C+Philippines&format=json&limit=1

SUCCESS → Bicol International Airport, Daraga, Albay, Philippines → 13.1129993, 123.6795211

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Southwest+Wyoming+Regional+Airport%2C+Rock+Springs%2C+Wyoming%2C+United+States+of+America&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Southwest+Wyoming+Regional+Airport%2C+Rock+Springs%2C+Wyoming%2C+United+States+of+America&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Southwest Wyoming Regional Airport, Rock Springs, Wyoming, United States of America',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Southwest+Wyoming+Regional+Airport%2C+Rock+Springs%2C+Wyoming%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Southwest+Wyoming+Regional+Airport%2C+Rock+Springs%2C+Wyoming%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Southwest+Wyoming+Regional+Airport%2C+Rock+Springs%2C+Wyoming%2C+United+States+of+America&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

SUCCESS → Southwest Wyoming Regional Airport, Rock Springs, Wyoming, United States of America → 41.5950759, -109.0684214
SUCCESS → Trabzon Airport, Türkiye → 40.9944424, 39.7890385
CACHE HIT → Mitiga International Airport, Tripoli, Libya → 32.8951353, 13.2809484
CACHE HIT → Zhetygen Air Base, Kazakhstan → nan, nan
FAILED → Mwanza International Airport, Tanzania
FAILED → Hodulluca, Yalvaç District, Turkey
CACHE HIT → Berlin Brandenburg Airport, Germany → 52.3659284, 13.4886435
CACHE HIT → Nnamdi Azikiwe International Airport, Nigeria → 9.0207137, 7.2677714
CACHE HIT → Zhengchang, Suiyang County, Guizhou Province, China → nan, nan
CACHE HIT → Sydney Kingsford Smith International Airport, New South Wales, Australia → nan, nan
CACHE HIT → Burke Lakefront Airport, Cleveland, Ohio, United States of America → 41.5188169, -81.6811324
CACHE HIT → Spain (Canaries airspace) → nan, nan
FAILED → Stepanovskoye, Ramenskoye District, Russia
CACHE HIT → Murtala Muhammed International Airport, Lagos, Nigeria → nan, nan
CACHE HIT → Óscar Machado Zuloaga International Airport, Charallave, Venezuela → nan, nan
CACHE HIT → Lubumbashi International Airport, Democratic Republic of the Congo → -11.5926492, 27.5259188
SUCCESS → Khmeimim Air Base, Latakia Governorate, Syria → 35.4119739, 35.954477
SUCCESS → Shahr-e Kord, Iran → 32.3257366, 50.8497369
CACHE HIT → Montréal–Pierre Elliott Trudeau International Airport, Quebec, Canada → nan, nan
CACHE HIT → Ben Gurion International Airport, Tel Aviv, Israel → nan, nan
CACHE HIT → Ben Gurion International Airport, Tel Aviv, Israel → nan, nan
FAILED → Capitán Av. Selin Zeitun Lopez Airport, Riberalta, Bolivia
CACHE HIT → Benito Juárez International Airport, Mexico City, Mexico → 19.4342349, -99.0733121
CACHE HIT → Benito Juárez International Airport, Mexico City, Mexico → 19.4342349, -99.0733121
SUCCESS → Orlando Sanford International Airport, Florida, United States of America → 28.7759519, -81.241239
CACHE HIT → William P. Hobby Airport, Houston, Texas, United States of America → 29.6471491, -95.2769303
CACHE HIT → William P. Hobby Airport, Houston, Texas, United States of America → 29.6471491, -95.2769303
CACHE HIT → William P. Hobby Airport, Houston, Texas, United States of America → 29.6471491, -95.2769303
CACHE HIT → William P. Hobby Airport, Houston, Texas, United States of America → 29.6471491, -95.2769303
CACHE HIT → William P. Hobby Airport, Houston, Texas, United States of America → 29.6471491, -95.2769303
CACHE HIT → Boufarik Air Base, Blida Province, Algeria → nan, nan
SUCCESS → El Barde, Somalia → 4.6737132, 43.9148358
CACHE HIT → Zhengzhou Xinzheng International Airport, China → nan, nan
CACHE HIT → Hartsfield–Jackson Atlanta International Airport, Georgia, United States of America → 33.6374009, -84.4298161
SUCCESS → Eperjes, Hungary → 46.7100842, 20.5609031
CACHE HIT → Jalaluddin Airport, Gorontalo, Indonesia → 0.6378751, 122.8443144
CACHE HIT → Sharara Airstrip, Libya → nan, nan
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → John F. Kennedy International Airport, New York, United States of America → 40.6429479, -73.7793734
CACHE HIT → Rand Airport, Germiston, South Africa → -26.237195, 28.1584722
CACHE HIT → Santiago de Compostela Airport, Spain → nan, nan
FAILED → Gavião Peixoto Airport (Embraer Unidade), São Paulo, Brazil
CACHE HIT → Jacksons International Airport, Port Moresby, Papua New Guinea → -9.4402674, 147.2171286
CACHE HIT → Jacksons International Airport, Port Moresby, Papua New Guinea → -9.4402674, 147.2171286
CACHE HIT → Istanbul Atatürk Airport, Turkey → 40.9782389, 28.8263208
CACHE HIT → Istanbul Atatürk Airport, Turkey → 40.9782389, 28.8263208
CACHE HIT → Bahun Khark, Nepal → nan, nan
CACHE HIT → José Martí International Airport, Havana, Cuba → 22.9873849, -82.4142531
CACHE HIT → Yangzhou Taizhou International Airport, China → nan, nan
CACHE HIT → King Abdulaziz International Airport, Jeddah, Saudi Arabia → 21.6585157, 39.1746303
CACHE HIT → Toncontín International Airport, Tegucigalpa, Honduras → 14.0576, -87.2163832
CACHE HIT → Aeroclube de Flores Airport, Manaus, Amazonas, Brazil → nan, nan
SUCCESS → Kolwezi Airport, Democratic Republic of the Congo → -10.7668668, 25.5094762
CACHE HIT → Kolwezi Airport, Democratic Republic of the Congo → -10.7668668, 25.5094762
CACHE HIT → Plan de Guadalupe International Airport, Saltillo, Mexico → nan, nan
CACHE HIT → Obo Mission Airstrip, Central African Republic → nan, nan
SUCCESS → Kamonia Airstrip, Democratic Republic of the Congo → -6.8702139, 20.9159079
CACHE HIT → Baleni, Galați County, Romania → nan, nan
FAILED → La Môle – Saint-Tropez Airport, France
CACHE HIT → Heraklion International Airport (Nikos Kazantzakis), Crete, Greece → 35.337058, 25.180972
CACHE HIT → Marcos A. Gelabert International Airport, Panama City, Panama → nan, nan
CACHE HIT → Beaver Island Airstrip, Falkland Islands → nan, nan
SUCCESS → Igor Sikorsky Kyiv International Airport, Ukraine → 50.4067304, 30.4444678
CACHE HIT → John Glenn Columbus International Airport, Columbus, Ohio, United States of America → 39.9970561, -82.8930477
FAILED → Kenyam Airstrip, Papua, Indonesia
CACHE HIT → Kenyam Airstrip, Papua, Indonesia → nan, nan
SUCCESS → Gimpo International Airport, Seoul, South Korea → 37.5677212, 126.8050268
CACHE HIT → Gimpo International Airport, Seoul, South Korea → 37.5677212, 126.8050268
SUCCESS → Nizhneudinsk, Irkutsk Oblast, Russia → 54.9024925, 99.0289558
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
CACHE HIT → Padek Airstrip, South Sudan → nan, nan
FAILED → Fès–Saïs Airport, Morocco
CACHE HIT → Cherif Al Idrissi Airport, Al Hoceïma, Morocco → 35.1771077, -3.8394796
FAILED → Wonderboom National Airport, Pretoria, South Africa
CACHE HIT → Tancredo Neves International Airport, Belo Horizonte, Brazil → -19.6367633, -43.9621429
CACHE HIT → Mayor Carlos Eduardo Krause Airport, Puerto Iguazú, Argentina → nan, nan
CACHE HIT → Burnet Municipal Airport (Kate Craddock Field), Texas, United States of America → 30.7399655, -98.2371136
SUCCESS → Kamako Airstrip, Democratic Republic of the Congo → -6.8702139, 20.9159079
SUCCESS → Bauerfield International Airport, Port Vila, Vanuatu → -17.6991308, 168.3193166
CACHE HIT → Bauerfield International Airport, Port Vila, Vanuatu → -17.6991308, 168.3193166
CACHE HIT → Bauerfield International Airport, Port Vila, Vanuatu → -17.6991308, 168.3193166
SUCCESS → Evenkiysky District, Krasnoyarsk Krai, Russia → 66.4414806, 94.2299248
CACHE HIT → General Guadalupe Victoria International Airport, Durango, Mexico → 24.126948, -104.5287122
CACHE HIT → Wilmington International Airport (ILM), North Carolina, United States of America → nan, nan
CACHE HIT → Istanbul Atatürk Airport, Turkey → 40.9782389, 28.8263208
CACHE HIT → Istanbul Atatürk Airport, Turkey → 40.9782389, 28.8263208
CACHE HIT → Ninoy Aquino International Airport, Manila, Philippines → 14.5123016, 121.0218861
CACHE HIT → Jorge Chávez International Airport, Lima, Peru → -12.019515, -77.1183731
FAILED → Gera-Leumnitz Airfield, Thuringia, Germany
CACHE HIT → Cape Hatteras, North Carolina, United States of America → 35.2252064, -75.5279144
CACHE HIT → Pieri Airstrip, South Sudan → nan, nan
SUCCESS → San Vicente del Caguán, Colombia → 2.1131213, -74.7697347
CACHE HIT → Burgas Airport, Bulgaria → 42.5702209, 27.5169873
CACHE HIT → Yirol Airstrip, South Sudan → nan, nan
SUCCESS → Sir Seewoosagur Ramgoolam International Airport, Mauritius → -20.4325615, 57.6849489
CACHE HIT → Khmeimim Air Base, Latakia Governorate, Syria → 35.4119739, 35.954477
CACHE HIT → Don Mueang International Airport, Bangkok, Thailand → 13.9122207, 100.6035314
CACHE HIT → Foz do Iguaçu/Cataratas International Airport, Paraná, Brazil → nan, nan
SUCCESS → Sendai, Japan → 38.2677554, 140.8691498
CACHE HIT → Chuuk International Airport (Weno Airport), Federated States of Micronesia → nan, nan
CACHE HIT → Beoga Airport, Papua, Indonesia → -3.8169022, 137.4254662
CACHE HIT → Murtala Muhammed International Airport, Lagos, Nigeria → nan, nan
FAILED → Tiruchirappalli International Airport, India
CACHE HIT → Tanjung Bungin, Indonesia → nan, nan
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
CACHE HIT → Charles de Gaulle Airport, Paris, France → nan, nan
CACHE HIT → Talagi Airport, Arkhangelsk, Russia → 64.599209, 40.7186047
CACHE HIT → PAF Base Nur Khan (Chaklala Airbase), Rawalpindi, Pakistan → nan, nan
CACHE HIT → Cheddi Jagan International Airport, Georgetown, Guyana → nan, nan
FAILED → Barrow County Airport, Winder, Georgia, United States of America
CACHE HIT → José Celestino Mutis Airport, Bahía Solano, Colombia → 6.2030693, -77.3952435
CACHE HIT → Stephenville International Airport, Newfoundland and Labrador, Canada → nan, nan
CACHE HIT → El Alto International Airport, La Paz, Bolivia → -16.5122206, -68.190261
CACHE HIT → Curaçao → 12.1176488, -68.9309263
CACHE HIT → Jinnah International Airport, Karachi, Pakistan → 24.9058248, 67.1614489
FAILED → Fazenda Fortaleza de Santa Terezinha Airport, Jequitaí, Minas Gerais, Brazil
SUCCESS → Hector International Airport, Fargo, North Dakota, United States of America → 46.9208925, -96.814488
CACHE HIT → LaGuardia Airport, New York, United States of America → 40.7757145, -73.873364
CACHE HIT → Ben Gurion International Airport, Tel Aviv, Israel → nan, nan
CACHE HIT → O'Hare International Airport, Chicago, Illinois, United States of America → 41.9782523, -87.9092355
SUCCESS → Osaka, Japan → 34.6937569, 135.5014539
CACHE HIT → Athens International Airport Eleftherios Venizelos, Greece → nan, nan
SUCCESS → Cape Muroto, Japan → 33.2435799, 134.1768342
CACHE HIT → Corozo, Sarstún River region, Guatemala → nan, nan
CACHE HIT → Benito Juárez International Airport, Mexico City, Mexico → 19.4342349, -99.0733121
CACHE HIT → Hong Kong International Airport (Chek Lap Kok), Hong Kong → 22.3125986, 113.9172999
CACHE HIT → São Tomé International Airport, São Tomé and Príncipe → 0.3773992, 6.7148853
CACHE HIT → N'Djili International Airport, Kinshasa, Democratic Republic of the Congo → nan, nan
CACHE HIT → Kamarata Airport, Venezuela → nan, nan
CACHE HIT → Beni Airport, North Kivu, Democratic Republic of the Congo → 0.5094382, 29.4756911
CACHE HIT → Murtala Muhammed International Airport, Lagos, Nigeria → nan, nan
CACHE HIT → Murtala Muhammed International Airport, Lagos, Nigeria → nan, nan

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Kirksville+Regional+Airport%2C+Missouri%2C+United+States+of+America&format=json&limit=1

SUCCESS → Kirksville Regional Airport, Missouri, United States of America → 40.0924817, -92.5432908
CACHE HIT → Lubumbashi International Airport, Democratic Republic of the Congo → -11.5926492, 27.5259188
CACHE HIT → Benito Juárez International Airport, Mexico City, Mexico → 19.4342349, -99.0733121

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tezpur+Air+Force+Station%2C+Assam%2C+India&format=json&limit=1

SUCCESS → Tezpur Air Force Station, Assam, India → 26.7139851, 92.7855981

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Hastings+Airport%2C+Freetown%2C+Sierra+Leone&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Hastings+Airport%2C+Freetown%2C+Sierra+Leone&format=json&limit=1
WARNING:geopy:RateLimiter caught an error, retrying (0/2 tries). Called with (*('Hastings Airport, Freetown, Sierra Leone',), **{}).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Hastings+Airport%2C+Freetown%2C+Sierra+Leone&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Hastings+Airport%2C+Freetown%2C+Sierra+Leone&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Hastings+Airport%2C+Freetown%2C+Sierra+Leone&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

FAILED → Hastings Airport, Freetown, Sierra Leone
CACHE HIT → Wadi Bu al Hashm, Libya → nan, nan
CACHE HIT → El Dorado International Airport, Bogotá, Colombia → 4.7020946, -74.1477132
CACHE HIT → Alek Airstrip, South Sudan → nan, nan
CACHE HIT → Mano Dayak International Airport, Agadez, Niger → 16.9709219, 8.0140235
CACHE HIT → Mano Dayak International Airport, Agadez, Niger → 16.9709219, 8.0140235
CACHE HIT → Bunia Airport, Democratic Republic of the Congo → 1.5666587, 30.2172709
CACHE HIT → Simón Bolívar International Airport, Caracas, Venezuela → nan, nan
CACHE HIT → Zarafshan Airport, Uzbekistan → nan, nan
CACHE HIT → Sidra Airport, Libya → 30.6449322, 18.3190161
CACHE HIT → Shabunda Airport, Democratic Republic of the Congo → -2.6897975, 27.3442817
CACHE HIT → José Martí International Airport, Havana, Cuba → 22.9873849, -82.4142531

In [ ]:
failed_df = new_df_copy[new_df_copy["GeoStatus"] == "FAILED"]
success_df = new_df_copy[new_df_copy["GeoStatus"] == "SUCCESS"]
skipped_df = new_df_copy[new_df_copy["GeoStatus"] == "SKIPPED"]
error_df = new_df_copy[new_df_copy["GeoStatus"] == "ERROR"]

print(len(failed_df))
print(len(success_df))
print(len(skipped_df))
print(len(error_df))

807
4471
0
0

In [ ]:
new_df_copy.head()

,Unnamed: 0,Event_No,Incident_Date,Year,Time,Aircaft_Damage_Type,Aircraft_Phase,Incident_Location,Aircaft_Nature,Aircaft_Registration,...,Dest_Lat,Dest_Lon,Incident,raw_place,country,place_clean,geopy_query,Latitude,Longitude,GeoStatus
0,0,1,2000-01-01,2000,13:00 LT,Substantial,Unknown,"HOMESTEAD, Florida - United States of America",Ferry/Positioning,N752CC,...,26.17100,56.24060,Accident,"HOMESTEAD, Florida",United States of America,"HOMESTEAD, Florida","HOMESTEAD, Florida, United States of America",25.471895,-80.475990,SUCCESS
1,1,2,2000-01-03,2000,NaN,Destroyed,Unknown,unknown location - Unknown country,Unknown,A2-AEZ,...,NaN,NaN,Unknown,unknown location,Unknown country,unknown location,unknown location,-0.999945,36.741661,SUCCESS
2,2,3,2000-01-04,2000,17:25 LT,Substantial,Unknown,"JACKSON, Wyoming - United States of America",Private,N895TT,...,56.17290,92.49330,Accident,"JACKSON, Wyoming",United States of America,"JACKSON, Wyoming","JACKSON, Wyoming, United States of America",43.479965,-110.761815,SUCCESS
3,3,4,2000-01-05,2000,13:25,Destroyed,Approach,Abuja International Airport (ABV) - Nigeria,Passenger,5N-AXL,...,9.00679,7.26317,Accident,Abuja International Airport (ABV),Nigeria,Abuja International Airport,"Nnamdi Azikiwe International Airport, Nigeria",9.020714,7.267771,SUCCESS
4,4,5,2000-01-07,2000,NaN,Missing,Unknown,- Angola,Cargo,D2-FBR,...,-8.78361,17.98970,Accident,- Angola,NaN,Angola,Angola,-11.877577,17.569124,SUCCESS

In [ ]:
new_df_copy.to_csv('new_clean_aircraft_data_with_lat_lon_incident_with_failures.csv')

## NLP to extract keywords regarding incident nature - for analytics

In [ ]:
# this code is working. but try better prompts --- cause the current ones are pretty bad

In [ ]:
import pandas as pd
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

True
NVIDIA A100-SXM4-80GB

In [ ]:
url = "https://raw.githubusercontent.com/oshani-jayawardane/aircraft-accident-project/main/cleanest_df_with_NLP.csv"
clean_df = pd.read_csv(url)

clean_df.head()

,Unnamed: 0.1,Unnamed: 0,Event_No,Incident_Date,Year,Time,Incident,Aircaft_Damage_Type,Aircraft_Phase,Occupants,...,is_model_cause,is_human_cause,is_weather_cause,is_wildlife_cause,is_ground_collision,is_unknown_cause,damage_area,cause,name,is_cause
0,0,0,1,2000-01-01,2000,13:00 LT,Accident,Substantial,Unknown,3.0,...,0.0,0.0,0.0,1.0,0.0,0.0,['right wing leading edge'],NaN,NaN,NaN
1,1,1,2,2000-01-03,2000,NaN,Unknown,Destroyed,Unknown,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,[],NaN,NaN,NaN
2,2,2,3,2000-01-04,2000,17:25 LT,Accident,Substantial,Unknown,3.0,...,0.0,1.0,1.0,0.0,1.0,0.0,['nose landing gear'],NaN,NaN,NaN
3,3,3,4,2000-01-05,2000,13:25,Accident,Destroyed,Approach,13.0,...,0.0,0.0,0.0,0.0,1.0,0.0,['farmland'],NaN,NaN,NaN
4,4,4,5,2000-01-07,2000,NaN,Accident,Missing,Unknown,8.0,...,0.0,0.0,0.0,0.0,0.0,1.0,[],NaN,NaN,NaN

In [ ]:
clean_df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Event_No', 'Incident_Date', 'Year',
       'Time', 'Incident', 'Aircaft_Damage_Type', 'Aircraft_Phase',
       'Occupants', 'Fatalities', 'Ground_Casualties', 'Collision_Casualties',
       'Incident_Location', 'geopy_query', 'Latitude', 'Longitude',
       'GeoStatus', 'Aircaft_Nature', 'Aircaft_Registration', 'Aircaft_Model',
       'Aircaft_Operator', 'Engine_Model', 'Departure_Airport',
       'Destination_Airport', 'Departure_Airport_Code',
       'Destination_Airport_Code', 'Departure_IATA', 'Destination_IATA',
       'Dep_Lat', 'Dep_Lon', 'Dest_Lat', 'Dest_Lon',
       'Aircraft_Manufacture_Year', 'Total_Flight_Hours', 'Confidence_Rating',
       'Narrative', 'Incident_Cause(es)', 'is_engine_cause', 'is_model_cause',
       'is_human_cause', 'is_weather_cause', 'is_wildlife_cause',
       'is_ground_collision', 'is_unknown_cause', 'damage_area', 'cause',
       'name', 'is_cause'],
      dtype='object')

In [ ]:
clean_df.iloc[3344:3352]

,Unnamed: 0.1,Unnamed: 0,Event_No,Incident_Date,Year,Time,Incident,Aircaft_Damage_Type,Aircraft_Phase,Occupants,...,is_model_cause,is_human_cause,is_weather_cause,is_wildlife_cause,is_ground_collision,is_unknown_cause,damage_area,cause,name,is_cause
3344,3344,3344,3393,2011-08-25,2011,NaN,Criminal,Destroyed,Standing,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,['lower fuselage'],NaN,NaN,NaN
3345,3345,3345,3394,2011-08-26,2011,NaN,Hijacking,Destroyed,Standing,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,[],NaN,NaN,NaN
3346,3346,3346,3395,2011-08-28,2011,08:54,Accident,Destroyed,Maneuvering,2.0,...,0.0,1.0,0.0,0.0,1.0,0.0,['fuselage'],NaN,NaN,NaN
3347,3347,3347,3396,2011-08-29,2011,03:54,Accident,Repairable,Landing,143.0,...,0.0,1.0,1.0,0.0,1.0,0.0,['nose gear'],NaN,NaN,NaN
3348,3348,3348,3397,2011-08-31,2011,NaN,Accident,Substantial,Landing,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3349,3349,3349,3398,2011-09-02,2011,17:48,Accident,Destroyed,Approach,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3350,3350,3350,3399,2011-09-02,2011,13:35,Accident,Destroyed,En Route,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3351,3351,3351,3400,2011-09-03,2011,12:00,Accident,Destroyed,Maneuvering,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
start_idx = 3348   # first row that needs NLP

processed_df = clean_df.iloc[:start_idx].reset_index(drop=True)      # 0..3347
new_df_source = clean_df.iloc[start_idx:].reset_index(drop=True)     # 3348..end

processed_df.head()

,Unnamed: 0.1,Unnamed: 0,Event_No,Incident_Date,Year,Time,Incident,Aircaft_Damage_Type,Aircraft_Phase,Occupants,...,is_model_cause,is_human_cause,is_weather_cause,is_wildlife_cause,is_ground_collision,is_unknown_cause,damage_area,cause,name,is_cause
0,0,0,1,2000-01-01,2000,13:00 LT,Accident,Substantial,Unknown,3.0,...,0.0,0.0,0.0,1.0,0.0,0.0,['right wing leading edge'],NaN,NaN,NaN
1,1,1,2,2000-01-03,2000,NaN,Unknown,Destroyed,Unknown,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,[],NaN,NaN,NaN
2,2,2,3,2000-01-04,2000,17:25 LT,Accident,Substantial,Unknown,3.0,...,0.0,1.0,1.0,0.0,1.0,0.0,['nose landing gear'],NaN,NaN,NaN
3,3,3,4,2000-01-05,2000,13:25,Accident,Destroyed,Approach,13.0,...,0.0,0.0,0.0,0.0,1.0,0.0,['farmland'],NaN,NaN,NaN
4,4,4,5,2000-01-07,2000,NaN,Accident,Missing,Unknown,8.0,...,0.0,0.0,0.0,0.0,0.0,1.0,[],NaN,NaN,NaN

In [ ]:
new_df_source.head()

,Unnamed: 0.1,Unnamed: 0,Event_No,Incident_Date,Year,Time,Incident,Aircaft_Damage_Type,Aircraft_Phase,Occupants,...,is_model_cause,is_human_cause,is_weather_cause,is_wildlife_cause,is_ground_collision,is_unknown_cause,damage_area,cause,name,is_cause
0,3348,3348,3397,2011-08-31,2011,NaN,Accident,Substantial,Landing,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3349,3349,3398,2011-09-02,2011,17:48,Accident,Destroyed,Approach,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3350,3350,3399,2011-09-02,2011,13:35,Accident,Destroyed,En Route,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3351,3351,3400,2011-09-03,2011,12:00,Accident,Destroyed,Maneuvering,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3352,3352,3401,2011-09-04,2011,15:29,Accident,Destroyed,Landing,47.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
!pip install -q transformers accelerate sentencepiece

In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
import pandas as pd
import json
import math
from tqdm.auto import tqdm

model_name = "mistralai/Mistral-7B-Instruct-v0.2"
# model_name = "google/flan-t5-large"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    dtype=torch.float16,
    device_map="auto"
)

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/596 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.94G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/4.54G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [ ]:
# Helper: build input text with narrative priority

def build_text(narrative, cause):
    # Handle NaNs / None
    narr = "" if narrative is None or (isinstance(narrative, float) and math.isnan(narrative)) else str(narrative).strip()
    cause_txt = "" if cause is None or (isinstance(cause, float) and math.isnan(cause)) else str(cause).strip()

    if not narr and not cause_txt:
        return None  # nothing to analyze

    # Narrative first, cause second (narrative has priority)
    text_parts = []
    if narr:
        text_parts.append(f"NARRATIVE:\n{narr}")
    if cause_txt:
        text_parts.append(f"INCIDENT_CAUSE_FIELD:\n{cause_txt}")

    return "\n\n".join(text_parts)

In [ ]:
def build_prompt(case_text):
    prompt = f"""
You are an aviation accident investigator.

Given the information below, decide which factors DIRECTLY CAUSED the accident.
Mentions that did NOT cause the accident must NOT be tagged as causes.
If the narrative and the incident cause field disagree, give MORE WEIGHT to the narrative.

You must answer ONLY in valid JSON (no extra text).

Definitions:
- is_engine_cause: 1 if an internal engine or propulsion system failure directly caused the accident.
- is_model_cause: 1 if a design flaw or known problem with the aircraft model directly caused the accident.
- is_human_cause: 1 if pilot, crew, or staff actions/decisions (carelessness, violation of procedure, etc.) directly caused the accident.
- is_weather_cause: 1 if weather or environmental conditions (storms, icing, turbulence, wind shear, etc.) directly caused the accident.
- is_wildlife_cause: 1 if a bird or animal strike directly caused the accident.
- is_ground_collision: 1 if collision with ground objects (vehicles, buildings, airport equipment, terrain, etc.) directly caused the accident.
- is_unknown_cause: 1 if the true cause cannot be determined from the text.

Multiple causes may be 1 at the same time if the text CLEARLY supports them ONLY.

Also extract:
- damage_area: list of STRUCTURAL aircraft parts that were DAMAGED (e.g. "left wing", "right wing", "fuselage", "wing leading edge", "landing gear", "engine", "engine #1", "propeller", "tail", "nose", "cockpit windows", "vertical stabilizer","horizontal stabilizer", "rudder", "elevator", and more).
  Look for keywords but ONLY list parts that are clearly damaged.

EXAMPLE 1
Text:
"A Cessna 172 lost power after an internal engine failure due to oil starvation and crashed short of the runway. The airplane sustained substantial damage to the nose and landing gear."
Answer:
{{
 "is_engine_cause": 1,
 "is_model_cause": 0,
 "is_human_cause": 0,
 "is_weather_cause": 0,
 "is_wildlife_cause": 0,
 "is_ground_collision": 0,
 "is_unknown_cause": 0,
 "damage_area": ["nose", "landing gear"]
}}

EXAMPLE 2
Text:
"The pilot continued an unstable approach at excessive speed, landed long, and overran the runway, collapsing the nose gear. No mechanical anomalies were reported with the airplane."
Answer:
{{
 "is_engine_cause": 0,
 "is_model_cause": 0,
 "is_human_cause": 1,
 "is_weather_cause": 0,
 "is_wildlife_cause": 0,
 "is_ground_collision": 1,
 "is_unknown_cause": 0,
 "damage_area": ["nose gear"]
}}

EXAMPLE 3
Text:
"The airplane struck a flock of birds during climb, resulting in dents and punctures to the right wing leading edge and engine inlet. The pilot returned for a precautionary landing."
Answer:
{{
 "is_engine_cause": 0,
 "is_model_cause": 0,
 "is_human_cause": 0,
 "is_weather_cause": 0,
 "is_wildlife_cause": 1,
 "is_ground_collision": 0,
 "is_unknown_cause": 0,
 "damage_area": ["right wing leading edge", "engine inlet"]
}}

NOW ANALYZE THIS CASE:
Text:
\"\"\"{case_text}\"\"\"

Return ONLY JSON for this case with exactly these keys:
{{
 "is_engine_cause": 0 or 1,
 "is_model_cause": 0 or 1,
 "is_human_cause": 0 or 1,
 "is_weather_cause": 0 or 1,
 "is_wildlife_cause": 0 or 1,
 "is_ground_collision": 0 or 1,
 "is_unknown_cause": 0 or 1,
 "damage_area": [ "part1", "part2", ... ]
}}
"""
    return prompt.strip()

In [ ]:
import re

def generate_json(case_text, max_new_tokens=256, temperature=0.1):
    prompt = build_prompt(case_text)

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=2048
    ).to(model.device)

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            do_sample=False
        )

    full_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)

    # Try to extract the LAST JSON block (our actual answer)
    try:
        matches = re.findall(r"\{[\s\S]*?\}", full_text)
        if not matches:
            raise ValueError("No JSON object found in model output.")
        json_str = matches[-1]   # take the LAST {...}
        data = json.loads(json_str)
    except Exception as e:
        # print("PARSE ERROR:", e)  # optional debug
        data = {
            "is_engine_cause": 0,
            "is_model_cause": 0,
            "is_human_cause": 0,
            "is_weather_cause": 0,
            "is_wildlife_cause": 0,
            "is_ground_collision": 0,
            "is_unknown_cause": 1,
            "damage_area": []
        }

    # Ensure all keys exist and have sane types
    default = {
        "is_engine_cause": 0,
        "is_model_cause": 0,
        "is_human_cause": 0,
        "is_weather_cause": 0,
        "is_wildlife_cause": 0,
        "is_ground_collision": 0,
        "is_unknown_cause": 0,
        "damage_area": []
    }
    for k, v in default.items():
        if k not in data:
            data[k] = v

    cause_keys = [
        "is_engine_cause",
        "is_model_cause",
        "is_human_cause",
        "is_weather_cause",
        "is_wildlife_cause",
        "is_ground_collision"
    ]
    if sum(int(data.get(k, 0)) for k in cause_keys) == 0 and int(data.get("is_unknown_cause", 0)) == 0:
        data["is_unknown_cause"] = 1

    da = data.get("damage_area", [])
    if not isinstance(da, list):
        da = [str(da)]
    data["damage_area"] = [str(x).strip() for x in da if str(x).strip()]

    return data

In [ ]:
from tqdm.auto import tqdm

results_new = []

for _, row in tqdm(new_df_source.iterrows(), total=len(new_df_source)):
    case_text = build_text(row.get("Narrative"), row.get("Incident_Cause(es)"))

    if case_text is None:
        res = {
            "is_engine_cause": 0,
            "is_model_cause": 0,
            "is_human_cause": 0,
            "is_weather_cause": 0,
            "is_wildlife_cause": 0,
            "is_ground_collision": 0,
            "is_unknown_cause": 1,
            "damage_area": []
        }
    else:
        res = generate_json(case_text)

    results_new.append(res)

  0%|          | 0/1930 [00:00<?, ?it/s]

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

In [ ]:
results_new_df = pd.DataFrame(results_new)

results_new_df.head()

,is_engine_cause,is_model_cause,is_human_cause,is_weather_cause,is_wildlife_cause,is_ground_collision,is_unknown_cause,damage_area,incident_cause_field,is_wake_vortex_cause,is_model_cause_details,probable_cause
0,0,0,0,0,0,1,0,[],NaN,NaN,NaN,NaN
1,0,0,0,1,0,0,0,"[left wing, nose, cockpit, right wing]",NaN,NaN,NaN,NaN
2,0,0,0,0,1,0,0,"[right wing leading edge, engine inlet]",NaN,NaN,NaN,NaN
3,0,0,0,0,0,1,0,[airplane],NaN,NaN,NaN,NaN
4,0,0,1,1,0,1,0,"[nose, landing gear, fuselage]",NaN,NaN,NaN,NaN

In [ ]:
print(len(results_new_df))
print(len(clean_df))

1930
5278

In [ ]:
print(processed_df.shape)
processed_df.head()

(3348, 49)

,Unnamed: 0.1,Unnamed: 0,Event_No,Incident_Date,Year,Time,Incident,Aircaft_Damage_Type,Aircraft_Phase,Occupants,...,is_model_cause,is_human_cause,is_weather_cause,is_wildlife_cause,is_ground_collision,is_unknown_cause,damage_area,cause,name,is_cause
0,0,0,1,2000-01-01,2000,13:00 LT,Accident,Substantial,Unknown,3.0,...,0.0,0.0,0.0,1.0,0.0,0.0,['right wing leading edge'],NaN,NaN,NaN
1,1,1,2,2000-01-03,2000,NaN,Unknown,Destroyed,Unknown,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,[],NaN,NaN,NaN
2,2,2,3,2000-01-04,2000,17:25 LT,Accident,Substantial,Unknown,3.0,...,0.0,1.0,1.0,0.0,1.0,0.0,['nose landing gear'],NaN,NaN,NaN
3,3,3,4,2000-01-05,2000,13:25,Accident,Destroyed,Approach,13.0,...,0.0,0.0,0.0,0.0,1.0,0.0,['farmland'],NaN,NaN,NaN
4,4,4,5,2000-01-07,2000,NaN,Accident,Missing,Unknown,8.0,...,0.0,0.0,0.0,0.0,0.0,1.0,[],NaN,NaN,NaN

In [ ]:
processed_df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Event_No', 'Incident_Date', 'Year',
       'Time', 'Incident', 'Aircaft_Damage_Type', 'Aircraft_Phase',
       'Occupants', 'Fatalities', 'Ground_Casualties', 'Collision_Casualties',
       'Incident_Location', 'geopy_query', 'Latitude', 'Longitude',
       'GeoStatus', 'Aircaft_Nature', 'Aircaft_Registration', 'Aircaft_Model',
       'Aircaft_Operator', 'Engine_Model', 'Departure_Airport',
       'Destination_Airport', 'Departure_Airport_Code',
       'Destination_Airport_Code', 'Departure_IATA', 'Destination_IATA',
       'Dep_Lat', 'Dep_Lon', 'Dest_Lat', 'Dest_Lon',
       'Aircraft_Manufacture_Year', 'Total_Flight_Hours', 'Confidence_Rating',
       'Narrative', 'Incident_Cause(es)', 'is_engine_cause', 'is_model_cause',
       'is_human_cause', 'is_weather_cause', 'is_wildlife_cause',
       'is_ground_collision', 'is_unknown_cause', 'damage_area'],
      dtype='object')

In [ ]:
processed_df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'], inplace=True)
processed_df.shape

(3348, 44)

In [ ]:
processed_df.columns

Index(['Event_No', 'Incident_Date', 'Year', 'Time', 'Incident',
       'Aircaft_Damage_Type', 'Aircraft_Phase', 'Occupants', 'Fatalities',
       'Ground_Casualties', 'Collision_Casualties', 'Incident_Location',
       'geopy_query', 'Latitude', 'Longitude', 'GeoStatus', 'Aircaft_Nature',
       'Aircaft_Registration', 'Aircaft_Model', 'Aircaft_Operator',
       'Engine_Model', 'Departure_Airport', 'Destination_Airport',
       'Departure_Airport_Code', 'Destination_Airport_Code', 'Departure_IATA',
       'Destination_IATA', 'Dep_Lat', 'Dep_Lon', 'Dest_Lat', 'Dest_Lon',
       'Aircraft_Manufacture_Year', 'Total_Flight_Hours', 'Confidence_Rating',
       'Narrative', 'Incident_Cause(es)', 'is_engine_cause', 'is_model_cause',
       'is_human_cause', 'is_weather_cause', 'is_wildlife_cause',
       'is_ground_collision', 'is_unknown_cause', 'damage_area'],
      dtype='object')

In [ ]:
new_df_source.head()

,Unnamed: 0.1,Unnamed: 0,Event_No,Incident_Date,Year,Time,Incident,Aircaft_Damage_Type,Aircraft_Phase,Occupants,...,is_model_cause,is_human_cause,is_weather_cause,is_wildlife_cause,is_ground_collision,is_unknown_cause,damage_area,cause,name,is_cause
0,3348,3348,3397,2011-08-31,2011,NaN,Accident,Substantial,Landing,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3349,3349,3398,2011-09-02,2011,17:48,Accident,Destroyed,Approach,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3350,3350,3399,2011-09-02,2011,13:35,Accident,Destroyed,En Route,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3351,3351,3400,2011-09-03,2011,12:00,Accident,Destroyed,Maneuvering,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3352,3352,3401,2011-09-04,2011,15:29,Accident,Destroyed,Landing,47.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
new_df_source.shape

(1930, 49)

In [ ]:
new_df_source.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Event_No', 'Incident_Date', 'Year',
       'Time', 'Incident', 'Aircaft_Damage_Type', 'Aircraft_Phase',
       'Occupants', 'Fatalities', 'Ground_Casualties', 'Collision_Casualties',
       'Incident_Location', 'geopy_query', 'Latitude', 'Longitude',
       'GeoStatus', 'Aircaft_Nature', 'Aircaft_Registration', 'Aircaft_Model',
       'Aircaft_Operator', 'Engine_Model', 'Departure_Airport',
       'Destination_Airport', 'Departure_Airport_Code',
       'Destination_Airport_Code', 'Departure_IATA', 'Destination_IATA',
       'Dep_Lat', 'Dep_Lon', 'Dest_Lat', 'Dest_Lon',
       'Aircraft_Manufacture_Year', 'Total_Flight_Hours', 'Confidence_Rating',
       'Narrative', 'Incident_Cause(es)', 'is_engine_cause', 'is_model_cause',
       'is_human_cause', 'is_weather_cause', 'is_wildlife_cause',
       'is_ground_collision', 'is_unknown_cause', 'damage_area', 'cause',
       'name', 'is_cause'],
      dtype='object')

In [ ]:
new_df_source.drop(columns=['Unnamed: 0.1', 'Unnamed: 0', 'is_engine_cause', 'is_model_cause',
       'is_human_cause', 'is_weather_cause', 'is_wildlife_cause',
       'is_ground_collision', 'is_unknown_cause', 'damage_area', 'cause',
       'name', 'is_cause'], inplace=True)
new_df_source.shape

(1930, 36)

In [ ]:
new_df_source.head()

,Event_No,Incident_Date,Year,Time,Incident,Aircaft_Damage_Type,Aircraft_Phase,Occupants,Fatalities,Ground_Casualties,...,Destination_IATA,Dep_Lat,Dep_Lon,Dest_Lat,Dest_Lon,Aircraft_Manufacture_Year,Total_Flight_Hours,Confidence_Rating,Narrative,Incident_Cause(es)
0,3397,2011-08-31,2011,NaN,Accident,Substantial,Landing,3.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,1989.0,NaN,NaN,An Antonov 2T airplane sustained substantial d...,Info-Unavailable
1,3398,2011-09-02,2011,17:48,Accident,Destroyed,Approach,21.0,21.0,0.0,...,SCI,-33.39300,-70.78580,7.80132,-72.20290,1994.0,NaN,NaN,"A CASA C-212 Aviocar transport plane, operated...","Result - Loss of control, Weather - Windshear/..."
2,3399,2011-09-02,2011,13:35,Accident,Destroyed,En Route,1.0,1.0,0.0,...,BET,60.50000,-165.10000,60.77856,-161.83717,2000.0,8483 hours,Accident investigation report completed and in...,"A Cessna 208B Grand Caravan airplane, N207DR, ...","Collision - Aircraft, Collision - Aircraft - I..."
3,3400,2011-09-03,2011,12:00,Accident,Destroyed,Maneuvering,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,1983.0,6010 hours,"Information is only available from news, socia...",An Antonov 2 airplane was destroyed in an acci...,Info-Unavailable
4,3401,2011-09-04,2011,15:29,Accident,Destroyed,Landing,47.0,0.0,0.0,...,YOW,41.97694,-87.90815,45.32250,-75.66920,2000.0,25655 hours,Accident investigation report completed and in...,An Embraer EMB-145LR passenger jet sustained s...,Result - Runway excursion

In [ ]:
results_new_df.head()

,is_engine_cause,is_model_cause,is_human_cause,is_weather_cause,is_wildlife_cause,is_ground_collision,is_unknown_cause,damage_area,incident_cause_field,is_wake_vortex_cause,is_model_cause_details,probable_cause
0,0,0,0,0,0,1,0,[],NaN,NaN,NaN,NaN
1,0,0,0,1,0,0,0,"[left wing, nose, cockpit, right wing]",NaN,NaN,NaN,NaN
2,0,0,0,0,1,0,0,"[right wing leading edge, engine inlet]",NaN,NaN,NaN,NaN
3,0,0,0,0,0,1,0,[airplane],NaN,NaN,NaN,NaN
4,0,0,1,1,0,1,0,"[nose, landing gear, fuselage]",NaN,NaN,NaN,NaN

In [ ]:
results_new_df.columns

Index(['is_engine_cause', 'is_model_cause', 'is_human_cause',
       'is_weather_cause', 'is_wildlife_cause', 'is_ground_collision',
       'is_unknown_cause', 'damage_area', 'incident_cause_field',
       'is_wake_vortex_cause', 'is_model_cause_details', 'probable_cause'],
      dtype='object')

In [ ]:
results_new_df.drop(columns=['incident_cause_field',
       'is_wake_vortex_cause', 'is_model_cause_details', 'probable_cause'], inplace=True)
results_new_df.shape

(1930, 8)

In [ ]:
results_new_df.head()

,is_engine_cause,is_model_cause,is_human_cause,is_weather_cause,is_wildlife_cause,is_ground_collision,is_unknown_cause,damage_area
0,0,0,0,0,0,1,0,[]
1,0,0,0,1,0,0,0,"[left wing, nose, cockpit, right wing]"
2,0,0,0,0,1,0,0,"[right wing leading edge, engine inlet]"
3,0,0,0,0,0,1,0,[airplane]
4,0,0,1,1,0,1,0,"[nose, landing gear, fuselage]"

In [ ]:
augmented_df = pd.concat(
    [new_df_source.reset_index(drop=True),
     results_new_df.reset_index(drop=True)],
    axis=1
)

augmented_df.shape

(1930, 44)

In [ ]:
print(processed_df.columns)

print(augmented_df.columns)

Index(['Event_No', 'Incident_Date', 'Year', 'Time', 'Incident',
       'Aircaft_Damage_Type', 'Aircraft_Phase', 'Occupants', 'Fatalities',
       'Ground_Casualties', 'Collision_Casualties', 'Incident_Location',
       'geopy_query', 'Latitude', 'Longitude', 'GeoStatus', 'Aircaft_Nature',
       'Aircaft_Registration', 'Aircaft_Model', 'Aircaft_Operator',
       'Engine_Model', 'Departure_Airport', 'Destination_Airport',
       'Departure_Airport_Code', 'Destination_Airport_Code', 'Departure_IATA',
       'Destination_IATA', 'Dep_Lat', 'Dep_Lon', 'Dest_Lat', 'Dest_Lon',
       'Aircraft_Manufacture_Year', 'Total_Flight_Hours', 'Confidence_Rating',
       'Narrative', 'Incident_Cause(es)', 'is_engine_cause', 'is_model_cause',
       'is_human_cause', 'is_weather_cause', 'is_wildlife_cause',
       'is_ground_collision', 'is_unknown_cause', 'damage_area'],
      dtype='object')
Index(['Event_No', 'Incident_Date', 'Year', 'Time', 'Incident',
       'Aircaft_Damage_Type', 'Aircraft_Phase', 'Occupants', 'Fatalities',
       'Ground_Casualties', 'Collision_Casualties', 'Incident_Location',
       'geopy_query', 'Latitude', 'Longitude', 'GeoStatus', 'Aircaft_Nature',
       'Aircaft_Registration', 'Aircaft_Model', 'Aircaft_Operator',
       'Engine_Model', 'Departure_Airport', 'Destination_Airport',
       'Departure_Airport_Code', 'Destination_Airport_Code', 'Departure_IATA',
       'Destination_IATA', 'Dep_Lat', 'Dep_Lon', 'Dest_Lat', 'Dest_Lon',
       'Aircraft_Manufacture_Year', 'Total_Flight_Hours', 'Confidence_Rating',
       'Narrative', 'Incident_Cause(es)', 'is_engine_cause', 'is_model_cause',
       'is_human_cause', 'is_weather_cause', 'is_wildlife_cause',
       'is_ground_collision', 'is_unknown_cause', 'damage_area'],
      dtype='object')

In [ ]:
print(len(processed_df))
print(len(augmented_df))
print(len(processed_df) + len(augmented_df))
print(len(clean_df))

3348
1930
5278
5278

In [ ]:
final_df = pd.concat(
    [processed_df, augmented_df],
    axis=0,
    ignore_index=True
)

final_df.to_csv("cleanest_df_with_full_NLP.csv", index=False)

In [ ]:
# clean_df = pd.concat([clean_df, results_df], axis=1)
# clean_df.to_csv('cleanest_df_with_NLP.csv')

# Different model starting here

In [ ]:
# !pip install -q transformers accelerate sentencepiece

In [ ]:
# from transformers import pipeline

# # combine cause + narrative into one text field
# def combine_text(row):
#     cause = str(row.get("Incident_Cause(es)", "") or "")
#     narr  = str(row.get("Narrative", "") or "")
#     return (cause + " " + narr).strip()

# new_df_copy["full_text"] = new_df_copy.apply(combine_text, axis=1)

# labels = [
#     "Did an internal engine or propulsion system failure directly cause the accident?",
#     "Did pilot, crew, or staff actions or decisions directly cause the accident?",
#     "Did weather or environmental conditions directly cause the accident?",
#     "Did a mechanical or structural failure of the aircraft (other than engines) directly cause the accident?",
#     "Did the aircraft collide with birds or wildlife?",
#     "Did the aircraft collide with a ground object or airport infrastructure?",
#     "Was the primary cause of the accident unknown or undetermined?",
#     "Did the aircraft experience a runway excursion or veer-off event as a result?",
#     "Did the flight lose control as a result?",
#     "Did emergency landing, forced landing, aborting happened as a result?"
# ]

# # zero-shot classifier (English, good general-purpose)
# classifier = pipeline(
#     "zero-shot-classification",
#     model="facebook/bart-large-mnli",   # or any NLI zero-shot model
#     device_map="auto"                  # uses GPU if available
# )

# def classify_causes(text, threshold=0.35):
#     if not text or text.strip() == "":
#         return {lbl: 0 for lbl in labels}

#     result = classifier(
#         text,
#         candidate_labels=labels,
#         multi_label=True
#     )

#     # result["labels"] are sorted by score
#     scores = dict(zip(result["labels"], result["scores"]))
#     return {lbl: int(scores.get(lbl, 0.0) >= threshold) for lbl in labels}

# # apply to your dataframe
# cause_flags = new_df_copy["full_text"].apply(classify_causes)

# # convert list of dicts -> columns
# flags_df = pd.DataFrame(list(cause_flags))

# # give nicer column names
# rename_map = {
#     "Did an internal engine or propulsion system failure directly cause the accident?": "is_engine_cause",
#     "Did pilot, crew, or staff actions or decisions directly cause the accident?": "is_crew_cause",
#     "Did weather or environmental conditions directly cause the accident?": "is_weather_cause",
#     "Did a mechanical or structural failure of the aircraft (other than engines) directly cause the accident?": "is_model_cause",
#     "Did the aircraft collide with birds or wildlife?": "is_bird_or_animal",
#     "Did the aircraft collide with a ground object or airport infrastructure?": "is_ground_collision",
#     "Was the primary cause of the accident unknown or undetermined?": "is_unknown_cause",
#     "Did the aircraft experience a runway excursion or veer-off event?": "result_runway_excursion",
#     "Did the flight lose control?": "result_lose_control",
#     "Did emergency landing, forced landing, aborting happened as a result?": "result_forced_landing"
# }

# flags_df = flags_df.rename(columns=rename_map)

# # attach back to df
# new_df_copy = pd.concat([new_df_copy, flags_df], axis=1)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

# Damage Analysis

In [ ]:
final_df.head()

,Event_No,Incident_Date,Year,Time,Incident,Aircaft_Damage_Type,Aircraft_Phase,Occupants,Fatalities,Ground_Casualties,...,Narrative,Incident_Cause(es),is_engine_cause,is_model_cause,is_human_cause,is_weather_cause,is_wildlife_cause,is_ground_collision,is_unknown_cause,damage_area
0,1,2000-01-01,2000,13:00 LT,Accident,Substantial,Unknown,3.0,0.0,0.0,...,The pilot-in-command (PIC) stated he was in cr...,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,['right wing leading edge']
1,2,2000-01-03,2000,NaN,Unknown,Destroyed,Unknown,NaN,NaN,0.0,...,Damaged beyond repair.,Info-Unavailable,0.0,0.0,0.0,0.0,0.0,0.0,1.0,[]
2,3,2000-01-04,2000,17:25 LT,Accident,Substantial,Unknown,3.0,0.0,0.0,...,While performing the ILS runway 18 approach to...,NaN,0.0,0.0,1.0,1.0,0.0,1.0,0.0,['nose landing gear']
3,4,2000-01-05,2000,13:25,Accident,Destroyed,Approach,13.0,1.0,1.0,...,The Bandeirante aircraft was coming in to land...,Result - Loss of control,0.0,0.0,0.0,0.0,0.0,1.0,0.0,['farmland']
4,5,2000-01-07,2000,NaN,Accident,Missing,Unknown,8.0,NaN,0.0,...,Disappeared near the border of the Angolan pro...,Unknown - Missing,0.0,0.0,0.0,0.0,0.0,0.0,1.0,[]

In [ ]:
final_df.shape

(5278, 44)

In [ ]:
url = "https://raw.githubusercontent.com/oshani-jayawardane/aircraft-accident-project/main/cleanest_df_with_NLP.csv"
new_final_df = pd.read_csv(url)

new_final_df.head()

,Event_No,Incident_Date,Year,Time,Incident,Aircaft_Damage_Type,Aircraft_Phase,Occupants,Fatalities,Ground_Casualties,...,is_model_cause,is_human_cause,is_weather_cause,is_wildlife_cause,is_ground_collision,is_unknown_cause,damage_area,Engine_Model_Standardized,Aircraft_Manufacturer,Engine_Manufacturer
0,1,2000-01-01,2000,13:00 LT,Accident,Substantial,Unknown,3.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,['right wing leading edge'],Pratt & Whitney JT15D-4,Cessna,Pratt & Whitney
1,2,2000-01-03,2000,NaN,Unknown,Destroyed,Unknown,NaN,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,[],NaN,Beechcraft,NaN
2,3,2000-01-04,2000,17:25 LT,Accident,Substantial,Unknown,3.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,['nose landing gear'],Pratt & Whitney PT6-A-42,Beechcraft,Pratt & Whitney
3,4,2000-01-05,2000,13:25,Accident,Destroyed,Approach,13.0,1.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,['farmland'],Pratt & Whitney Canada PT6A-34,Embraer,Pratt & Whitney
4,5,2000-01-07,2000,NaN,Accident,Missing,Unknown,8.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,[],Ivchenko AI-24,Antonov,Ivchenko

In [ ]:
new_final_df.columns

Index(['Event_No', 'Incident_Date', 'Year', 'Time', 'Incident',
       'Aircaft_Damage_Type', 'Aircraft_Phase', 'Occupants', 'Fatalities',
       'Ground_Casualties', 'Collision_Casualties', 'Incident_Location',
       'geopy_query', 'Latitude', 'Longitude', 'GeoStatus', 'Aircaft_Nature',
       'Aircaft_Registration', 'Aircaft_Model', 'Aircaft_Operator',
       'Engine_Model', 'Departure_Airport', 'Destination_Airport',
       'Departure_Airport_Code', 'Destination_Airport_Code', 'Departure_IATA',
       'Destination_IATA', 'Dep_Lat', 'Dep_Lon', 'Dest_Lat', 'Dest_Lon',
       'Aircraft_Manufacture_Year', 'Total_Flight_Hours', 'Confidence_Rating',
       'Narrative', 'Incident_Cause(es)', 'is_engine_cause', 'is_model_cause',
       'is_human_cause', 'is_weather_cause', 'is_wildlife_cause',
       'is_ground_collision', 'is_unknown_cause', 'damage_area',
       'Engine_Model_Standardized', 'Aircraft_Manufacturer',
       'Engine_Manufacturer'],
      dtype='object')

In [ ]:
new_final_df['damage_area']

0                             ['right wing leading edge']
1                                                      []
2                                   ['nose landing gear']
3                                            ['farmland']
4                                                      []
                              ...
5273                                                   []
5274                                                   []
5275    ['nose landing gear', 'pressure vessel aft of ...
5276                                     ['no. 2 engine']
5277                                                   []
Name: damage_area, Length: 5278, dtype: object

In [ ]:
new_final_df['damage_area'].unique()

array(["['right wing leading edge']", '[]', "['nose landing gear']", ...,
       "['cockpit section']",
       "['nose section', 'avionics', 'fuselage skin', 'wing leading edge']",
       "['nose landing gear', 'pressure vessel aft of gear attach bulkhead']"],
      dtype=object)

In [ ]:
import re

def simplify_damage(entry):
    # entry can be a string or a list of strings
    if isinstance(entry, list):
        text = " ".join(str(x) for x in entry if x is not None)
    else:
        text = "" if entry is None else str(entry)

    t = text.lower().strip()
    if t == "" or t in {"-", "none", "n/a", "n\\a", "unknown", "undetermined", "unreported", "unspecified"}:
        return []

    cats = set()

    # ---------- WING ----------
    if re.search(r"\bwing\b|\bwings\b|\bwingtip\b|\bwing tip\b|\bwinglet\b|\bslat\b|\bslats\b|\baileron\b|\bflap\b|\bflaps\b|\bspar\b|\bmainplane\b", t):
        cats.add("wing")

    # ---------- ENGINE ----------
    if ("engine" in t or "nacelle" in t or "cowling" in t or "pylon" in t or
        "apu" in t or "fan" in t or "turbine" in t or "jet engine" in t or
        "propeller" in t or "props" in t or re.search(r"\bprop\b", t)):
        # folding propeller into engine to keep categories simple
        cats.add("engine")

    # ---------- TAIL ----------
    if ("tail" in t or "empennage" in t or "tailplane" in t or
        "vertical stabilizer" in t or "horizontal stabilizer" in t or
        "stabilizer" in t or "tail cone" in t or "tail skid" in t or
        "fin" in t or "rudder" in t or "elevator" in t or "tail boom" in t):
        cats.add("tail")

    # ---------- NOSE ----------
    if ("nose" in t or "radome" in t or
        "cockpit" in t or "flight deck" in t or "flight compartment" in t or
        "windshield" in t or "windscreen" in t or
        "below captain's window" in t or "below first officer's window" in t):
        cats.add("nose")

    # ---------- FUSELAGE ----------
    if ("fuselage" in t or "airframe" in t or "aircraft body" in t or
        "airplane body" in t or "hull" in t or "pressure vessel" in t or
        "pressure body" in t or "cabin" in t or "belly" in t or
        "underside of fuselage" in t or "ventral" in t or
        "bulkhead" in t or "stringer" in t or "frame " in t or "skin" in t):
        cats.add("fuselage")

    # ---------- LANDING GEAR ----------
    if ("landing gear" in t or "landing-gear" in t or
        "undercarriage" in t or "gear " in t or t.startswith("gear") or
        "nose gear" in t or "nosewheel" in t or "nose wheel" in t or
        "main gear" in t or "main landing gear" in t or
        "mlg" in t or "nlg" in t or
        "strut" in t or "oleo" in t or "bogie" in t or
        "wheel well" in t or "wheel wells" in t or
        "wheel" in t or "wheels" in t or "tyre" in t or "tire" in t):
        cats.add("landing gear")

    return sorted(cats)

In [ ]:
new_final_df["Damage_Areas"] = new_final_df["damage_area"].apply(simplify_damage)

In [ ]:
comp_df = new_final_df[["Damage_Areas", "damage_area"]]

In [ ]:
new_final_df.columns

Index(['Event_No', 'Incident_Date', 'Year', 'Time', 'Incident',
       'Aircaft_Damage_Type', 'Aircraft_Phase', 'Occupants', 'Fatalities',
       'Ground_Casualties', 'Collision_Casualties', 'Incident_Location',
       'geopy_query', 'Latitude', 'Longitude', 'GeoStatus', 'Aircaft_Nature',
       'Aircaft_Registration', 'Aircaft_Model', 'Aircaft_Operator',
       'Engine_Model', 'Departure_Airport', 'Destination_Airport',
       'Departure_Airport_Code', 'Destination_Airport_Code', 'Departure_IATA',
       'Destination_IATA', 'Dep_Lat', 'Dep_Lon', 'Dest_Lat', 'Dest_Lon',
       'Aircraft_Manufacture_Year', 'Total_Flight_Hours', 'Confidence_Rating',
       'Narrative', 'Incident_Cause(es)', 'is_engine_cause', 'is_model_cause',
       'is_human_cause', 'is_weather_cause', 'is_wildlife_cause',
       'is_ground_collision', 'is_unknown_cause', 'damage_area',
       'Engine_Model_Standardized', 'Aircraft_Manufacturer',
       'Engine_Manufacturer', 'Damage_Areas'],
      dtype='object')

In [ ]:
new_final_df.to_csv("cleanest_df_with_NLP.csv", index=False)

In [ ]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/oshani-jayawardane/aircraft-accident-project/main/cleanest_df_with_NLP.csv"
df = pd.read_csv(url)

df.head()

,Event_No,Incident_Date,Year,Time,Incident,Aircaft_Damage_Type,Aircraft_Phase,Occupants,Fatalities,Ground_Casualties,...,is_human_cause,is_weather_cause,is_wildlife_cause,is_ground_collision,is_unknown_cause,damage_area,Engine_Model_Standardized,Aircraft_Manufacturer,Engine_Manufacturer,Damage_Areas
0,1,2000-01-01,2000,13:00 LT,Accident,Substantial,Unknown,3.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,['right wing leading edge'],Pratt & Whitney JT15D-4,Cessna,Pratt & Whitney,['wing']
1,2,2000-01-03,2000,NaN,Unknown,Destroyed,Unknown,NaN,NaN,0.0,...,0.0,0.0,0.0,0.0,1.0,[],NaN,Beechcraft,NaN,[]
2,3,2000-01-04,2000,17:25 LT,Accident,Substantial,Unknown,3.0,0.0,0.0,...,1.0,1.0,0.0,1.0,0.0,['nose landing gear'],Pratt & Whitney PT6-A-42,Beechcraft,Pratt & Whitney,"['landing gear', 'nose']"
3,4,2000-01-05,2000,13:25,Accident,Destroyed,Approach,13.0,1.0,1.0,...,0.0,0.0,0.0,1.0,0.0,['farmland'],Pratt & Whitney Canada PT6A-34,Embraer,Pratt & Whitney,[]
4,5,2000-01-07,2000,NaN,Accident,Missing,Unknown,8.0,NaN,0.0,...,0.0,0.0,0.0,0.0,1.0,[],Ivchenko AI-24,Antonov,Ivchenko,[]

In [ ]:
from google.colab import files
import pandas as pd

# upload file
uploaded = files.upload()

# assuming only one file uploaded
file_name = list(uploaded.keys())[0]

# read into dataframe
other_df = pd.read_csv(file_name)

other_df.head()

Saving with_engine_aircraft_manufacturer (2).csv to with_engine_aircraft_manufacturer (2).csv

,Unnamed: 0.1,Unnamed: 0,Event_No,Incident_Date,Year,Time,Incident,Aircaft_Damage_Type,Aircraft_Phase,Occupants,...,Dest_Lon,Aircraft_Manufacture_Year,Total_Flight_Hours,Confidence_Rating,Narrative,Incident_Cause(es),Engine_Model_Standardized,Engine_Manufacturer_Robust,Aircraft_Manufacturer,Engine_Manufacturer
0,0,0,1,2000-01-01,2000,13:00 LT,Accident,Substantial,Unknown,3.0,...,56.24060,NaN,12159 hours,Accident investigation report completed and in...,The pilot-in-command (PIC) stated he was in cr...,NaN,Pratt & Whitney ratt & Whitney JT15D-4,Pratt & Whitney,Cessna,Pratt & Whitney
1,1,1,2,2000-01-03,2000,NaN,Unknown,Destroyed,Unknown,NaN,...,NaN,1978.0,NaN,Little or no information is available,Damaged beyond repair.,Info-Unavailable,NaN,NaN,Beechcraft,NaN
2,2,2,3,2000-01-04,2000,17:25 LT,Accident,Substantial,Unknown,3.0,...,92.49330,1986.0,3238 hours,Accident investigation report completed and in...,While performing the ILS runway 18 approach to...,NaN,Pratt & Whitney ratt & Whitney Pratt & Whitney...,Pratt & Whitney,Beechcraft,Pratt & Whitney
3,3,3,4,2000-01-05,2000,13:25,Accident,Destroyed,Approach,13.0,...,7.26317,1984.0,NaN,Information verified through data from acciden...,The Bandeirante aircraft was coming in to land...,Result - Loss of control,Pratt & Whitney ratt & Whitney Canada Pratt & ...,Pratt & Whitney,Embraer,Pratt & Whitney
4,4,4,5,2000-01-07,2000,NaN,Accident,Missing,Unknown,8.0,...,17.98970,1978.0,NaN,NaN,Disappeared near the border of the Angolan pro...,Unknown - Missing,Ivchenko AI-24,Ivchenko,Antonov,Ivchenko

In [ ]:
other_df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Event_No', 'Incident_Date', 'Year',
       'Time', 'Incident', 'Aircaft_Damage_Type', 'Aircraft_Phase',
       'Occupants', 'Fatalities', 'Ground_Casualties', 'Collision_Casualties',
       'Incident_Location', 'geopy_query', 'Latitude', 'Longitude',
       'GeoStatus', 'Aircaft_Nature', 'Aircaft_Registration', 'Aircaft_Model',
       'Aircaft_Operator', 'Engine_Model', 'Departure_Airport',
       'Destination_Airport', 'Departure_Airport_Code',
       'Destination_Airport_Code', 'Departure_IATA', 'Destination_IATA',
       'Dep_Lat', 'Dep_Lon', 'Dest_Lat', 'Dest_Lon',
       'Aircraft_Manufacture_Year', 'Total_Flight_Hours', 'Confidence_Rating',
       'Narrative', 'Incident_Cause(es)', 'Engine_Model_Standardized',
       'Engine_Manufacturer_Robust', 'Aircraft_Manufacturer',
       'Engine_Manufacturer'],
      dtype='object')

In [ ]:
other_df.head(20)

,Unnamed: 0.1,Unnamed: 0,Event_No,Incident_Date,Year,Time,Incident,Aircaft_Damage_Type,Aircraft_Phase,Occupants,...,Dest_Lon,Aircraft_Manufacture_Year,Total_Flight_Hours,Confidence_Rating,Narrative,Incident_Cause(es),Engine_Model_Standardized,Engine_Manufacturer_Robust,Aircraft_Manufacturer,Engine_Manufacturer
0,0,0,1,2000-01-01,2000,13:00 LT,Accident,Substantial,Unknown,3.0,...,56.24060,NaN,12159 hours,Accident investigation report completed and in...,The pilot-in-command (PIC) stated he was in cr...,NaN,Pratt & Whitney ratt & Whitney JT15D-4,Pratt & Whitney,Cessna,Pratt & Whitney
1,1,1,2,2000-01-03,2000,NaN,Unknown,Destroyed,Unknown,NaN,...,NaN,1978.0,NaN,Little or no information is available,Damaged beyond repair.,Info-Unavailable,NaN,NaN,Beechcraft,NaN
2,2,2,3,2000-01-04,2000,17:25 LT,Accident,Substantial,Unknown,3.0,...,92.49330,1986.0,3238 hours,Accident investigation report completed and in...,While performing the ILS runway 18 approach to...,NaN,Pratt & Whitney ratt & Whitney Pratt & Whitney...,Pratt & Whitney,Beechcraft,Pratt & Whitney
3,3,3,4,2000-01-05,2000,13:25,Accident,Destroyed,Approach,13.0,...,7.26317,1984.0,NaN,Information verified through data from acciden...,The Bandeirante aircraft was coming in to land...,Result - Loss of control,Pratt & Whitney ratt & Whitney Canada Pratt & ...,Pratt & Whitney,Embraer,Pratt & Whitney
4,4,4,5,2000-01-07,2000,NaN,Accident,Missing,Unknown,8.0,...,17.98970,1978.0,NaN,NaN,Disappeared near the border of the Angolan pro...,Unknown - Missing,Ivchenko AI-24,Ivchenko,Antonov,Ivchenko
5,5,5,6,2000-01-07,2000,15:44,Accident,Substantial,Landing,2.0,...,NaN,1970.0,NaN,Information verified through data from acciden...,"NWL100, a Beech King Air with 2 crew, was trai...",NaN,NaN,NaN,Beechcraft,NaN
6,6,6,7,2000-01-09,2000,18:00,Accident,Repairable,Approach,3.0,...,100.27700,1972.0,NaN,NaN,"On approach to Penang runway 22, the aircraft ...",Info-Unavailable,Pratt & Whitney ratt & Whitney JT9D-7A,Pratt & Whitney,Boeing,Pratt & Whitney
7,7,7,8,2000-01-10,2000,17:56,Accident,Destroyed,En Route,10.0,...,13.76720,1990.0,21674 hours,Accident investigation report completed and in...,"At 17:00 Saab 340 HB-AKK arrived at Zurich, Sw...",Result - Loss of control,General Electric neral Electric CT7-9B,General Electric,Saab,General Electric
8,8,8,9,2000-01-11,2000,22:51 LT,Accident,Unknown,En Route,44.0,...,NaN,1989.0,NaN,Accident investigation report completed and in...,One flight attendant sustained serious injurie...,NaN,Rolls-Royce e RB211-535E4,Rolls-Royce,Boeing,Rolls-Royce
9,9,9,10,2000-01-13,2000,14:38,Accident,Destroyed,Approach,41.0,...,19.57640,1990.0,7138 hours,Accident investigation report completed and in...,The Shorts 360 plane had been leased to Sirte ...,"Airplane - Engines, Airplane - Engines - All e...",Pratt & Whitney ratt & Whitney Canada Pratt & ...,Pratt & Whitney,Shorts,Pratt & Whitney
10,10,10,11,2000-01-14,2000,14:30,Accident,Repairable,Taxi,NaN,...,NaN,1976.0,867 hours,NaN,A Hawker Siddeley HS-748 transport plane susta...,"Collision - Object, Collision - Object - Airpo...",Rolls-Royce e Dart 534-2,Rolls-Royce,Hawker,Rolls-Royce
11,11,11,12,2000-01-14,2000,12:16,Accident,Destroyed,Takeoff,31.0,...,-64.91800,1960.0,NaN,NaN,"Departed the left side of runway 35, about 600...",Result - Runway excursion,Allison T56-A-7,Allison,Lockheed,Allison
12,12,12,13,2000-01-15,2000,13:04,Accident,Destroyed,En Route,18.0,...,-83.51480,1986.0,NaN,Accident investigation report completed and in...,The airplane was ferried from the internationa...,"Cargo - CofG, Collision - Object, Collision - ...",Walter M-601E,Walter,Let,Walter
13,13,13,14,2000-01-17,2000,1:30,Accident,Unknown,Takeoff,NaN,...,NaN,NaN,NaN,Information verified through data from acciden...,The takeoff was aborted due to an engine fire ...,NaN,Pratt & Whitney ratt & Whitney Pratt & Whitney...,Pratt & Whitney,Airbus,Pratt & Whitney
14,14,14,15,2000-01-17,2000,16:15,Accident,Unknown,En Route,50.0,...,NaN,1989.0,NaN,Accident investigation report completed and in...,Before the flight the commander informed the c...,NaN,Pratt & Whitney ratt & Whitney Canada Pratt & ...,Pratt & Whitney,Fokker,Pratt & Whitney
15,15,15,16,2000-01-19,2000,23:07 LT,Accident,Substantial,Unknown,1.0,...,NaN,1988.0,7557 hours,Accident investigation report completed and in...,"According to the pilot's written statement, he...",NaN,Pratt & Whitney ratt & Whitney Pratt & Whitney...,Pratt & Whitney,Cessna,Pratt & Whitney
16,16,16,17,2000-01-20,2000,06:55,Accident,Repairable,Takeoff,152.0,...,-2.37010,1991.0,NaN,Accident investigation report completed and in...,"As the aircraft rotated for take off, both fan...","Airplane - Engines, Airplane - Engines - Loss/...",International Aero Engines V2500-A1,International Aero Engines,Airbus,International Aero Engines
17,17,17,18,2000-01-27,2000,10:15,Accident,Destroyed,Landing,6.0,...,-96.85088,1982.0,5266 hours,Accident investigation report completed and in...,The flight departed Austin at 09:40 on an IFR ...,Result - Runway excursion,Pratt & Whitney ratt & Whitney JT15D-4D,Pratt & Whitney,Mitsubishi,Pratt & Whitney
18,18,18,19,2000-01-28,2000,21:30 LT,Accident,Substantial,Unknown,2.0,...,NaN,1985.0,14251 hours,Accident investigation report completed and in...,On departure for the night air taxi cargo flig...,NaN,Honeywell TPratt & Whitney E331,Pratt & Whitney,Fairchild,Honeywell
19,19,19,20,2000-01-30,2000,21:09,Accident,Destroyed,En Route,179.0,...,3.32116,1986.0,58115 hours,Accident investigation report completed and in...,"Kenya Airways flight 431, an Airbus A310, cras...",Result - CFIT - Water,General Electric CF6-80C2A2,General Electric,Airbus,General Electric

In [ ]:
cols = ["Engine_Model_Standardized", "Aircraft_Manufacturer", "Engine_Manufacturer"]

df[cols] = other_df[cols].values

In [ ]:
df.to_csv("updated_dataset.csv", index=False)